### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rekire** [781flyingdutchman/background_downloader#1]
I'm trying to understand how you build your library. I noticed that you are using `httpConnection.contentLengthLong` in [DownloadWorker:260](https://github.com/781flyingdutchman/background_downloader/blob/b0daefd47bcbe72e24c3e62c8e633f0d946f9557/android/src/main/kotlin/com/bbflight/background_downloader/DownloadWorker.kt#L260), this requires API level 24, but you can replace it with this one liner:

```kotlin
val contentLength = httpConnection.getHeaderField("content-length").toLongOrNull() ?: -1
```

You should also limit your response code handling to 200 to download the file. A 206 for "Partial Content" is currently not supported by your code.

**Comment by 781flyingdutchman** [comment]
Thanks! I've left the original code as I am comfortable with a minSDK of 24, and I have updated the response code handling to exclude 206. Implemented in V1.1.0
