### ISSUE TITLE
Multiple callback for a single group?

### ISSUE THREAD

**Issue by markst** [781flyingdutchman/background_downloader#10]
Perhaps I need to adjust my implementation. 

I have multiple widgets which I wish to observe download status/progress.

One such example is comparing the `task.taskId` and updating the widget state:

```dart
@override
void initState() {
  super.initState();

  FileDownloader.registerCallbacks(downloadStatusCallback: (task, status) {
    if (task.taskId == _taskId) {
      setState(() {
        _downloadStatus = status;
      });
    }
  }, downloadProgressCallback: (task, progress) {
    if (task.taskId == _taskId) {
      setState(() {
        _progress = progress;
      });
    }
  });
}
```

**Comment by markst** [comment]
What ends up happening is only the last widget subscribes can observe the download state/progress.

**Comment by markst** [comment]
Perhaps I need to create an isolate or stream in which my widget subscribes. 

```dart
void downloadStatusCallback(BackgroundDownloadTask task, DownloadTaskStatus status) {
  IsolateNameServer.lookupPortByName(task.taskId)?.send([task.taskId, status, 0.0]);
}

void downloadProgressCallback(BackgroundDownloadTask task, double progress) {
  IsolateNameServer.lookupPortByName(task.taskId)?.send([task.taskId, DownloadTaskStatus.running, progress]);
}
```

**Comment by 781flyingdutchman** [comment]
Hi. If I understand correctly you want every widget to have its own callback, and presumably the code you show at the top is the code for the widget where you register the listener?  If so, it's really simple: assign a unique group name to the listener for each widget, and make sure your task is created with `group` set to that group name.

Assuming you have a unique id for each widget (for example its key, or if it only loads one task the taskId of that task), just register the callback with `group` set to that unique id. For example:
```
FileDownloader.registerCallbacks(group: the_widget_id, downloadStatusCallback: (task, status) {
    if (task.taskId == _taskId) {
      setState(() {
        _downloadStatus = status;
      });
    }
  }, downloadProgressCallback: (task, progress) {
    if (task.taskId == _taskId) {
      setState(() {
        _progress = progress;
      });
    }
  });
}
```

and create the task with `group: the_widget_id`.

Without this (the way you had it) you overwrite the 'default' callback in every widget, so only the last one gets all the updates. There is really no need for complicated isolate stuff.

**Comment by markst** [comment]
Thanks for pointers @781flyingdutchman! assigning a unique group name to listener for each widget solved it!
 
![Simulator Screen Recording - iPhone 14 - 2023-02-11 at 11 50 49](https://user-images.githubusercontent.com/274318/218228027-f8628c2f-dd62-46f0-9ac8-8805ebdbeb38.gif)

**Comment by 781flyingdutchman** [comment]
Glad it worked, and that screen looks beautiful!

**Comment by 781flyingdutchman** [comment]
@markst I just published version 3.0.0 of the downloader. It adds uploads and cleans up the API a bit (so will require some renaming of classes and enums) and it also adds anonymous callbacks for regular downloads, inspired by your use case.

In your widget you should now be able to simply do:
```
  final _task = DownloadTask(....);
  FileDownloader.download(_task, 
      onStatus: (status)  => setState(() {
        _downloadStatus = status;
      }),
      onProgress: (progress) => setState(() {
        _progress = progress;
      }));
```

No need to register callbacks or define groups, as the `onStatus` and `onProgress` callbacks you define here as anonymous functions are directly associated with this specific task only.  Note that `FileDownloader.download` returns a `Future<TaskStatus>` which is ignored in the example above, as you already act on status updates via the callback.

Hope this is helpful.

**Comment by markst** [comment]
Sounds great. Although potentially changes now mean only one set of callbacks can be registered. 

Previously both of these would subscribers would receive callbacks:

```dart
FileDownloader.initialize(
    taskStatusCallback: downloadStatusCallback, //
    taskProgressCallback: downloadProgressCallback);
```

```dart
FileDownloader.registerCallbacks(
    group: widget.episode.timestamp ?? "default",
    taskStatusCallback: (task, status) {
```

Will do some more debugging tomorrow.

**Comment by 781flyingdutchman** [comment]
If you use the 'new' way to call download (passing in an anonymous callback for `onStatus` or `onProgress`) then the centrally registered callbacks (via `initialize` or `registerCallbacks`) will not be called. The anonymous callbacks are only for that specific download, not a general callback that all tasks will report to, so I figured it might be a better fit for your widget-specific callback (no need for a widget Id anymore) but if it's not a better design for you then of course stick with the centrally registered callback!
