### ISSUE TITLE
Every time when I download a big file the download Failed

### ISSUE THREAD

**Issue by OmarASharaf** [781flyingdutchman/background_downloader#114]
when I download big file I get this error when the progress download goes to 80% or 90% the download failed

Read error: ssl=0x75797b7308: I/O error during system call, Connection reset by peer

I am using the last version of this package

**Comment by 781flyingdutchman** [comment]
Thanks for reaching out. Unfortunately that error says it's an issue with the server you are connecting to.

**Comment by 781flyingdutchman** [comment]
You can follow issue #102 that is about resuming (or retrying) a failed task without starting from scratch. This won't solve the problem you're describing, but may make it easier to recover.
