### ISSUE TITLE
How to disable this downloader for android devices below android 7.0?

### ISSUE THREAD

**Issue by hamidhandid** [781flyingdutchman/background_downloader#115]
Hi, Thanks for your awesome package.
I want to use your package just for android 7.0 and above because your package has minSDK of 24 for android platform. I want to use another custom downloader for android devices below 7.0. How can I do that?
@781flyingdutchman

**Comment by 781flyingdutchman** [comment]
Hi, I don't know how to do that, so let's leave this issue open and see if someone else can help.

**Comment by beroso** [comment]
@hamidhandid I don't have experience with it but I think Android build variants can be useful for your purpose:

https://developer.android.com/build/build-variants

**Comment by 781flyingdutchman** [comment]
Version 8.0.5 now supports minSdk 21

**Comment by hamidhandid** [comment]
> Version 8.0.5 now supports minSdk 21

Good job! Thanks!
