### ISSUE TITLE
File downloading working in IOS Simulator but not in real device

### ISSUE THREAD

**Issue by frsarker** [781flyingdutchman/background_downloader#117]
**Problem**
I am using background_downloader 7.9.0 in my flutter project. File downloading is working in Android Device as well as in IOS simulator. But when build the IOS app (IPA) and installed it in my iPhone 12 Pro Max, the downloading is not happening. In Notification, I just get "Downloading", but it never become "Download finished".

I don't have my Mac, I use remote Mac PC from where I generate the IPA and then install in my device, thats why I am unable to see live error happening.

**My Code**

```
Future<void> downloadFile(String url, String cookieString) async {
  if (await requestPermission("storage")) {
    await requestPermission("notification");

    FileDownloader().registerCallbacks(taskNotificationTapCallback:
        (Task task, NotificationType notificationType) async {

    });



    FileDownloader().configureNotification(
        running: const TaskNotification('Downloading', 'file: {filename}'),
        complete:
            const TaskNotification('Download finished', 'file: {filename}'),
        progressBar: true,
        tapOpensFile: true);

    final task = await DownloadTask(
      url: url,
      headers: {'Cookie': cookieString},
      baseDirectory: BaseDirectory.applicationDocuments,
      updates: Updates.statusAndProgress,
      retries: 5,
      allowPause: true,
    ).withSuggestedFilename(unique: true);



    await FileDownloader().download(task,
        onProgress: (progress) => print('Progress: ${progress * 100}%'),
        onStatus: (status) async {
          if (status == TaskStatus.complete) {

          }
        });
  }
```

**Comment by 781flyingdutchman** [comment]
Hi, hard to debug this way - you should probably find a way to "log" messages in release (eg by writing then to the screen our to a server).

Have you [set it up](https://github.com/781flyingdutchman/background_downloader#ios) properly, and confirm you're using https URLs?

**Comment by frsarker** [comment]
Yes my setup is properly done as everything is working correctly in xcode simulator and the file is https.

I will be trying to output the log now and let you know.
