### ISSUE TITLE
Close notification after file is opened

### ISSUE THREAD

**Issue by AlexPopaUpcode** [781flyingdutchman/background_downloader#122]
Hello,
I have started using this package recently and I am using notifications to notify the user about the download status. The notifications are working very good, they also open the downloaded file when they are tapped.

I would like to know if there is any possibility of closing a notification after it was tapped and file was opened. At the moment user have to swipe the notification to get rid of it. Usually other notifications (from other apps) will be closed after user taps them. 
This behaviour is on Android devices.

**Comment by 781flyingdutchman** [comment]
Hi, thanks for your suggestion. Sounds like a good idea - I'll add this but it may take a bit. Are you using the `tapOpensFile` feature or have you registered a notification tap callback?

**Comment by AlexPopaUpcode** [comment]
Thank you for the news 😄 I have registered a notification tap callback

**Comment by 781flyingdutchman** [comment]
Published in V7.9.4
