### ISSUE TITLE
can't build app in web

### ISSUE THREAD

**Issue by abbasnazari-0** [781flyingdutchman/background_downloader#123]
Hello  publisher

when i build my app for web 
/C:/Users/ABBAS/.puro/shared/pub_cache/hosted/pub.dev/background_downloader-7.9.3/lib/src/desktop_downloader_isolate.dart:37:36: Error: Member not found: 'BackgroundIsolateBinaryMessenger.ensureInitialized'.
  BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);
                                  ^^^^^^^^^^^^^^^^^
Failed to compile application.
Exited (sigterm)

this error occurred 
and my app exited 

should web app build and not work in running status app 
but not in building

**Comment by 781flyingdutchman** [comment]
The background downloader does not support the web platform, sorry.

**Comment by abbasnazari-0** [comment]
yes i know 
But it should not interfere with building for web

**Comment by 781flyingdutchman** [comment]
I can see how that would be valuable, but I don't know how to do that. It seems this would require some conditional build process and I am not aware of one. Perhaps you can do a conditional import?

**Comment by 781flyingdutchman** [comment]
Please follow #124 and test the development branch to see if this works for you

**Comment by abbasnazari-0** [comment]
thank you 
yes this work for me
