### ISSUE TITLE
Is it necessary to add an isolate?

### ISSUE THREAD

**Issue by willsalasare** [781flyingdutchman/background_downloader#127]
It gets too slow when there are a lot of downloads, like it's 1 fps, then it crashes, I was wondering if it's necessary to add isolate?

**Comment by hylsabella** [comment]
> It gets too slow when there are a lot of downloads, like it's 1 fps, then it crashes, I was wondering if it's necessary to add isolate?

It seems like the code is already using an isolate

**Comment by willsalasare** [comment]
I was trying with an isolate but it can never

I think I found the solution, here you have a problem similar to mine, tomorrow I will try it as mentioned in the downloadBatch method.

**Comment by 781flyingdutchman** [comment]
If you enqueue a lot of tasks at once you need to make sure the app "can breathe" while you do that. In the `downloadBatch` method you can see how you can do that by adding a `Future.delay` after every couple of enqueues.

**Comment by willsalasare** [comment]
That was the problem, only it increases to 500ms, 3ms is not enough

**Comment by 781flyingdutchman** [comment]
Glad it worked. The example has the delay set at 50ms, not 3ms, every 3rd enqueues, and based on my testing that is enough. 50ms gives your app 3 frames time every 3rd frame to do other stuff.
