### ISSUE TITLE
Download task is canceling / Failing over slow connection

### ISSUE THREAD

**Issue by Rohan487** [781flyingdutchman/background_downloader#129]
My app has some users who are in remote areas where the internet connection is not that fast even achieving 1MB/ps is very hard in remote areas. I received complaints of file download failure from users with slow internet connection

I have a decent internet connection with 50Mb/s. So I used [Nethrottle Android App](https://play.google.com/store/apps/details?id=com.network.speedbooster) to limit my internet speed, I connected with a 2g profile, and when I started downloading the file, the Background downloader canceled the task and started retrying until retries are 0 after that it failed, it even not started the task 

![image](https://github.com/781flyingdutchman/background_downloader/assets/72985121/2a3b86dc-17ae-46ba-ad4d-39d33af71754)

I have already set the request timeout to 30 seconds using androidConfig

**Expected behavior**
Whether the internet speed is below 500kb/s or as high as 50MB/s, the download should start and keep running until there is no interruption on the network.

**Comment by 781flyingdutchman** [comment]
Thanks, can you please share logs?! I can't do much without those.

**Comment by 781flyingdutchman** [comment]
Hi, I also think you should configure the use of the cache dir, by using configuration `(Config.useCacheDir, Config.never)`. This forces the use of the documents directory for temporary files, and I've had several reports indicating that this resolves premature cancellation of the task by the Android OS. Also, if - as a result of the slow network - the task runs too long (longer than 9 mins) you may want to force tasks to run in the foreground using `(Config.runInForeground, true)`. Please try these, and upgrade to the latest version. If you still have issues, please share logs.

**Comment by Rohan487** [comment]
Hey, I was working again on this issue, I have some logs related to unexpected end-of-stream. I am not using CacheDir and runInForground is enabled. This issue is with low speed internet connection
![image](https://github.com/781flyingdutchman/background_downloader/assets/72985121/7ad750c2-2124-47d8-abc2-6c25c50c874f)

**Comment by Rohan487** [comment]
Hey, I was working again on this issue, I have some logs related to unexpected end-of-stream. I am not using CacheDir and runInForground is enabled. This issue is with a low-speed internet connection

![Screenshot 2023-09-13 160224](https://github.com/781flyingdutchman/background_downloader/assets/72985121/7ac5d8f0-3496-49aa-b4b3-1ac767e88663)

**Comment by 781flyingdutchman** [comment]
Ok, that's a server side problem (the server closes the connection). Per [this](https://stackoverflow.com/questions/45838774/java-io-ioexception-unexpected-end-of-stream-on-connection-in-android/52622402#52622402) try adding header `{'Connection': 'close'}` to your Download task.

As this is not a client side (plugin) issue I'm going to close this now, but please report your findings here so others can benefit from it
