### ISSUE TITLE
how to remove the sqlite related codes and package dependencies to reduce app size ?

### ISSUE THREAD

**Issue by Hilbert2048** [781flyingdutchman/background_downloader#131]

**Comment by 781flyingdutchman** [comment]
Thanks for reaching out. I want to look into this - I was under the impression that if you don't use the `SqlitePersistentStorage` (which is the default) it would be tree shaken out, but I am not sure that's the case. At the moment therefore the only option is, I think, to fork and remove the `pubspec.yaml` entry for sqflite and the files that depend on it.

**Comment by Hilbert2048** [comment]
it is a little bit heavy for me, e.g the sqflite package depends on FMDB on iOS platform,  I will try to fork and handle this issue by myself.

**Comment by 781flyingdutchman** [comment]
Yes, as I said I was under the impression this would all get tree-shaken but I now understand plugins are not "included" in that process. I may take out the sqlite references and classes as they are not used by default, but that's a breaking change so I'm collecting a few other possible changes before going there.

**Comment by 781flyingdutchman** [comment]
Hi @Hilbert2048, see #173, you can now use the `V7-lite` branch of the repo to use a version of the background_downloader that does not include `sqflite`.
