### ISSUE TITLE
Query MIME type of downloaded file

### ISSUE THREAD

**Issue by ryanheise** [781flyingdutchman/background_downloader#137]
**Is your feature request related to a problem? Please describe.**

The way to know the MIME type of an arbitrary download is to read the Content-type header of the download response, which is currently not available. So although we can now pass a MIME type into `moveToSharedStorage` we do not know what MIME type to pass in for an arbitrary download. If an app needs to know the MIME type in order to open and render the file itself, that also presents a problem.

**Describe the solution you'd like**

Read the MIME type on the native side when receiving the download response, and pass it to the Dart side.

**Describe alternatives you've considered**

The app could make a preliminary HEAD request just to get the MIME type, and then call background_downloader to make second request.

**Additional context**

This is motivated by downloading audio files. On iOS, a local audio file cannot be played unless is has the correct filename extension The source URL won't necessarily have any extension at all, but the Content-type header should at least be correct. By making the MIME type available in Dart, the app will be able to choose a valid filename extension for that MIME type when moving the file to its final location.

**Comment by 781flyingdutchman** [comment]
Hi, thanks for raising this. You can do this relatively easily today:
```
final task = DownloadTask(url: 'https://yourfile.com'); // your task
final response = await FileDownloader().request(task.copyWith(httpRequestMethod: 'HEAD')); // head request
final contentType = response.headers['Content-Type']; // or any other header field you're interested in - may be null
final downloadResult = await FileDownloader().download(task); // the actual download
```
The `response` is the HTTP response for the 'HEAD' request, and from its `headers` field you can get the content type.

I haven't tried the above code but am pretty sure this should work, and as you can see it's minimal extra work, and given it's not a very common requirement I prefer not adding it to every download task.

Hope this helps - closing this for now.

**Comment by ryanheise** [comment]
I didn't mean that, of course I can already do a separate HEAD request as a workaround, but what this feature request is for is so that I don't have to make a separate request for it, because the download itself includes the MIME type in the response, it is just not being captured and included in the result that is passed to Dart.

**Comment by 781flyingdutchman** [comment]
Yes, we could add it to the TaskStatusUpdate when the download completes - I'll look into that but for now you'll have to use the workaround.

**Comment by Aulig** [comment]
I'd be interested in that too. Instead of making another request, I'm getting the headers from the request that determines the filename (DownloadTask.withSuggestedFilename):

```dart
taskWithFilenameBuilder: (DownloadTask downloadTask, Map<String, String> headers, bool unique) async {
  if (headers.containsKey("content-type")) {
    mimeType = headers["content-type"];
    log("Content-Type header found: $mimeType");
  }

  // fall back to the default implementation of taskWithFilenameBuilder
  return taskWithSuggestedFilename(downloadTask, headers, unique);
}
```
