### ISSUE TITLE
Pause button on notification.

### ISSUE THREAD

**Issue by itsSagarBro** [781flyingdutchman/background_downloader#139]
Notification only have cancel button, Is there any way to add pause button in it?

**Comment by itsSagarBro** [comment]
@781flyingdutchman

**Comment by itsSagarBro** [comment]
Added pause task notification in configureNotificationForTask solved my problem.

**Comment by 781flyingdutchman** [comment]
It should have a pause button if you set the task's `allowPause` to `true`
