### ISSUE TITLE
[help wanted] Throwing Error on cancel.

### ISSUE THREAD

**Issue by itsSagarBro** [781flyingdutchman/background_downloader#140]
Whenever I cancel the task it throws an error that is cached by Firebase Crashlytics. How can I catch this??

![image](https://github.com/781flyingdutchman/background_downloader/assets/64249963/08d17dae-0082-4284-bb6d-ffa35be72f4a)

@781flyingdutchman

**Comment by 781flyingdutchman** [comment]
Hi, that error is thrown by the wrapper around the task (that is part of Android's `WorkManager`). I don't know how to prevent that from logging, so I'll keep this issue open in case anyone else has some insight
