### ISSUE TITLE
Android Workmanager and iOS BGTaskScheduler

### ISSUE THREAD

**Issue by absar** [781flyingdutchman/background_downloader#141]
First of all thank you for this plugin, it is really well put together and thorough. My feature request is not related to uploads or downloads rather a full-fledged background workmanager/task scheduler, I've checked out a few other plugins for this purpose, but none of them seem to keep up with the latest Android and iOS updates. They still rely on older, deprecated APIs and don't support features introduced in the last four years, so I wanted to bring to your attention the significant need for a plugin that pays attention to details, similar to what you've achieved with the downloader, you have extensive experience developing downloader which appears to be using similar background native APIs under the hood. If such a plugin is developed, its combination with downloader will cover most of the background use cases, which will benefit the whole Flutter community.

**Describe the solution you'd like**
I would like the plugin to support common features from Android Workmanager and iOS BGTaskScheduler like:

- One time task
- Recurring tasks like iOS [BGAppRefreshTask](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask)
- Long running tasks like iOS [BGProcessingTask](https://developer.apple.com/documentation/backgroundtasks/bgprocessingtask), [Android long running tasks](https://developer.android.com/guide/background/persistent/how-to/long-running)

**Describe alternatives you've considered**
[Workmanager](https://github.com/fluttercommunity/flutter_workmanager), [flutter_background_service](https://github.com/ekasetiawans/flutter_background_service)

P.S. Sorry to create it as an issue, the discussions tab is not enabled in this repo

**Comment by 781flyingdutchman** [comment]
Hi, thanks for the kind words! Taking a quick look at the WorkManager package, it does seem to do what you're asking for (and has a lot of 👍), leveraging the WorkManager API on Android and BgAppRefreshTask on iOS. 

Can you elaborate a bit on what that package is _not_ doing that you'd want to see in a new package? What issues do you experience with that package?

I'm asking because while I welcome a challenge 😊 there were a lot of reasons to develop background_downloader despite flutter_downloader already existing (reliability, fundamental architecture issues, API design etc). Without such compelling reasons it's hard to justify building an alternative to a popular package, and the energy may be better aimed at improving the existing one (as I tried with flutter_downloader).

**Comment by absar** [comment]
Hi, thank you for the quick response

> it does seem to do what you're asking for (and has a lot of 👍), leveraging the WorkManager API on Android and BgAppRefreshTask on iOS

The Android part is more or less ok but it does not support long running tasks like the native workmanager does, I raised it as a feature request in 2020 but there is no work on that, see issue 236
Regarding BgAppRefreshTask on iOS, unfortunately the documentation is misleading, it does not support BgAppRefreshTask rather its using background fetch which is deprecated in iOS 13, check these issues 295, 450, they have by mistake implemented BGProcessingTask and calling it BgAppRefreshTask. Secondly it does not support one off immediate tasks, rather BGProcessingTask which only runs when device is charging, in practice it might be just once a day or less.

> Can you elaborate a bit on what that package is not doing that you'd want to see in a new package? What issues do you experience with that package?

Apart from the unsupported Android long running processes, iOS BgAppRefreshTask and one off tasks, the plugin is becoming an abandon-ware specially on iOS side, since the original author has left in early 2020 there is not much progress
![image](https://github.com/781flyingdutchman/background_downloader/assets/1186833/0ce8ded7-3a33-4ce3-b168-bf34e80d48cc)

The funny thing is Flutter refers to this plugin in its docs but its not given the love it needs, recently during a live call on Youtube I tried to get the attention of flutter community towards this plugin but response was not what I expected, they were mentioning there are other plugins out there and that iOS and Android does not want users to run background tasks, which is not the truth, now both Android and iOS is giving options to run even ML processes using long running tasks.

> the energy may be better aimed at improving the existing one

I am also trying for this and running my own forked branches of workmanager but my lack of native development experience and busy schedule it's lagging behind, while researching this I came across your plugin and was impressed hence the reason for this discussion, i think there is a need for a well designed and easy to maintain plugin, by well designed i mean on both dart and native side.
Anyways have a nice weekend.

**Comment by absar** [comment]
Coincidently I start seeing some activity on workmanager since yesterday at least on Android side :)

**Comment by 781flyingdutchman** [comment]
Thanks for that extra info. I've created a discussion tab and 'moved' this issue there (by copying it - didn't know how else) as I want to keep this idea open but also have a few other things I'm working on right now. I'm closing this issue so the issue list stays clean. Thanks again for raising the idea!
