### ISSUE TITLE
Upload Task does not trigger Progress Callback when Enqueued

### ISSUE THREAD

**Issue by passsionforprogramming** [781flyingdutchman/background_downloader#143]
**Describe the bug**
The `taskProgressCallback` in the `FileDownloader().registerCallbacks` is not getting called even when the updates on the update task is set to `Updates.statusAndProgress`
**Version**
7.9.4
**To Reproduce**
1. Create a register callbacks in the initState of the main method of the applications. And register callbacks for the `taskStatusCallback` and `taskProgressCallback`. Place a print statement in the callback for `taskProgressCallback` to see if it gets called.
2. Create a upload task and set the updates to Updates.statusAndProgress
3. Upload a file using the enqueue method to enqueue the task.
4. Notice that the taskProgressCallback never gets called

**Expected behavior**
The taskProgressCallback should be called to give the progress of the upload when Updates.statusAndProgress is set on the upload task.

**Logs**
If possible, include logs that capture the issue:
```
logs
```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
  final task = UploadTask(
          url: session,
          updates: Updates.statusAndProgress,
          filename: fileForUpload,
          mimeType: contentType,
          post: "binary",
          baseDirectory: BaseDirectory.applicationDocuments,
          httpRequestMethod: "PUT",
          headers: {
            "Authorization":
                "Bearer ${httpClient.credentials.accessToken.data}",
            "Content-Length": "${totalBytes.length}",
            "Content-Type": contentType,
            // "Content-Range": "bytes 0-262143/${totalBytes.length}"
          });

 await FileDownloader().enqueue(task);
```

```
static void registerCallbacks() {
    FileDownloader().registerCallbacks(taskStatusCallback: (status) {
      switch (status.status) {
        case TaskStatus.complete:
          {
            if (status.responseBody != null) {
              handleUploadSuccess(status.responseBody!, status.task);
            }
            break;
          }
        case TaskStatus.failed:
          {
            // resume upload
            debugPrint("Exception status is ${status.exception}");
            break;
          }
        default:
          {
            debugPrint(
                "Status type here ${status.status} Response body ${status.responseBody}");
            debugPrint("Exception in default ${status.exception}");
          }
      }
    }, taskProgressCallback: (progress) {
      debugPrint("progress received ${progress.progress}");
      CurrentUploadProgress().setupSubscriptionV2(
          progress: progress.progress, task: progress.task);
    });
  }
```

**Additional context**

**Comment by 781flyingdutchman** [comment]
Hi, sorry you're having this problem. What platform is this problem happening for you (e.g. Android, iOS, desktop), and does it also happen on other platforms?

I can't replicate this issue - is the upload itself successful? Can you try running the test named "enqueue binary file" in the `downloader_integration_test.dart` file (which completes successfully for me, showing progress updates along the way)? Can you post the full logs of the upload (on Android from LogCat, and on iOS from Console)?
