### ISSUE TITLE
Basically it doesn't work

### ISSUE THREAD

**Issue by rekire** [781flyingdutchman/background_downloader#145]
**Describe the bug**
I got recently the bug report that in my app the download are not working anymore. To be honest I am not sure if it ever worked before, but that is not the topic here.

The filename is numeric only which seems to be not openable on iOS.

**To Reproduce**
The download links look like https://customer.example.com/downloads/123456 when the user clicks on it there is a redirect to a temporal url like https://downloads.example.com/6241b350-b233-4824-8c06-f7f1efcb3d50. This url provides for each (GET/HEAD) request a `Content-Disposition` header like this:
```Content-Disposition: inline; filename="test_abc.jpg"; filename*=UTF-8''test_abc.jpg```

My code looks like that:
```dart
if (request.url.startsWith('https://customer.example.com/downloads/') ||
    request.url.startsWith('https://downloads.example.com/') {
  final backgroundDownloadTask = DownloadTask(
    url: request.url,
    baseDirectory: BaseDirectory.applicationDocuments,
    updates: Updates.statusAndProgress,
    allowPause: true,
  );
  await FileDownloader().enqueue(backgroundDownloadTask);
  await FileDownloader().moveToSharedStorage(task as DownloadTask, SharedStorage.downloads);
  await FileDownloader().openFile(task: backgroundDownloadTask);
}
```
I already removed the first condition so that the redirect does not matter, however I see no downloads on that iphone and nothings open. Not by code above or by tapping on the notifications open action.

**Expected behavior**
I expect in the Files app the download and that it opens automatically and by pressing the notification with the filename from the `Content-Disposition` header.

**Logs**
If possible, include logs that capture the issue:
```
[Downloader] Starting task with id 450949381
[Downloader] timeoutIntervalForResource = 14400 seconds
[Downloader] timeoutIntervalForRequest = 60 seconds
[Downloader] Not using proxy for any task
[Downloader] File does not exist: /var/mobile/Containers/Data/Application/46951B18-BECB-4EC3-AEB9-835278C3ED70/Documents/872645225
[Process] 0x102499618 - [pageProxyID=6, webPageID=7, PID=2047] WebPageProxy::didFailProvisionalLoadForFrame: frameID=3, domain=WebKitErrorDomain, code=102, isMainFrame=1
[Downloader] Finished task with id 450949381
flutter: Tapped notification NotificationType.complete for taskId 450949381
[Downloader] Moved from file:///var/mobile/Containers/Data/Application/46951B18-BECB-4EC3-AEB9-835278C3ED70/Documents/872645225 to /var/mobile/Containers/Data/Application/46951B18-BECB-4EC3-AEB9-835278C3ED70/Documents/Downloads/872645225
```

**Code**
If possible, paste in the code snippet where you interact with the package:
(see above)

**Additional context**
The `Content-Disposition` support seems to be done via #37

**Comment by 781flyingdutchman** [comment]
Hi, it appears you call `moveToSharedStorage` immediately after calling `enqueue`, without waiting for the download to complete. At that moment, the task has only been enqueued so the file you want to download doesn't exist yet. Change `enqueue` to `download` and only move and open the file if the result of that call indicates that the task was downloaded successfully.

**Comment by rekire** [comment]
The behavior is without that line still the same.

Here is my "new" log:

> [Downloader] Starting task with id 1050052327
> [Downloader] timeoutIntervalForResource = 14400 seconds
> [Downloader] timeoutIntervalForRequest = 60 seconds
> [Downloader] Not using proxy for any task
> [Process] 0x103a92e18 - [pageProxyID=6, webPageID=7, PID=3049] WebPageProxy::didFailProvisionalLoadForFrame: frameID=3, domain=WebKitErrorDomain, code=102, isMainFrame=1
> [Downloader] Finished task with id 1050052327
> flutter: Tapped notification NotificationType.complete for taskId 1050052327

**Comment by 781flyingdutchman** [comment]
It's a little unclear what exactly is not working as expected. Part of documentation on an iPhone. You cannot actually move a file to the downloads folder so that it shows up in the iPhone files app. I don't know how to get permission for that, and as far as I know that permission is only granted to apps like Safari. If you download to the documents folder, the default, and add the required permissions to make the file available externally then that should work. Please read the documentation on the limitations on iOS

**Comment by rekire** [comment]
I found now the download on the iPhone, I'm a bit shocked how complicated it is to find the downloads, but I see them now. The next missing part was indeed the changes in the `info.plist`, I missed that part. My fault. However the filename detection doesn't work. Here is an actual URL I'm using (not sure how long it is valid) you might want to check it yourself:
https://external.centralstationcrm.net/external/attachments/Z3BGMEgyUTJvNS9ncVY1a2dSUWdFS2JYQ3c0VzZoL085bGVUcDd6TXdkZGpqOG9MZ29MODRUVkFNSWFBc0l3YzQzRkdHVkdnY21VMTNabEp1RlNoRy9GWTlJYjBxWUtzWjJjQ3ZyY1lvU05sR2hKWWhwaUR3QlhvQlM3YU02MnlUQVR2OGZQc0tqUXltM3JLN3cwZWdPdlBVRUY2ZW8zazZhUzgxUmJtYzY5dDJSWkQ3V09Rbys1dUd0WnEvYjVhLS05ZzYzUzF3S2pGV0tnZVl6QVZhY2J3PT0=--a8eaefd919e3e924611d9c72157875dcea01c71f

The filename on the device is currently some random number without an extension.

**Comment by 781flyingdutchman** [comment]
In [this section](https://pub.dev/packages/background_downloader#specifying-the-location-of-the-file-to-download-or-upload) it shows you how to use a filename suggested by the server. Leaving filename empty (as you've done in your example code above) will indeed generate a random filename.

**Comment by rekire** [comment]
I cannot use the filename parameter since I do not know the filename. I thought with #37 you would read the actual filename with a head request. Does that mean that I need to do that request myself?

**Comment by 781flyingdutchman** [comment]
Did you read the section I referred you to? It explains how to do this, offering the following example:

```
final task = await DownloadTask(url: 'https://google.com')
        .withSuggestedFilename(unique: true);
```

Every issue you've raised in this "Basically it does not work" issue has been due to you not reading or following the documentation. You know how much work it is to maintain a package, so please do your part and read the documentation before throwing out issues that are not issues, that require me to point you to the docs again and again.

**Comment by rekire** [comment]
I can absolutly understand you. I'm sorry that I took a not so professional issue title, but I was just fustrated in that moment. Just to make it clear I am very thankful for your work, expecially you exceptional quick responses.

The point is, I read the docs multiple times (of cause not everything otherwise I would not have made so stupid errors). I have trouble to get the right points, those fairly annoing pointers, are that what I didn't see.

I clicked on your link and scanned the text I saw the point with `.withSuggestedFilename(unique: true)`, but I missinterpreted it. I looked at the url and the example. I'm pretty sure that `https://google.com` has not those `Content-Disposition` headers so I saw the example file names "file.txt" and "file (1).txt" and I thought that this would just avoid naming colissions. To be honest I would expact that as default behavior instead of those random numbers, but that is just my opinion.

Anyway I think I'm now on the right track to fix the issue in a couple of minutes. 

Thank you!

**Comment by 781flyingdutchman** [comment]
No worries, and yes in hindsight I also wish I had defaulted to server-provided filename if you leave it out of the task. I am very careful not to create breaking changes though, and this would be one, which is why I went with the suggestedFilename approach. Thanks!

**Comment by rekire** [comment]
I have right now a very limited internet connection. I'll check it next week.

13.10.2023 19:04:44 781flyingdutchman ***@***.***>:
