### ISSUE TITLE
Download progress as notification

### ISSUE THREAD

**Issue by rekire** [781flyingdutchman/background_downloader#15]
I still want to have the download progress on Android and iOS. On Windows you could also use [the taskbar](https://github.com/alexmercerind/windows_taskbar).

That should be optional of cause but for my usecase I would need it. I know that here kicks in localization problems, but I guess that would be not the frist plugin which runs into that issue.

**Comment by 781flyingdutchman** [comment]
Hi, similar to scoped storage, this type of progress is uniquely Android: it is not possible/allowed on iOS and frowned upon in desktop apps. Similar to my response on scoped storage I think the best way to implement is a "configureAndroidNotification" call that you make before starting your download. It would take a task or a group and set notification details like what text to show. On the native android side you store that info, and when the task is enqueued we check if such info exists. If it does, the progress notification is built and updated.
Like with scoped storage, happy for you to work on a pull request, but wait for the next version as it has changed the Kotlin side substantially.

**Comment by rekire** [comment]
Download progress is not unique for Android since as I said I would like to see the progress in the taskbar like for copy operations (if you are familiar with Windows). However to be honest I have no idea if progress is shown on Apple platforms (but I mean I have seen very basic progress bars in the dock [random Google result](https://github.com/sindresorhus/DockProgress))

Regarding the problems that will appear with localization I've a basic concept how to generate the native resources for e.g. Android. However I'm not sure if that is required or if it is easier to pass those data via method channel. However customization would be likely critical for most users.

<details><summary>Basic idea to generate localized native resources</summary>

If you put this into your repo `bin/foo.dart`:

```dart
import 'dart:io';
import 'package:yaml/yaml.dart';

void main() async {
  final pubspec = await File('pubspec.yaml').readAsString();
  final config = loadYaml(pubspec)['translation-converter'];
  config['input'].forEach((e)=>Directory(e).listSync().forEach((f)=>parseFile(f as File, config)));
}

parseFile(File f, config) async {
  final filename = f.uri.pathSegments.last;
  final json = await f.readAsString();
  print('Parsing $filename');
  if(filename == '${config['default']}.json') {
    print('Output: ${config['output']['android']}/res/values/easy_localization.xml');
  } else if(filename.length == 7) { // xx.json
    print('Output: ${config['output']['android']}/res/values-${filename.substring(0, 2).toLowerCase()}/easy_localization.xml');
  } else if(filename.length == 10) { // xx-yy.json
    print('Output: ${config['output']['android']}/res/values-${filename.substring(0, 2).toLowerCase()}-r${filename.substring(3, 5).toUpperCase()}/easy_localization.xml');
  }
  print(json.length);
}
```

And put this into your `pubspec.yaml`:
```yaml
translation-converter:
  input:
    - assets/translations/
  default: en-US
  output:
    android: build/foo
```

Then you could run it by using:
```bash
flutter pub run your_project:foo
```
</details>

Anyway if that is required to have the localization in the native platform or not I wrote that code already for a native Android App therefore I can reuse that code. What is currently missing and would be required to write from scratch is: To check if the permission is given to show notifications and handle the request flow including a guidance why the permission is requested. There should be also a way to recover from a rejected permission, both should be applied on iOS too.

I could image a flow like this:

```dart
enum NotificationPermission {
  NotGranted,
  Rejected,
  Granted,
}

final downloadGroup = getCurrentDownloads();
switch (downloadGroup.notificationPermission) {
  case NotificationPermission.Granted:
    downloadGroup.showNotification(mayBe: Some.options);
    break;
  case NotificationPermission.Rejected:
    // create a dialog with option to open the system settings
    break;
  case NotificationPermission.NotGranted:
    // Inform the user about the progress and ask for permission
    break;
}
```

**Comment by 781flyingdutchman** [comment]
Great you already have this for Android. It's really not allowed/possible on iOS, and on desktop platforms I am not aware of any other than the one on Windows you mentioned. If someone wants to use that, it is much easier for them to simply use that plugin and wire it up via the progressUpdate they're getting from the downloader. I really don't want to include that in the plugin.

For Android, I understand this is more common and requires native code. Like with ScopedStorage, I can create a starting point for how I think it can be done, where you would have to plug in the code pieces that you already have. Let me know if that's an approach that works for you, before I start that work.

**Comment by rekire** [comment]
From the perspective of the scope I was also thinking about to put it into a second plugin, I just wanted to discuss it with someone else.

I'm just surprised how does a user open an attachment from the browser or email client on iOS when the download takes let's say more then 10 seconds and navigates somewhere else e.g. getting a call or so. I cannot image that you can in that case absolutely no feedback that your download is done.

Anyway I would suggest:

Could you be so kind to copy and paste here an example how to observe here a download so that I can forward the information to the new plugin.

Please let this issue here open until I created a new project which can do what I have in mind.

**Comment by 781flyingdutchman** [comment]
Sure, something like this:
```
final progressBar = ProgressBar(); // from your other plugin
final subscription = FileDownloader().updates.listen((update) {
      if (update is TaskProgressUpdate) {
        progressBar.updateProgress(update.progress); // assuming it takes an update between 0 and 1
    });
    // define the task
    final task = DownloadTask(
        url: 'https://google.com',
        filename: 'google.html',
        updates:
            Updates.statusAndProgress); // needed to also get progress updates
    // enqueue the download
    final successFullyEnqueued = await FileDownloader().enqueue(task);
    // updates will be sent to your subscription listener

```

If you have multiple downloads in parallel you need to check which task the update is for (check `update.task`) and perhaps use multiple progress bars.  This will work in the foreground also on Android if you can find a notification plugin. It won't work in the background, which is why you need native Android code as you suggested. You can use the same technique to detect the end of a download and send a notifcation then. Note that on desktop there is no such thing as background, which is why wiring it up to the Windows taskbar plugin you mentioned should be trivial, and will work. Good luck!

**Comment by rekire** [comment]
Thank you for that code sample. But that remembers me to one thing: I would need be called from the background worker when the dart code it in the background I would likely don't get any updates anymore.

So maybe a code change on the Kotlin side would be required.

I'll check if I get updates from the flutter side when the app is in the background, however I am not sure if I find the time for that today.

**Comment by 781flyingdutchman** [comment]
The code example was meant for a plugin like the Windows taskbar one you mentioned. That will work. For Android you need to implement the entire notification logic in Kotlin, you can't communicate effectively with the Dart side when the task is in the background.

**Comment by rekire** [comment]
Right that was what I had in mind earlier today... In that case a listener interface might help. I'll come back when I have a concrete idea

**Comment by rekire** [comment]
What do you think about this interface to observe the download progress?

```kotlin
class NativeDownloadObserver {
    private val listeners = mutableListOf<DownloadProgress>()
    
    fun addListener(listener: DownloadProgress) {
        listeners += listener
    }
    
    fun removeListener(listener: DownloadProgress) {
        listeners -= listener
    }
    
    fun notifyProgressChanged(task: Task, progress: Int) {
        for(listener in listeners.asReversed()) {
            listener.onProgressChange(task, progress)
        }
    }

    fun notifyStatusChanged(task: Task, status: TaskStatus) {
        for(listener in listeners.asReversed()) {
            listener.onStatusChanged(task, status)
        }
    }
}

interface DownloadProgress {
    fun onProgressChange(task: Task, progress: Int);
    fun onStatusChanged(task: Task, status: TaskStatus)
}
```

**Comment by 781flyingdutchman** [comment]
Notifications is now implemented for Android on the notifications  branch, though not yet working for iOS so don't use it if you target that platform. Also, expect changes before this gets published on the main branch.
