### ISSUE TITLE
Allow ParallelDownload if user passes fileSize

### ISSUE THREAD

**Issue by delfme** [781flyingdutchman/background_downloader#156]
I’m testing the plugin, which I like very much. On android Im hit by performance issue.

I have coded a `chunkedDownloader` and Im using it for now (It provides a 40% speed improvement). Would love to test ParallelDownload, but our files are saved on google drive and it doesnt return content lenght.

Could you improve the feature so that it can be used anyway if `fileSize` is passed inside the constructor? This is our very use case (we already know the fileSize of the files that we download).

**Comment by 781flyingdutchman** [comment]
Interesting - are you sure Drive doesn't provide content length? I seem to remember that you get a progress indicator if you download a file from Drive to your local disk (which would suggest there is content-length available).  Let me think about if this can be added - unfortunately I won't get to this for about 2 weeks.

**Comment by iosephmagno** [comment]
Yes, tested also with your plugin and ParallelDownloads dont work with gdrive urls.
Will follow this issue and test again if you get to add the feature.
In my class I do sth like that:
```
fileSize = fileSize ?? int.tryParse(r.headers['content-length'] ?? '-1');
```
I get fileSize from constructor and if not available I get it try from headers.
Then I split download in chunks.

**Comment by iosephmagno** [comment]
Done, used my other account

**Comment by 781flyingdutchman** [comment]
Thanks, closing this issue in favor of the discussion in #157 which should lead to an implementation that satisfies this issue
