### ISSUE TITLE
Not Getting latest version in my project. flutter_test depends on collection 1.16.0.

### ISSUE THREAD

**Issue by dishant-livebird** [781flyingdutchman/background_downloader#16]
Because every version of flutter_test from sdk depends on collection 1.16.0 and background_downloader >=5.0.0 depends on collection ^1.17.0, flutter_test from sdk is incompatible with background_downloader >=5.0.0.
So, because vectortiles_to_rastertiles depends on both background_downloader ^5.2.0 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because vectortiles_to_rastertiles depends on both background_downloader ^5.2.0 and flutter_test from sdk, version solving failed.)
exit code 1

How i change or increase  flutter_test  dependency.

**Comment by 781flyingdutchman** [comment]
First step is to upgrade your Flutter SDK by doing 'flutter upgrade'. If that doesn't work you can add a dependency override in your app's pubspec.yaml like this:
```
dependency_overrides:
  collection: ^1.16.0
```
