### ISSUE TITLE
UploadTask: how to pass data?

### ISSUE THREAD

**Issue by delfme** [781flyingdutchman/background_downloader#160]
Hello,
This should not be a bug but I'd need a clarification on how to pass `data`.

To upload a file to google drive via Dio(), code would be:
```
Response metaResponse = await dio.post(
      'https://www.googleapis.com/upload/drive/v3/files',
      queryParameters: {
        'uploadType': 'resumable',
      },
      options: Options(
          headers: {
            'Authorization': token,  
            'Content-Type' : 'application/json; charset=utf-8',
            'Content-Length': file.lengthSync(),
          }),
      data: {
        'parents': [folderId ?? 'appDataFolder'],
        'properties': metaData.properties,
        'appProperties': metaData.appProperties,
        'description': metaData.description,
        'name': metaData.name,
        'mimeType': mime(file.path),
      },
    );
```

How that would convert for `UploadTask` ? Coz `data` is an Object and fields like `metaData.properties` are itself Map<String, dynamic>.

With googleapis gdrive it would be:
```
GoogleSignInAccount? googleSignInAccount = await googleSignIn();
var client = GoogleHttpClient(await googleSignInAccount!.authHeaders);
var drive = gApi.DriveApi(client);
    gApi.File fileToUpload = gApi.File();
    fileToUpload.parents = [chatroomId ?? 'appDataFolder'];
    fileToUpload.name = metaData.name;
    var metaResponse = await drive.files.create(
      fileToUpload,
      uploadMedia: gApi.Media(file.openRead(), file.lengthSync()),
    );
    debugPrint('$_debugPrefix gdrive response uploaded FileId ${metaResponse.id}');
  return metaResponse.id!; // Response from server, we get fileId from it
```

**Comment by delfme** [comment]
Noticed that we can get rid of  `fileToUpload.properties` , `fileToUpload.description` and `fileToUpload.appProperties`.

However, it is not clear how to receive the response from api `metaResponse` and I'm not very sure about what to pass to UploadTask `fileField`

**Comment by 781flyingdutchman** [comment]
Hi, I'm not familiar with the Drive API, but from [this](https://developers.google.com/drive/api/guides/manage-uploads) I gather that it's a regular binary or multipart upload (note that 'resumable' is not supported in the downloader). So your task would look something like this:
```
final task = UploadTask(
      url: 'https://www.googleapis.com/upload/drive/v3/files',
      urlQueryParameters: {
        'uploadType': 'multipart',
      },
      headers: {
            'Authorization': token,  
          },
      filename: 'your.file.txt',  // add baseDirectory and directory fields if needed to specify file location
      mimeType: 'image/jpeg', // leave out for auto detect based on file extension
      fields: { // these are typically used for metadata and depend on what the server expects, so I think this may work
        'description': metaData.description,
        'name': metaData.name
      },
      fileField: 'only_set_if_non_standard', // default is 'file' and works for most servers
      );
```
In a multiPart upload the fileField is the name of the field that contains the file name. By default it's 'file' and I suspect this will work for Drive, so just omit it.  Content type and length headers will be set based on the file so don't add those.

Note that the drive API also supports regular binary uploads (and so does the donwloader). Set `urlQueryParamers` to `{'uploadType': 'media'}` (for the Drive API) and set the `post` field to the string 'binary'. In this case you cannot include metadata with the upload, so no need for `fields` and `fileField` in this case.

**Comment by delfme** [comment]
Let me better explain the case and clean code.

With gdrive api is as simple as that: you pass `Media` got via `file.openRead()` or  `Stream<List<int>>` if you need download onProgress. For simplicity I paste below the code without onProgress. When you upload a file gdrive return a response, which contains `fileId` (which can be used by client later on to access that file directly).

**OPTION 1:**
```
// Upload via api Google
GoogleSignInAccount? googleSignInAccount = await googleSignIn();
var client = GoogleHttpClient(await googleSignInAccount!.authHeaders);
var drive = gApi.DriveApi(client);
    gApi.File fileToUpload = gApi.File();
    fileToUpload.parents = [chatroomId ?? 'appDataFolder'];
    fileToUpload.name = metaData.name;
    File file = await drive.files.create(
      fileToUpload,
      uploadMedia: gApi.Media(file.openRead(), file.lengthSync()),
    );
debugPrint('gdrive response uploaded FileId ${file.id}');
return file.it!; // Return gdrive fileId
```
Note that gdrive return a gdrive File, which is a custom class where they set their own properties. The most important one is `id` (the id of the file which let you then access it back again directly).


**OPTION 2:**
With a generic http client (Dio) it is:
```
    // Authenticate and get `response` from gfrive
    Dio dio = Dio();
    Response response = await dio.post(
      'https://www.googleapis.com/upload/drive/v3/files',
      queryParameters: {
        'uploadType': 'media',
      },
      options: Options(
          headers: {
            'Authorization': token,
            'Content-Type' : 'application/json; charset=utf-8',
            'Content-Length': file.lengthSync(),
          }),
      data: {
        'parents': [chatroomId ?? 'appDataFolder'],
        'name': metaData.name,
      },
    );	

    // Get `Location` from response
    String? uploadUrl = response.headers.value('Location');
		
    // Upload File with PUT
    Response uploadResponse = await dio.put(
      uploadUrl!,
      options: Options(headers: {
        'Authorization': token,
        'Content-Length': file.lengthSync()
      }),
      data: file.openRead(),
      onSendProgress: (count, total) => {}),
    );
    debugPrint('gdrive response uploaded FileId ${uploadResponse.data['id']}');
    return uploadResponse.data['id']; // Return gdrive fileId
```
In this case (using rest api), a POST and a PUT are required, the id of the file is inside the response body, `uploadResponse` and can be accessed via `uploadResponse.data['id']`

It is not clear how to use `background_downloader` in this scenario.

**Comment by 781flyingdutchman** [comment]
Hi, the direct approach using the API is not going to work (because you cannot execute the code you show there as a native background task) so you'll have to follow Option 2.

It looks like you need to do a server request to get an uploadUrl, then a 'regular' binary upload of a file via that uploadUrl.  I suggest doing this with the downloader as follows:
1. Create a [server post request](https://github.com/781flyingdutchman/background_downloader#server-requests) using `Request`. You should try either passing the map in `data` in your Dio example above to `post` in the `Request`, or JSONEncode the `data` Map  as a String and pass that as the `post` parameter of the `Request`, and you may have to experiment with setting the content-type - I am not sure which way will work
2. Call `final response = await FileDownloader().request(yourRequest)` and extract the `uploadUrl` from the response header just like you do for Dio (the response is a normal `HttpResponse` object)
3. Create an uploadTask with the `uploadUrl`, set `httpRequestMethod` to 'PUT', add your authorization header (no content length), set the baseDirectory, directory and filename such that they point to the file you want to upload
4. Call `final result = FileDownloader().upload(uploadTask)` (or better yet, use `enqueue`) and check the result.

**Comment by delfme** [comment]
hello @781flyingdutchman can you please tell me what the correct settings of basedir and dir should be for this remote url? We have 3 folders here:
chat/message/71ab3693-5f19-4d0a-8228-acffdbfd94ef1699215079854/example_file.MP4

**Comment by 781flyingdutchman** [comment]
Hi, I imagine there's something before "chat", no? If not, then you'll have to copy the file to one of the supported directories, e.g. the temporary directory, and upload from there.

**Comment by delfme** [comment]
Yes it is app Documents Directory

` baseDirectory: BaseDirectory.applicationDocuments,`

How should I set directory? This one?
`directory: 'chat/message/71ab3693-5f19-4d0a-8228-acffdbfd94ef1699215079854'`

**Comment by 781flyingdutchman** [comment]
You need to copy that file to one of the directories supported, eg the temporary one, then upload

**Comment by delfme** [comment]
Thx, understood the approach.

I did some benchmarks on iphone pro 13, ios 16.
Background_downloader wins hands-down even against Dio native adapter (which honestly performs very similar to standard dart http client).

```
Test 2MB file

AWS Amplify
average: 1,8-2,5 sec 
worst case: 6-7sec and it occurs every 2-3 uploads

Dio
average: 1,8-2,5 sec 
worst case: 6-7sec and it occurs every 2-3 uploads

Background_downloader
average: 700ms-2,5 sec 
Worst case: 3sec and it occurs rarely


Test 10 Mb file

AWS Amplify
average: 6-11 sec 
worst case: 11sec and it occurs every 2-3 uploads

Dio
average: 3-6 sec 
worst case: 11sec and it occurs every 2-3 uploads

Background_downloader
average: 2,8s-3,3 sec 
Worst case: 10sec and it occurs rarely
```

**Comment by william150823** [comment]
dio.post(
            '$uploadBaseUrl/im/upload/file',
            data: formData,);
            
            
            Dio working this way is fine. can upload the file, but for background_downloader doesn't have the place to add 'data'
            
             final task = UploadTask(
        url: '$uploadBaseUrl/im/upload/file',
        fileField: localPath,
        filename: path.basename(localPath),
        updates: Updates.statusAndProgress // request status and progress updates
    );

it always return task status.failed.

**Comment by 781flyingdutchman** [comment]
Please carefully read the documentation: there are many options to add form fields, and which one is right for you depends on your data and server. For example if you read the documentation you'll see that it is highly unlikely that `localPath` is an appropriate argument for the `fileField` parameter.

**Comment by william150823** [comment]
@781flyingdutchman thanks for fast respond. So let said I want to upload image file then the proper way to write is like this?

UploadTask(
        url: '$uploadBaseUrl/im/upload/file',
        fileField: 'image',
        fields: {'files': localPath},
        filename: path.basename(localPath),
        updates: Updates.statusAndProgress // request status and progress updates
    );

**Comment by 781flyingdutchman** [comment]
It depends on your server. Most likely it expects a binary file, in which case you set `post` to `'binary'`. What you write is for a multipart file upload, not binary. And you haven't specified what file to upload properly either. Please read the documentation

**Comment by william150823** [comment]
@781flyingdutchman yes. what I need is multipart upload. Tried all the method and meet the requirement, but the status still fail.

UploadTask(
        url: '$uploadBaseUrl/im/upload/file',
        fields: {'files': localPath},
        filename: path.basename(localPath),
        mimeType: lookupMimeType(localPath),
        updates: Updates.statusAndProgress // request status and progress updates
    );

 UploadTask{taskId: 1829761738, url: https://upload/im/upload/file, filename: user.png, headers: {}, httpRequestMethod: POST, post: null, directory: , baseDirectory: BaseDirectory.applicationDocuments, group: default, updates: Updates.statusAndProgress, requiresWiFi: false, retries: 0, retriesRemaining: 0, allowPause: false, priority: 5, metaData: , displayName: } and fileField file, mimeType image/png and fields {files: C:\Users\William\Documents/b61c31c21c84fe8f768b4c7ba90d1f08/Media/Images/user.png}


flutter: Status: TaskStatus.enqueued
flutter: Status: TaskStatus.running
flutter: Progress: 0.0%
flutter: Progress: -100.0%
flutter: Status: TaskStatus.failed
