### ISSUE TITLE
There should be a way download directly to external memory.

### ISSUE THREAD

**Issue by nahidmk** [781flyingdutchman/background_downloader#162]
There should be a way to directly download content to external memory. I am encountering an issue where I need to check the available space on local storage before downloading. Subsequently, I must check the available space on external storage to move the video. It is crucial to provide the option of specifying a custom path for downloading or relocating the video to any desired location on the device. In essence, if a user possesses an SD card, I would like the video to be downloaded onto the SD card; otherwise, I prefer it to be downloaded to the local storage

**Comment by 781flyingdutchman** [comment]
Hi, this has been asked before, and I understand why it's desirable, but it's not straightforward to fit this into how the downloader (and the DownloadTask) are meant to work.  I've started discussion #163 with some thoughts - please comment on the idea there if you have a point of view (and please understand the constraints outlined there).  I'm closing this issue in favor of continuing the discussion there, hopefully leading to a solution eventually
