### ISSUE TITLE
how to pass path to task in upload task ?

### ISSUE THREAD

**Issue by MostafaTawfik7** [781flyingdutchman/background_downloader#172]
path of image '/Users/mostafatawfik/Library/Developer/CoreSimulator/Devices/39EDCDA2-2876-4C80-8CA4-2416115E35E6/data/Containers/Data/Application/4937BE4C-84D6-4E0B-89FD-1364FB11F82F/tmp/tree-g9bbc18fbe_1280.jpg'

path in ios from path provider for getApplicationDocumentsDirectory() ,getApplicationSupportDirectory(), getTemporaryDirectory()
don't match with path of image in tmp/tree-g9bbc18fbe_1280.jpg
ex : path from getApplicationSupportDirectory() is 
" /Users/mostafatawfik/Library/Developer/CoreSimulator/Devices/39EDCDA2-2876-4C80-8CA4-2416115E35E6/data/Containers/Data/Application/4937BE4C-84D6-4E0B-89FD-1364FB11F82F/Library/Application Support"
how to replace Library/Application Support with tmp/tree-g9bbc18fbe_1280.jpg'
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=3 "(null)") error, Scheduling the task using BGTaskScheduler has failed.
 ```
```
final task = UploadTask(
      url: url,
      filename: fileName,
      directory:  'tmp' ,
      retries: 1,
      post: 'binary',
      httpRequestMethod: 'PUT',
      baseDirectory: BaseDirectory.applicationLibrary,
      headers: {
        Headers.contentTypeHeader: 'image/jpeg',
        Headers.contentLengthHeader: len.toString(),
      },
      updates: Updates.statusAndProgress, 
    );
```

**Comment by 781flyingdutchman** [comment]
Hi, similar to #121 you'll have to copy the file to one of the supported directories and start the upload from there.

**Comment by EmmanyTaskWorld** [comment]
> Hi, similar to #121 you'll have to copy the file to one of the supported directories and start the upload from there.

1. How do we do that. I am also not understanding this part. 

2. Why can't we just specify the filePath then your package can create the directory and start the upload?

**Comment by EmmanyTaskWorld** [comment]
This is what i did

`Future<File?> copyFileToTemporaryDirectory(File sourceFile) async {
    try {
      final tempDir = await getTemporaryDirectory();
      final tempPath = tempDir.path;
      final fileName = sourceFile.path.split('/').last; // Get the file name from the source path

      final tempFile = File('$tempPath/$fileName');
      await sourceFile.copy(tempFile.path);

      return tempFile;
    } catch (e) {
      print('Error copying file to temporary directory: $e');
      return null;
    }
  }`
  
File sourceFile = File('path/to/your/source/file.txt');
File? tempFile = await copyFileToTemporaryDirectory(sourceFile);

if (tempFile != null) {
  print('File copied to temporary directory: ${tempFile.path}');
} else {
  print('Failed to copy the file.');
}

Then upload like this:

final task = UploadTask(
                  url: attachmentBaseURL, // server URL
                  baseDirectory: BaseDirectory.temporary,
                  filename: metaData?.attachments?.first.upload?.fileName ?? '', // this is your file name
                  headers: extraHeaders, // headers if required
                  updates: Updates.statusAndProgress);

              var result = await FileDownloader().enqueue(task);

**Comment by MostafaTawfik7** [comment]
Thanks @EmmanyTaskWorld

**Comment by 781flyingdutchman** [comment]
I would add that if you don't need to keep the original you can probably use `await sourceFile.rename(tempFile.path);` which is much faster as it does not actually copy the file.  `rename` fails if your original file is on a different volume than where you are moving it to (which I believe is more of an Android thing if you use external file storage such as an SD card), so you could add a `try/catch` that first attempts `rename` and if that fails does a copy & delete.  Again, this is if you don't need to keep the original.
