### ISSUE TITLE
Uploading duplicate files when reopen the app after uploading files

### ISSUE THREAD

**Issue by rxvivek** [781flyingdutchman/background_downloader#175]
When i uplaoding my images, during uploading file process, i reopen my app after killing the app. the duplicate files are uploading in android.

**Comment by 781flyingdutchman** [comment]
Hi, can you describe the issue in more detail? Step by step, what are you doing, what is happening and what did you expect to happen? Also, please include the relevant code snippet and the logs. Thanks
