### ISSUE TITLE
The plugin makes run release project crash on startup when minifyEnabled

### ISSUE THREAD

**Issue by fpatron** [781flyingdutchman/background_downloader#177]
Hi,
For your information, I got exactly the same issue as https://github.com/781flyingdutchman/background_downloader/issues/116.
I resolved it by removing the option minifyEnabled in my build.gradle file.
I was unable to start my app after adding the background_downloader plugin.
Hope this helps.

**Comment by 781flyingdutchman** [comment]
Hi, sorry to hear that - I never heard back on #116 so assumed it was not replicated.

To help me debug this, can you let me know which of the following functionality you use:
* download
* upload
* ParallelDownload (using ParallelDownloadTask)
* Pausing/resuming a task
* Notifications

And if possible, can you describe what you're doing when the app crashes - for example "the crash happens when the download finishes" or "when I pause a task"?

In lieu of logs this will help me understand where the issue with minification is. Thanks!

**Comment by 781flyingdutchman** [comment]
In addition, can you perhaps try a new version that I hope/think may fix this? Change your pubspec.yaml to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: minify
```
and try your app in release mode. Let me know if the issue is still there (see earlier comment).

**Comment by fpatron** [comment]
Hi @781flyingdutchman ,

The app crashes at startup as soon as background_download is added to the pubspec. No functionality is used yet. In my init functiob, I retrieve the available cameras, but when the plugin is added, it crashes with the following error:

```
Error:
MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
```

Without it, the init function succeeds without any problems
I searched for a solution and found a workaround by removing the minifyEnabled parameter.

I will try your version later today or tomorrow.

**Comment by fpatron** [comment]
@781flyingdutchman 
I just tested your patch and the problem is still here.

E/flutter (25173): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera_android)
E/flutter (25173): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (25173): <asynchronous suspension>
E/flutter (25173): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:496:35)
E/flutter (25173): <asynchronous suspension>
E/flutter (25173): #2      AndroidCamera.availableCameras (package:camera_android/src/android_camera.dart:74:52)
E/flutter (25173): <asynchronous suspension>
E/flutter (25173): #3      main (package:lafourmi/main.dart:44:17)
E/flutter (25173): <asynchronous suspension>
E/flutter (25173): 

If I just keep this in my init function, I've got this new error.

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

   try {
    FileDownloader().configure(
      globalConfig: [
        (Config.requestTimeout, const Duration(seconds: 100)),
      ],
      androidConfig: [
        (Config.runInForeground, true),
        (Config.runInForegroundIfFileLargerThan, 1),
      ],
    ).then(
      (result) =>
          debugPrint('Background task manager configuration result = $result'),
    );

    await FileDownloader().trackTasks();
  } on Exception catch (e) {
    return Future.error(e);
  }

  runApp(const MyApp());
}
```


```
E/flutter (28942): 
E/flutter (28942): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (28942): 
E/flutter (28942): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method configRequestTimeout on channel com.bbflight.background_downloader)
E/flutter (28942): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (28942): <asynchronous suspension>
E/flutter (28942): #1      NativeDownloader.configureItem (package:background_downloader/src/native_downloader.dart:332:9)
E/flutter (28942): <asynchronous suspension>
E/flutter (28942): #2      AndroidDownloader.configureItem (package:background_downloader/src/native_downloader.dart:387:25)
E/flutter (28942): <asynchronous suspension>
E/flutter (28942): #3      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
E/flutter (28942): <asynchronous suspension>
E/flutter (28942): #4      BaseDownloader.configure (package:background_downloader/src/base_downloader.dart:123:12)
E/flutter (28942): <asynchronous suspension>
E/flutter (28942): 
```

**Comment by 781flyingdutchman** [comment]
Thanks, very helpful. What Android version are you on?

**Comment by 781flyingdutchman** [comment]
OK, I believe I have found the issue.  Make sure you have a `proguard-rules.pro` file in the app module directory, and add to that file:
```
# For background_downloader, retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
```

Also make sure that your release config uses this file, e.g.:
```
release {
            // your signing configs here
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```

Can you let me know if this works with the published version of the plugin, or if it only works with the `minify` branch referenced above?

**Comment by fpatron** [comment]
Hi @781flyingdutchman,

Thank you for your support.
I updated my proguard-rules.pro file according to your instructions and tested it with two different versions.
However, it didn't work, I am still receiving the same error.

My proguard-rules.pro file

```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.google.firebase.** { *; }
-keep class com.builttoroam.devicecalendar.** { *; }
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

```

I also try to add your package into : 
`-keep class com.bbflight.background_downloader.** { *; }`

Same error

```
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #6      Database.allRecords (package:background_downloader/src/database.dart:36:24)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #7      BaseDownloader.trackTasks (package:background_downloader/src/base_downloader.dart:321:23)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #8      FileDownloader.trackTasks (package:background_downloader/src/file_downloader.dart:689:5)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #9      main (package:lafourmi/main.dart:58:5)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): 
E/flutter (28957): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (28957): 
E/flutter (28957): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method configRequestTimeout on channel com.bbflight.background_downloader)
E/flutter (28957): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #1      NativeDownloader.configureItem (package:background_downloader/src/native_downloader.dart:332:9)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #2      AndroidDownloader.configureItem (package:background_downloader/src/native_downloader.dart:387:25)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #3      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): #4      BaseDownloader.configure (package:background_downloader/src/base_downloader.dart:123:12)
E/flutter (28957): <asynchronous suspension>
E/flutter (28957): 
```

**Comment by 781flyingdutchman** [comment]
That's strange - I could replicate the issue and adding the proguard file & rules did solve it for me. A few thoughts:

- What is the location of your proguard-rules.pro file? It needs to be in the 'app' module of your Android project
- Likewise, the code above under the `release` tag is part of the `app/build.gradle` file
- If you can run in debug with minify on (using the same proguard file) then can you post the logCat logs from the Android device (not the Flutter ones)? [This](https://stackoverflow.com/a/68621427/4172761) answer shows you how you can do that, just for testing (and you don't need to create the 'stage' buildtype, you can just change the debug one). In the debug trace you should see an error related to GeneratedPlugin - which is where the TypeToken issue surfaced for me

Sorry this is so difficult, thanks for your help debugging.

**Comment by fpatron** [comment]
Hi @781flyingdutchman,
I don't why it doesn't work...
When I try this setup I always get the previous error.

```
    buildTypes {
        debug {
            signingConfig signingConfigs.release
            minifyEnabled true
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

I launched a release with the minifyEnabled parameter set to true to test on a device,with the addition of these lines in the proguard-rules.pro file
```
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

```

How do you enable logcat?

**Comment by 781flyingdutchman** [comment]
On logcat: if you run your app in debug mode then in Android Studio there's a tab showing Android logs that is called LogCat. I'm not sure how to access this on other IDEs like VS Code, but I imagine something similar has to be there. It shows the raw Android logs, and if you filter by your package name then you should see the error that triggers the flutter error you're reporting. I'd like to see that error message to understand if it's a different issue than the one I thought I had solved with the proguard rules. Meanwhile, unfortunately you'll have to run with minify off.

**Comment by fpatron** [comment]
@781flyingdutchman 

Today, I tried multiple configs because I was unable to release a version with the BG plugin.
It worked in debug mode but not for release builds.

The only solution I found for keeping minifyEnabled and shrinkResources enabled was to add this to my ProGuard file:

`-keepattributes Signature`

**Comment by 781flyingdutchman** [comment]
Thanks for your help in 'debugging' this. I found this [reference](https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#troubleshooting-gson-gson) specifically for the use of GSON (which is indeed where the error occurs), with this suggestion:
```
-keepattributes Signature
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
```
It's close to what I mentioned earlier, but not exactly the same, and - notably - adds the `keepAttributes Signature` line that you found to work.  So, to make sure we cover this fully, can you try it with the above in your proguard file and confirm you can minify on release?  If so, I am going to mark this as the answer and add it to the readme.

**Comment by fpatron** [comment]
@781flyingdutchman 
I just tested it, and it works with these instructions.
Thanks for your support and your work.
Your plugin is great

**Comment by 781flyingdutchman** [comment]
@fpatron I have changed the serialization mechanism in V8, and was wondering if you could test to confirm that minify now works as expected _without the need for extra proGuard rules_.

To test, modify your pubspec.yaml entry to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: V8-dev
```

You may have to make a few minor changes (V8 is a major revision, so there are some breaking changes) but you'll have to make those to follow along on V8 anyway.

Please let me know what you find.

**Comment by 781flyingdutchman** [comment]
Hi @fpatron , I just published V8.0.0 and one of the changes (under the hood) is a transition to kotlin.serialization. I believe that with that change minification should not longer be an issue, and the workaround described above should no longer be required. If you have a moment, I'd appreciate if you can check and confirm that on this issue thread, for posterity. Thanks!

**Comment by fpatron** [comment]
Hi @781flyingdutchman, I will try as soon as possible and give you a feedback :+1:

**Comment by fpatron** [comment]
Hi @781flyingdutchman 
Sorry for the delay, I just tested the version 8.0.2 with minify enabled and without the proguard rules.
All is ok, it works

**Comment by 781flyingdutchman** [comment]
Great! Thanks for your help in identifying the issue, and for following up.
