### ISSUE TITLE
Upload to AWS S3 with presignedUrl

### ISSUE THREAD

**Issue by delfme** [781flyingdutchman/background_downloader#181]
This is not a bug but would be nice to have an example about how to use the plugin with this popular use case.

With `Dio` code is like:
```
// Get a presigneUrl from flutter Amplify package, remoteUrl is the desired destination url
 final getPresignedUrl = await Amplify.Storage.getUrl(key: remoteUrl).result;
 final presignedUrl = getPresignedUrl.url.toString();

// Upload the file to presignedUrl
await dio.put(
        presignedUrl,
        data: file.openRead(),
        onSendProgress: (int sent, int total) {
          debugPrint('$_debugPrefix File upload progress $sent of total $total');
        },
        options: Options(
          headers: {
            Headers.contentLengthHeader: len,
          },)
    ).then((onResponse){     
      return response;
    }).catchError((onerror){});
```

With `background_downloader` Im using this code: 
file is inside cache dir (no subfolders),
len is file length.

```
    final task = UploadTask(
      url: presignedUrl,
      httpRequestMethod: "PUT",
      headers: {
        "Content-Length": file.lengthSync().toString(),
      },
      baseDirectory: BaseDirectory.temporary,
      filename: filename, 
    );
    final result = await FileDownloader().upload(task,
        onProgress: (progress) {
            final sent = progress*len
            debugPrint('$_debugPrefix File upload progress $sent of total $len');
        } ,
        onStatus: (status) {
            if (status == TaskStatus.complete){
              debugPrint('$_debugPrefix Upload completed.');
            }
        }
    );
```
However, this code doesn't work. Also, I don't get any error, so idk whether the task starts at all.
Tested on:
```
iphone 13 pro ios 16.x
Flutter version: Channel master, 3.17.0-1.0.pre.37
```

**Comment by 781flyingdutchman** [comment]
Three thoughts:
1. It is likely that this should be a binary upload, so you should set the task's `post` field to the string value "binary". 
2. Please check if the signed URL is url-encoded and if not, do that.
3. You should also probably NOT set the content length header, as the plugin will do this too

**Comment by delfme** [comment]
Thx. Im indeed able to start task now, but it doesnt upload

```
[Downloader] Starting task with id 984937331
[Downloader] Binary file upload
```

Im sure that the plugin finds the file, coz if I just edit the path I gets error about file not found in specified path. No error and no result from
```
    final result = await FileDownloader().upload(task,
        onProgress: (progress) {    
          debugPrint('$_debugPrefix File upload progress $progress');
        } ,
        onStatus: (status) {
            debugPrint('Upload Status: ${status.toString()}');
            if (status == TaskStatus.complete){ }
        }
    );
```

**Comment by 781flyingdutchman** [comment]
I'm sorry but I am not familiar with S3. I'll leave this issue open for a while to see if anyone else has an answer.

**Comment by juskuc** [comment]
Have you fixed your issue @delfme? I implemented this exact functionality (uploading a file to an S3 bucket with a presigned URL) in my app yesterday, was having some issues similar to yours at first, but managed to fix them by doing two things:

1. I was getting the file which I wanted to upload from `file_picker` library, which returns a temporary path for the file that you can not really reuse directly to e.g. upload, so what I did was simply copy over the file to application's directory, and upload it from there;
2. adding `post: 'binary'` was also crucial, otherwise the task started and nothing was happening.

Everything looks good for the most part, progress and status updates are working well, I can upload/download without problems, however I did notice occasional crashes happening on app opening after adding this lib, but I'm not sure if it's related to this library or simply my code, looking into it atm

**Comment by delfme** [comment]
Hello @juskuc thx for letting me know.
I couldn't fix my issue. Can you please post your code here for both upload and download, so that we have a working reference for this use case?

**Comment by delfme** [comment]
This is my code
```
 final localStorageDir =await getApplicationDocumentsDirectory();
    String filePath = '${localStorageDir.path}/$filename';
    File file = File(filePath);
    final len = file.lengthSync();
    var startTime = DateTime.timestamp();

    // Get a presigneUrl from flutter Amplify package, remoteUrl is the desired destination url
    final getPresignedUrl = await Amplify.Storage.getUrl(key: 'test_amplify/${basename(file.path)}').result;
    final presignedUrl = getPresignedUrl.url.toString();

    final task = UploadTask(
      url: presignedUrl,
      post: 'binary',
      httpRequestMethod: "PUT",

      headers: {
        "Content-Type": "application/octet-stream",
       // "Content-Length": file.lengthSync().toString(),
      },
      baseDirectory: BaseDirectory.applicationDocuments,
      filename: filename,
    );
    final result = await FileDownloader().upload(task,
        onProgress: (progress) {
          final sent = progress*len;
          debugPrint('File upload progress $sent of total $len');
        } ,
        onStatus: (status) {
          if (status == TaskStatus.complete){
            debugPrint('Upload completed.');
          }
        }
    );
```

Task starts but then this is the log, a weird negative progress after finished. And file is not uploaded to s3 folder.
```
[Downloader] Starting task with id 1095440273
[Downloader] Binary file upload
flutter: File upload progress 0.0 of total 2146824
flutter: File upload progress 1048576.0 of total 2146824
flutter: File upload progress 1572864.0 of total 2146824
[Downloader] Finished task with id 1095440273
flutter: File upload progress -2146824.0 of total 2146824
```

**Comment by delfme** [comment]
Also, is it me or it should display way more progress values?

**Comment by delfme** [comment]
@781flyingdutchman maybe I know why @juskuc can upload.
With code above, I can both upload/download too if I dont use presignedUrl and use remote url directly
```
url: 'https://$bucketName.s3.amazonaws.com/public/test_uploads/${basename(file.path)}',
``
instead of
```
url: presignedUrl,
``

But then everyone who knows our S3 `bucketName` (only the `name`, no need for other security properties) can simply upload files to the bucket :)
@juskuc are you maybe using a different security approach without the presignedUrl ?

**Comment by juskuc** [comment]
Sorry, can't get back to you with code examples at this moment, perhaps later in the evening/tomrrow, but to answer your questions - regarding progress values, I'm not exactly sure, you'd have to ask @781flyingdutchman, I assume the amount of progress updates depends on your download speed and the file size.

As for the security approach - well, for one, I am not using `amplify` library, we went with a different approach of having an AWS Lambda function that I can call through and endpoint which returns to me the presigned urls for download/upload that I can then use. I am not using direct bucket url like the one in your example (`https://$bucketName.s3.amazonaws.com/public/test_uploads/${basename(file.path)}`)

**Comment by 781flyingdutchman** [comment]
Hi, if it works with the unsigned URL then perhaps the presigned URL is not in the right format, or not url-encoded?
Updates are generated when the difference in progress exceeds 2% but is also limited to 2 updates per second, so if you have a fast connection or shorter file you will not see many updates.
I don't understand why you get the negative value: it implies progress==-1 which indicates `failed` yet you also get the status as `complete` so that's not right. Can you share the Android logs, as they tend to show more info?

**Comment by delfme** [comment]
> I don't understand why you get the negative value: it implies progress==-1 which indicates `failed` yet you also get the status as `complete` so that's not right. Can you share the Android logs, as they tend to show more info?

Yea, it seems it occurs when call is not authorized. So from my tests, if we use presignedUrl got from Amplify package, AWS doesnt authorize the call but that presignedUrl works nice with Amplify plugin. If we don't use presignedUrl, we would expose entire bucket to public. There are other way to obtain a presignedUrl, I tried a few but none of them works.

@juskuc 
> As for the security approach - well, for one, I am not using amplify library, we went with a different approach of having an AWS Lambda function that I can call through and endpoint which returns to me the presigned urls for download/upload that I can then use.

I would discourage this approach, coz it would cost money and it is not really required if we get a valid presignedUrl from AWS directly.
