### ISSUE TITLE
insert File to the batch download list

### ISSUE THREAD

**Issue by Blacktaler** [781flyingdutchman/background_downloader#183]
Hi. I'm using background downloader, it's okay that it has some good features, bugs and need some extra features too.
I would ask you to add insertToBatch function, because If someone makes an app which has download functionality and wants to download files one by one, will want to use downloadBatch function like as I wanted to. But there is a question is that, If I use downloadBatch function, then want to add some other files to the downloadList what should I do? I think for now it's impossible to add files to batch after once, it has started

**Comment by 781flyingdutchman** [comment]
The `downloadBatch` function is just a convenience function. If you want a more sophisticated solution you'll have to build your own batch mechanism using regular `enqueue` calls for individual files. You can look at the current way that `downloadBatch is implemented for inspiration. You can also take a look at the `TaskQueue` interface, which can easily be extended to act like a batch queue.

My philosophy here is to keep the downloader simple, and make it easy for developers to add the functionality they need.

**Comment by 781flyingdutchman** [comment]
Hi, you can check out groupnotifications (see [this](https://github.com/781flyingdutchman/background_downloader/discussions/186#discussioncomment-7664237) comment) and see if that solves the problem for you.

**Comment by Blacktaler** [comment]
Hi thanks for the answers, I built my own batch mechanism which downloads files one by one. You're right it's simple to use for now.

**Comment by Blacktaler** [comment]
I noticed one thing that, if there comes any broken file or can't download the file, it goes to the paused state not failed. Thanks for support and nice plugin
