### ISSUE TITLE
cannot download from local server without internet

### ISSUE THREAD

**Issue by thaivm** [781flyingdutchman/background_downloader#188]
My android app want to download mp4 file from local server in ship,
There is no internet on that ship, but app cannot download mp4 file from local server without internet.
if i enable internet then i can download normally.

could you please help to solve or any setting need to set to solve this problem

**Comment by 781flyingdutchman** [comment]
Please look at the configuration section of the docs, as I suspect you'll have to bypass SSL certificate verification. You may have to experiment as it all depends on what your local server does and doesn't do.
