### ISSUE TITLE
App Closing/Crashing on resuming any paused task 

### ISSUE THREAD

**Issue by Rohan487** [781flyingdutchman/background_downloader#189]
**Describe the bug**
I am using enqueue for downloading files, For the past few months it has been working fine, but this month while working on a new version of my app I noticed that on the android <=11 when a download is paused and we are trying to resume it by calling Filedownloader().resume method, the app is crashing

**To Reproduce**
On Android <=11 pause a task and then resume it, os is closing the app 

**Logs**

![Screenshot 2023-11-09 145750](https://github.com/781flyingdutchman/background_downloader/assets/72985121/9f88d7fd-6c74-45f7-9845-b1a22e7498de)

**Comment by 781flyingdutchman** [comment]
Thanks for sharing this issue. Can you also post the raw Android logs from LogCat where the crash occurs? Thanks!

**Comment by Rohan487** [comment]
Hey, Here is full logs from adb logcat 

Logs txt 👉 [error_logs.txt](https://github.com/781flyingdutchman/background_downloader/files/13309177/error_logs.txt)

**Comment by 781flyingdutchman** [comment]
Thanks. Fixed in version 7.12.3
