### ISSUE TITLE
Can i use this with min sdk 21

### ISSUE THREAD

**Issue by Nahid-mk** [781flyingdutchman/background_downloader#190]
This package is best. I have so many users of Android version 5. But this package requires Android version 7.  

so can you please help me on this matter?

It would be very helpful if you can

**Comment by 781flyingdutchman** [comment]
Sorry i can't help you there - Android version 24 was released 7 years ago, and trying to support even older versions adds complexity and maintenance burden that I'm not up for.

**Comment by 781flyingdutchman** [comment]
Hi, Version 8.0.5 now supports minSdk 21
