### ISSUE TITLE
[Help Wanted] Error log from server when uploading file 

### ISSUE THREAD

**Issue by woogi-kang** [781flyingdutchman/background_downloader#192]
Hi there, thanks for the amazing library.

While I was using upload feature in this library, I realized that there was no way to handle error logs from server for either with a listener or callback functions in upload() method.

Does it exist at all to get these error logs? or does it have to be added?

**Comment by 781flyingdutchman** [comment]
Hi! Not sure exactly what you mean with error logs from the server. You can get the server response for the upload from the final `TaskStatusUpdate.responseBody`, which is where you typically might find that kind of information. For errors you can also check the `TaskException`. Let me know if that's what you're looking for, or if not please elaborate.

**Comment by woogi-kang** [comment]
Hello @781flyingdutchman , Thanks for the information about `TaskException`.

However, I have checked with TaskException but it still shows me no error.

I am expecting net::ERR_CONNECTION_RESET error from server. Is there any way for me to get this error log?

`      FileDownloader().registerCallbacks(
        taskStatusCallback: (status) {
          logger.d('1. ${status.exception}');
          logger.d('2. ${status.responseBody}');
          switch (status.status) {
            case TaskStatus.complete:
              {
                if (status.responseBody != null) {
                  logger.d('Upload Completed!');
                  // TODO: handleUploadSuccess
                }
                break;
              }
            case TaskStatus.failed:
              {
                logger.d('Upload Failed: ${status.exception}');
                // TODO: handleUploadFailed

                break;
              }
            default:
              {
                logger.d('Upload Status: ${status.status}');
                break;
              }
          }
        },
        taskProgressCallback: (progress) {
          logger.d('Uploading: ${progress.progress}');
        },
      );`

**Comment by 781flyingdutchman** [comment]
A HTTPException should result in a failed task and show you that error as the TaskException. Can you share the Android logs from LogCat?

**Comment by woogi-kang** [comment]
@781flyingdutchman 

I have tried in Android and I got my expected results but the problem is in iOS. `In iOS, no exception is caught`

![스크린샷 2023-11-13 오후 6 36 45](https://github.com/781flyingdutchman/background_downloader/assets/70678014/059a738b-85e8-4e17-ad30-0bf7e60e5d65)

**Comment by woogi-kang** [comment]
`I/TaskWorker(13526): Exception for taskId 3431453937: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@6c30396
I/WM-WorkerWrapper(13526): Work [ id=69bb4afe-e2a4-4d78-a380-91975ad00b19, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=1887845846, group=default } ] was cancelled
I/WM-WorkerWrapper(13526): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(13526): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper(13526): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper(13526): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper(13526): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
I/WM-WorkerWrapper(13526): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
I/WM-WorkerWrapper(13526): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
I/WM-WorkerWrapper(13526): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
I/WM-WorkerWrapper(13526): 	at java.lang.Thread.run(Thread.java:1012)`

**Comment by 781flyingdutchman** [comment]
Ok, let's focus on the iOS case first. Your screenshot shows: "Upload failed: TaskConnectionException ...".  I believe you extracted that Exception from the TaskStatus, right? If so, that seems to work as intended: you have access to the TaskException, and the TaskException has some information on the nature of the issue.  Can you clarify what you feel is missing or not working here?

**Comment by woogi-kang** [comment]
@781flyingdutchman Hello, i think i solved the problem thanks for the help!
