### ISSUE TITLE
Notification Click Behavior Discrepancy When App Background Updates Are Suspended by OS

### ISSUE THREAD

**Issue by Rohan487** [781flyingdutchman/background_downloader#193]
**Describe the bug**
When the app is in the background but not suspended by the OS, clicking on a notification successfully opens the app. However, when the OS suspends the app's background updates, the notification only displays the progress bar, and clicking on it has no effect.

**To Reproduce**
**Scenario 1 (App not suspended by OS):**

Ensure the app is running in the background but not suspended by the OS.
Receive a notification.
Click on the notification.
**Expected Result:** The app should be brought to the foreground, and the associated screen should open.

**Actual Result:** The app is successfully brought to the foreground, and the associated screen opens.

**Scenario 2 (App suspended by OS):**

Simulate a scenario where the OS suspends the app's background updates.
Receive a notification.
Click on the notification.
**Expected Result:** The app should be brought to the foreground, and the associated screen should open.

**Actual Result:** The notification displays a progress bar, but clicking on it has no effect. The app does not come to the foreground.

**Comment by 781flyingdutchman** [comment]
Can you let me know what OS this is happening on, and how you are simulating the OS suspending the app?

**Comment by Rohan487** [comment]
Hey I Tested on 

Android 13 (Realme OS)
Android 10 ( MIUI )

It's happening on both, When I exit the app by pressing the back button os suspends the background updates may be for performance it's on some Android phones ( Chinese ROMs like MIUI and Realme maybe )

**Comment by 781flyingdutchman** [comment]
HI, yes, unfortunately I've seen a lot of reports complaining about this aggressive performance management of some OS implementations (not just for this package) that affects functionality. The only thing I think you can try is to configure the downloader to use 'foreground' mode - see the configuration document for that.  

Closing this issue here, as there is really nothing I can do about this.
