### ISSUE TITLE
Canceling a Paused task not removing the Notification When Notification for Pause is Enabled

### ISSUE THREAD

**Issue by Rohan487** [781flyingdutchman/background_downloader#194]
**Description:**

Canceling a running task successfully cancels the task and removes the associated notification. However, when a task is paused, and the user cancels it, the task is cancelled, but the notification with the resume button persists in the status bar.

**To Reproduce:**

1. Enable notifications for paused tasks by setting the paused property in FileDownloader().configureNotification.
2. Download a task and pause it.
3. Observe the paused notification in the status bar.
4. **IMPORTANT:  Cancel the paused task from the method FileDownloader.cancelTaskById()**

**Expected Behavior:**
The notification associated with the cancelled paused task should be removed from the status bar.

**Actual Result:**
After canceling the paused task using the method FileDownloader.cancelTaskById(), the notification with the resume button remains visible in the status bar.

Only After Clicking the Cancel button from the notification of paused task is working as expected.

**Comment by Rohan487** [comment]
Its happening on Android all versions

**Comment by Rohan487** [comment]
I have tested on Samsung S23 Android 14 , and also in Android 13 , 11, 10

Paused Notification is not removing, when we are cancelling a paused task using cancelTaskById() 

You can check it in virtual devices, may be you will see same behaviour

**Comment by 781flyingdutchman** [comment]
Yes, confirmed, and I think this issue also pops up if a task retry fails -> the 'error' notification is not shown in that case.  I need to make it possible to set the notification from the Dart side (currently all notifications are triggered from the native side only).

**Comment by 781flyingdutchman** [comment]
Hi, this should be fixed in the pre-release of V8. Would you mind testing & confirming? Change your pubspec.yaml to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: V8-dev
```

There are a few minor changes with the V8 release (some breaking) so you may need to make minor modifications to your app - see the CHANGELOG - but those will be required for the V8 release anyway (the change won't make it into V7).

Thanks for your help!

**Comment by 781flyingdutchman** [comment]
Included in V8-dev
