### ISSUE TITLE
batchProgressCallback is not real-time enough

### ISSUE THREAD

**Issue by CoderLengary** [781flyingdutchman/background_downloader#195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I found that the way `batchProgressCallback` calculates progress is not real-time enough. The calculation method here is to divide the number of files that have been downloaded by the total number of files to be downloaded. Imagine a situation where I am downloading a collection, which includes 2 small files and one very large file. When I finish downloading the small files and start downloading the large file, even if I am downloading the large file, the overall progress will still be stuck at 2/3. I think a more reasonable way is to divide the number of bytes downloaded for this collection by the total number of bytes of all files in the collection. This way, the progress will not be stuck at 2/3.

**Describe alternatives you've considered**

**Additional context**

**Comment by 781flyingdutchman** [comment]
Hi, thanks for your feedback and suggestion. I agree this would be better for certain instances, but it is quite complex and not always possible (e.g., file size is not know until a download starts, which is not when the batch starts, and file size is not provided by all servers). The batch download functionality is a simple interface on top of the basic downloader, and I intend to leave it as a simple implementation. If you need the functionality you describe, then I'm afraid you'll have to add it on top of the basic download functionality yourself, or perhaps submit it as a PR if you can get it to work consistently and tested.

Closing this as "not planned".
