### ISSUE TITLE
How to get bytes from URL when the Response.data will be List<int>?

### ISSUE THREAD

**Issue by bahman2000** [781flyingdutchman/background_downloader#198]
Hello,
This should not be a bug or feature request but I'd need a clarification on how to get bytes from URL.

To get bytes from URL via `Dio`, code would be:
` Response response = await _dio.get('URL',
          options: Options(
            responseType: ResponseType.bytes,
          ));`

How can I do this with `DownloadTask`?

**Comment by 781flyingdutchman** [comment]
You'll download the response bytes to a file, then convert the file to a List<Int> like this:
```
Future<Uint8List?> loadToIntList(final DownloadTask task) async {
  final success = await FileDownloader().download(task);
  if (success.status == TaskStatus.complete) {
    final file = File(await task.filePath());
    final intList = await file.readAsBytes(); // this is your Uint8List
    await file.delete();
    return intList;
  }
  return null;
}
```

This downloads the file (your server response) from `task`, then converts the downloaded file to a `UInt8List` and deletes the file, before returning the list. If something goes wrong, it returns null - not the best error handling but you get the idea :)

**Comment by bahman2000** [comment]
@781flyingdutchman I really appreciate your great work on the `background_downloader` . Thank you so much.

**Comment by bahman2000** [comment]
@781flyingdutchman I really appreciate your great work on the background_downloader . Thank you so much.
