### ISSUE TITLE
[BUG] cannot download/upload with Cellular in iOS17

### ISSUE THREAD

**Issue by woogi-kang** [781flyingdutchman/background_downloader#199]
**Describe the bug**
Hello, thanks for making this library.
I am having trouble with iOS and I was hoping to get some help.

#### Process with Wifi:
Works fine for download/upload/enqueue

#### Process with Cellular:
When download/upload/enqueued functions are called, Tasks are properly enqueued (status changes to TaskStatus.enqueued), but does not change to TaskStatus.running after. The tasks stays TaskStatus.enqueued. 

I have tried setting requiredWifi = false, retries = 0, but still not being changed to running
How should I fix this problem?

### Environment:
iOS 17, latest background_downloader version

### Exception:
iOS 16/15 works fine

### Current Code:

```
final task = DownloadTask(
      group: 'download',
      url: downloadLink,
      filename: fileName,
      headers: {'Authorization': 'Bearer jwt:$jwt'},
      updates: Updates.statusAndProgress,
      directory: 'Downloads',
      baseDirectory: Platform.isAndroid ? BaseDirectory.applicationSupport : BaseDirectory.applicationDocuments,
      requiresWiFi: false,
      retries: 0,
    );

    var result = await FileDownloader().download(
      task,
      onStatus: (status) {
        logger.d(status);
      },
      onProgress: (progress) {
        logger.d(progress);
      },
    );
```
[log] │ 🐛 TaskStatus.enqueued
not changing from this log

**Comment by 781flyingdutchman** [comment]
Hi, sorry you're having this problem. I've tried to replicate it but can't, so was wondering if you can share the logs (from the iOS Console, filtered by "Downloader" Category), and ideally also try it with the soon-to-be-released V8 (as that's all I am working on right now). To do that, change your pubspec.yaml entry to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: V8-dev
```

Thanks!

**Comment by woogi-kang** [comment]
@781flyingdutchman Hi thanks for detailed guide.

Did you failed to replicate the same results in same condition as I am? Does that mean you could download/upload files using cellular network in iOS 17?

I have tried using the v8-dev version but still all tasks are being remained TaskStatus.queued in iOS17 devices, in Celluar mode(not Wifi). 

I can provide you the logs on Monday (I don't own iphone devices sorry)

**Comment by woogi-kang** [comment]
@781flyingdutchman 

I have found this [https://discussions.apple.com/thread/253094215](url) issue that looks similar with what I am having right now.

I tried changing the cellular option that is suggested in the link but still nothing changes. Hope this could help

**Comment by 781flyingdutchman** [comment]
Hi, I have tried on a real iPhone with iOS 17 and switching wifi off (so cellular only) and have no issue downloading. I strongly suspect there is a setting on your device(s) that prevents cellular downloads - perhaps similar to what is described for the Files app in the link you provided. I don't know enough about iPhones or iOS17 to know what that might be, but I don't see an issue here with the downloader. The logs you provided don't tell me anything otherwise either - sorry.

**Comment by woogi-kang** [comment]
@781flyingdutchman 

Thanks for your help. 

I have been comparing my code with the sample code in the library and I think I found out the error.

In Cellular env, domain with `http` is not being downloaded/uploaded but if the domain is `https` the downloading and uploading works fine.

Do you know about this issue?

**Comment by 781flyingdutchman** [comment]
Yes, this is called ATS and you can read about it here: https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/

Both iOS and Android strongly discourage use of http.

**Comment by woogi-kang** [comment]
@781flyingdutchman 

So you mean because of ATS settings, files aren't allowed to download in only 'Celluar'?
Cause I can download files from same http domain with 'Wifi'.

Kinda weird that only Cellular is not allowed (Can't find this information in any of apple documents) 🥲🥲🥲

**Comment by 781flyingdutchman** [comment]
I wasn't aware that that only applies to Cellular (I also thought this would apply always). See [here](https://pub.dev/packages/background_downloader#ios) for another link. I've never tried this, and would encourage you to explore using HTTPS if at all possible, because this will only get harder with new OS releases I think.

Closing this issue, but please add any further details you can find to help others.
