### ISSUE TITLE
Prefer UTF-8 content-disposition headers

### ISSUE THREAD

**Issue by rekire** [781flyingdutchman/background_downloader#200]
**Is your feature request related to a problem? Please describe.**
While debugging an content-disposition error. I noticed that in the [test](https://github.com/781flyingdutchman/background_downloader/blob/V7.12.3/example/integration_test/downloader_integration_test.dart#L2622-L2633) the non unicode filenames are preferred. 

**Describe the solution you'd like**
At least Firefox prefers the UTF-8 file names. I would like that this library would do the same.

**Describe alternatives you've considered**
If you count this as a breaking change a new flag would be nice.

**Comment by 781flyingdutchman** [comment]
Good point! I'll look into this and likely switch to UTF preferred in V8

**Comment by 781flyingdutchman** [comment]
Included in V8-dev

**Comment by 781flyingdutchman** [comment]
V8 is now published.
