### ISSUE TITLE
Support-Request about content-disposition (again)

### ISSUE THREAD

**Issue by rekire** [781flyingdutchman/background_downloader#201]
I need your help to understand a bug. I'm downloading files like this:
```dart
final backgroundDownloadTask = await DownloadTask(
  url: 'https://example.com/4711/export,
  baseDirectory: BaseDirectory.applicationDocuments,
  updates: Updates.status,
  allowPause: true,
).withSuggestedFilename(unique: true);
await FileDownloader().enqueue(backgroundDownloadTask);
```

In most cases that simply works as intended, but in some cases it does not work and I don't understand why. I already debugged your method [`withSuggestedFilename`](https://github.com/781flyingdutchman/background_downloader/blob/V7.12.3/lib/src/models.dart#L677) there I can see that there is no `content-disposition` header. To be honest I'm confused how it works. Those URL which do not work require session cookies. But I can see a 200 response which does not make sense in my mind. When I do the request in curl I get without a cookie a redirect to the login. With cookies I get in curl the header which is missing in your libraries head response. The resulting file has the expected size, but cannot been opened.

I think I found a way to get the cookies from the webview but I am not sure how I can convert the [Cookie](https://api.dart.dev/be/180791/dart-io/Cookie-class.html) to a Cookie header which I can pass to your library for the request.

**Comment by 781flyingdutchman** [comment]
Interesting - I'm not very familiar with cookies, but I don't think the downloader supports cookies or if the box, as there is no Kotlin code referring to cookies, and nothing related to cookies use transferred from Flutter to Android. When you say "in curl, with cookies..." how's do you pass the cookie info to curl? Is that via a header? When you get the successful outcome using curl, do you know if the content disposition header use returned as part of the first response (the redirect) or as part of the second? The downloader currently only keeps the final response header, so that may also be an issue.

**Comment by rekire** [comment]
I just copied the curl request from the developer console of the browser. There the cookies are passed via the -H (header) argument (which is basically a key value pair) as in your headers argument. My point is just that I am not sure how the format from the "set-cookie" server response are converted to the "cookie" header of the request. I think there is no need to reinvent the wheel, but I just don't know it right now.

Regarding redirects: When I request the file without proper authorization I get a 302 response with a redirect to the login page which is byside of a 403 or 401 okay out of my view. But that login page should not be downloaded of cause :-)

With proper authentication I get for a HEAD request a 200 with the content-disposition response header and I also get the file content when I use GET instead.

When I pass the headers argument to the `DownloadTask()` constructor will those headers also been used for the HEAD request?

**Comment by 781flyingdutchman** [comment]
I just read [this](https://web.archive.org/web/20170122122852/https://www.nczonline.net/blog/2009/05/05/http-cookies-explained/) and it looks like this is a two step process:
1. Make a regular request to the server with login information, to obtain a cookie. This should be done using the `FileDownloader().request` method, and the cookie information is contained in the Response header "Set-Cookie". Store that cookie information
2. Create your download request as you show in your code example, and add the cookie information obtained in step 1 by adding a "Cookie" header using the task `headers` field

For example if your request in step 1 includes a header `Set-Cookie: XYZ=abc; expires=Sat, 02 May 2009 23:38:25 GMT` then per the article you should add a header `{'Cookie': 'XYZ=ABC's}` to your DownloadTask.

Let me know if this works!

And yes, the headers you specify on the task are used for the Head request that is done to get the suggestedFilename

**Comment by 781flyingdutchman** [comment]
Looks like the httpResponse had a `cookies' getter to get a list of cookies set by the server, so you can use that in step 1 to parse the cookies to add. https://api.flutter.dev/flutter/dart-io/HttpResponse/cookies.html

**Comment by rekire** [comment]
This seems to be the way to get it working I guess. I just need to find out how to convert the `Cookie`s to the format requested for the `Cookie` request header. Most likely just `cookies.map((c) => '${c.name}=${c.value}').join(' ')`

**Comment by 781flyingdutchman** [comment]
I think, per the article, you should `.join('; ')`

**Comment by rekire** [comment]
Oh that makes sense why it didn't work on my first try 👍🏻

**Comment by rekire** [comment]
Yes that is the solution. Thank you!

**Comment by 781flyingdutchman** [comment]
Hi, inspired by your question I added `Request.cookieHeader` to V8.0.0, to parse the 'Set-Cookie' response header and add it to your download task.

From the docs

Servers may ask you to set a cookie (via the 'Set-Cookie' header in the response), to be passed along to the next request (in the 'Cookie' header).
This may be needed for authentication, or for session state.

The method `Request.cookieHeader` makes it easy to insert cookies in a request. The first argument `cookies` is either a `http.Response` object (as returned by the `FileDownloader().request` method), a `List<Cookie>`, or a String value from a 'Set-Cookie' header. It returns a `{'Cookie': '...'}` header that can be added to the next request.
The second argument is the `url` you intend to use the cookies with. This is needed to filter the appropriate cookies based on domain and path.

For example:
```dart
final loginResponse = await FileDownloader()
   .request(Request(url: 'https://server.com/login', headers: {'Auth': 'Token'}));
const downloadUrl = 'https://server.com/download';
// add the cookies from the response to the task
final task = DownloadTask(url: downloadUrl, headers: {
  'Auth': 'Token',
  ...Request.cookieHeader(loginResponse, downloadUrl) // inserts the 'Cookie' header
});
```
