### ISSUE TITLE
... is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by MorosophDude** [781flyingdutchman/background_downloader#202]
**Describe the bug**
I am running `background_downloader: 7.12.3`, when I try to run the app it requires minimum target to be iOS 13 (please see _Logs_ section below for console log), which I have already set. 
I believe this minimum target of iOS 13 needs to be set on Podfile of this package.

**Some other interesting findings**
1. This issue looks related to https://github.com/781flyingdutchman/background_downloader/issues/74 but I am not so sure as it is closed and I had already tried the solution mentioned there.
2. Although confusing at first this issue is quiet easy to solve/workaround
    2.1. Open the iOS project in xCode
    2.2. Click on `Pods` from sidebar on the left
    2.3. Under `TARGETS` find `background_downloader`
    2.4. Select the `General` tab (if not already selected) and find `Minimum Deployments` section
    2.5. Change it to from `12.0` to `13.0`
    2.6. Run the app.
(You will need to repeat these steps if you use `flutter clean` command or something else that will replace/revert this modified instance of the package from `./pub-cache`)
<img width="1137" alt="Screenshot 2023-11-30 at 14 13 28" src="https://github.com/781flyingdutchman/background_downloader/assets/25612158/8748b705-f035-4eb9-951c-ce2aadfde791">

**Expected behavior**
For the app to just run since I have already set minimum target to 13.0 in my Podfile.

**Logs**
When trying to run the app I get
```
Failed to build iOS app
Swift Compiler Error (Xcode): 'Task' is only available in iOS 13.0 or newer
/Users/username/.pub-cache/hosted/pub.dev/background_downloader-7.12.3/ios/Classes/Downloader.swift:61:29

Swift Compiler Error (Xcode): 'init(priority:operation:)' is only available in iOS 13.0 or newer
/Users/username/.pub-cache/hosted/pub.dev/background_downloader-7.12.3/ios/Classes/Downloader.swift:61:29

...

Swift Compiler Error (Xcode): 'value(forHTTPHeaderField:)' is only available in iOS 13.0 or newer
/Users/username/.pub-cache/hosted/pub.dev/background_downloader-7.12.3/ios/Classes/ParallelDownloader.swift:23:92

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
```

**Additional context**
1. I am not quite sure what caused this issue in my system. I did upgrade flutter sdk, all dependencies in puspec.yaml, xcode, ... all at once and then after a week tried running this project.
2. These are the current version in my device
 - Flutter 3.16.1 • channel stable
 - xCode 15.0.1
 - background_downloader: ^7.12.3
 - Simulator: iPhone 14 Pro Max on iOS 17.0

**Comment by 781flyingdutchman** [comment]
Thanks for highlighting this. Added to the PodSpec in V8 (which you can preview on V8-dev).
