### ISSUE TITLE
Bug: Failure in SSL library

### ISSUE THREAD

**Issue by agufagit** [781flyingdutchman/background_downloader#205]
**Describe the bug**
if a cloud file presigned request expired, get a new presigned request url, and download again, give SSL library error

**To Reproduce**
1. download with an expired cloud file presigned request url
2. handle 403 exception, and get a new presigned request url
3. run the same code again to download with new presigned request url

**Expected behavior**
file downloaded with new presigned request url

**Logs**
```
I/TaskWorker(24981): Exception for taskId 3268501357: kotlinx.coroutines.JobCancellationException: DispatchedCoroutine is cancelling; job=DispatchedCoroutine{Cancelling}@5fd92bf
W/TaskWorker(24981): Error for taskId 3268501357: Read error: ssl=0x75f12c637d58: Failure in SSL library, usually a protocol error
W/TaskWorker(24981): error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT (external/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1095 0x75f08f2892dc:0x00000000)
W/TaskWorker(24981): error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC (external/boringssl/src/ssl/tls_record.cc:298 0x75f08f2892dc:0x00000000)
W/TaskWorker(24981): javax.net.ssl.SSLProtocolException: Read error: ssl=0x75f12c637d58: Failure in SSL library, usually a protocol error
W/TaskWorker(24981): error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT (external/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1095 0x75f08f2892dc:0x00000000)
W/TaskWorker(24981): error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC (external/boringssl/src/ssl/tls_record.cc:298 0x75f08f2892dc:0x00000000)
W/TaskWorker(24981): 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
W/TaskWorker(24981): 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
W/TaskWorker(24981): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
W/TaskWorker(24981): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
W/TaskWorker(24981): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
W/TaskWorker(24981): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
W/TaskWorker(24981): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
```

**Code**
Code uses flutter_hooks, when `retry` value changes, code in `useEffect` will run again
```
final downloader = useValueNotifier<FileDownloader?>(null);
final task = useValueNotifier<DownloadTask?>(null);

useEffect(() {
      task.value = DownloadTask(
        url: file.url!,
        filename: file.baseFileName,
        directory: '$category/$msgId',
        baseDirectory: BaseDirectory.temporary,
        updates: Updates.statusAndProgress,
        allowPause: true,
        headers: {'Connection': 'close'},
      );

      downloader.value = FileDownloader();

      downloader.value!
          .download(
        task.value!,
        onProgress: (progressValue) => progressValue > 0 ? progress.value = progressValue : progress.value = 0,
      )
          .then((result) async {
        switch (result.status) {
         ...
         case TaskStatus.failed:
             final url = getNewUrl();
             file.url = url;
             downloader.value!.destroy();
             retry = retry + 1;
             break;
         ...     
      }})

      return null;
}, [retry]}

```

**Comment by 781flyingdutchman** [comment]
I'm afraid you're on your own getting a new presigned URL 😊. That's not what I consider core download functionality, as there are many different ways one may have to go about this, depending on the server you are trying to download from.

**Comment by 781flyingdutchman** [comment]
Have you url-encoded the URL that you use in the Task definition? Perhaps you need additional headers?

**Comment by agufagit** [comment]
It works when URL is not expired.  For the new URL, I saved it to database, when I reload the screen, it works.  So the error only happens in this sequence:

1. First task: url is expired, 403 exception is returned, task status is `failed`
2. Handle 403 exception, get new URL, retry
3. 2nd task is created, doesn't matter if it's the same FileDownloader() or new FileDownloader(), when I call FileDownloader().download(...) again, this error will happen

btw, how to debug this project using vscode?  I'll try to dig into this if you can point me to a place to learn how to debug those .kt files

Thank you

**Comment by 781flyingdutchman** [comment]
Hi, from the error it seems like this is related to your SSL certificate. I suggest you Google around a bit to see how to fix it - I don't think there's anything about the plugin that's causing this.

**Comment by agufagit** [comment]
After upgrading to version 8.0.2, it gives this error now all the time.  I googled, it looks like in Android API level 16+ TLS 1.1 and 1.2 are not enabled by default so it needs to be enabled, as described [here](https://stackoverflow.com/a/55217773)

**Comment by 781flyingdutchman** [comment]
Hi, according to the [SSLSocket documentation](https://developer.android.com/reference/javax/net/ssl/SSLSocket) for Android, TLSv1.1 and TLSv1.2 are enabled by default starting at API Level 20. Since the minSdk for the downloader is 23, both older protocols should be enabled. Also, there are good reasons for Android making decisions for what protocols to support, and I am not familiar enough with SSL to suggest anything different. So, I still am going to keep this closed as not a bug caused by the plugin.
