### ISSUE TITLE
Please simplify Upload process in background_downloader

### ISSUE THREAD

**Issue by sumitanaiya** [781flyingdutchman/background_downloader#207]

**Comment by 781flyingdutchman** [comment]
Hi. Location is given in 3 parts: baseDirectory (default is the documents directory), directory (subdirs following baseDirectory, default is none), filename.

From your earlier edit it looks like you only pass a filename, so the downloader would look for the file in the application documentsDirectory. 

In version 8, just released, you can also specify baseDirectory.root and have the absolute path to the file (minus the filename itself) as the directory. However, please read the warning in the docs about using that approach, especially on iOS.

Let me know if this solves it.

**Comment by scottynoshotty** [comment]
Is there any reason there can't be an API that just takes a File as argument?

**Comment by 781flyingdutchman** [comment]
Per the documentation, there are good reasons why passing an absolute path is generally not a good idea (on mobile platforms) so it's not something I want to encourage by making it easier, plus it would add more complexity to the API by providing an alternative. It's trivial to create the upload task based on a File (untested, but something like this):
* Set `baseDirectory` to `BaseDirectory.root`
* Set `directory` to `yourFile.parent.path`
* Set `filename` to `yourFile.path`
