### ISSUE TITLE
Version 8.0.0+ doesn't compile with Xcode 14.2

### ISSUE THREAD

**Issue by Aulig** [781flyingdutchman/background_downloader#209]
First of all, thank you for this awesome project, it has helped me a lot.

When compiling an app with version 8.0.0 or 8.0.1 I get this error:

Swift Compiler Error (Xcode): Extra argument 'encodingInvalidCharacters' in call
/Users/administrator/.pub-cache/hosted/pub.dev/background_downloader-8.0.1/ios/Classes/BDPlugin.swift:156:67

The code this error is referring to is this one:
```
let url: URL?
if #available(iOS 17.0, *) {
    url = URL(string: task.url, encodingInvalidCharacters: false)
} else {
    url = URL(string: task.url)
}
```

I'm pretty sure I'm experiencing this issue because I'm using Xcode 14.2 still which doesn't support iOS 17. Unfortunately I can't just update, since my mac doesn't support Xcode 15. I'm pretty sure I saw something similar before in Flutter and they solved it using version gates or something like that.

**Comment by 781flyingdutchman** [comment]
Hi! If you're trying to compile for iOS 17 on XCode 14 that simply won't work. If you have to use XCode 14 then you cannot target iOS 17, per [this example](https://developer.apple.com/forums/thread/730947?answerId=754878022#754878022).

Is that the situation you're in, or do you get this error when targeting iOS 16?

**Comment by Aulig** [comment]
> Hi! If you're trying to compile for iOS 17 on XCode 14 that simply won't work. If you have to use XCode 14 then you cannot target iOS 17, per [this example](https://developer.apple.com/forums/thread/730947?answerId=754878022#754878022).
> 
> Is that the situation you're in, or do you get this error when targeting iOS 16?

Thanks for your help - I'm not trying to do anything like that as far as I'm aware. My deployment target is iOS 13.0 as per the minimum requirements of background_downloader:
![grafik](https://github.com/781flyingdutchman/background_downloader/assets/32148066/ffd08d1e-1179-44b6-8d5b-9d6e6a113d5d)

I'm trying to run the app on an iOS 16.2 simulator (that comes with my Xcode version 14.2).

**Comment by 781flyingdutchman** [comment]
Hi, thanks. I've done a bit more research, but unfortunately this doesn't look good. Here's what Bard says about it:

> You are correct, the existing version gate in the code is causing a compile-time error because Xcode 14.2 doesn't support iOS 17. As the package maintainer, here are some options to consider:
> 
> 1. Backport the encodingInvalidCharacters parameter:
> Implement the functionality of encodingInvalidCharacters manually for older iOS versions. This may involve checking the character encoding and performing appropriate adjustments before creating the URL.
> This approach ensures compatibility with older versions of Xcode but requires additional maintenance effort.
> 
> 2. Provide alternative APIs:
> Offer separate APIs for versions with and without the encodingInvalidCharacters parameter. This allows developers using older Xcodes to access the desired functionality through a different API.
> This approach provides flexibility for users of different Xcode versions but may increase code complexity.
> 
> 3. Increase the minimum supported iOS version:
> Update the package's minimum supported iOS version to 17. This will prevent users on older versions of Xcode from installing the package.
> This approach ensures compatibility with the latest features but may limit your user base.
> 
> 4. Document the issue and offer workarounds:
> Clearly document the compatibility issue in the package's README and provide workarounds for users on older Xcodes. This may involve instructing users to use the appropriate API or manually handle the character encoding.
> This approach offers transparency and flexibility but may require additional support for users encountering the issue.
> 
> 5. Use a compatibility layer:
> Explore libraries or frameworks designed to provide compatibility with newer iOS features on older Xcodes. This may involve using a separate package or modifying your existing code to work with the compatibility layer.
> This approach can be an efficient solution but may depend on the availability of suitable compatibility libraries.

Unfortunately, neither of these are possible for me, and I _have_ to support iOS 17 (that code snippet is required to run on iOS 17, as that URL functionality has changed). You'll have to upgrade to XCode 15 to use version 8 - I guess that's how Apple is getting you to buy a new Mac :(

**Comment by Aulig** [comment]
I found the version gate thing again :) 
Here's how they do it in the webview_flutter plugin: https://github.com/flutter/flutter/issues/129587#issuecomment-1608700939
Relevant code: https://github.com/bparrishMines/packages/blob/561029a1820dd5a1f28f9773a1a3e5e3b9a90307/packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FWFWebViewHostApi.m#L204C7-L204C7

Not sure if that is easily doable for you too or if that requires a different build pipeline or something. Even if you can't change it in this case maybe it'll be useful at some point in the future and we both learned something new ;)

If it's not possible I guess I'll fork and remove the iOS 17 stuff - hopefully it's not too much.

**Comment by 781flyingdutchman** [comment]
As I understand it, __IPHONE_OS_VERSION_MAX_ALLOWED is for Objective-C and there is no equivalent for Swift. You're welcome to fork and see if you can implement this, and if it passes all test also on iOS 17 I can merge a PR.

You can also fork the repo and remove the conditional (it's the only one) but I don't know if that means your app won't work as expected on iOS 17 (I am not really sure how iOS manages versions).

Sorry I can't be more helpful.
