### ISSUE TITLE
Support for minSdkVersion below 24

### ISSUE THREAD

**Issue by suryansh-t** [781flyingdutchman/background_downloader#211]
We have a very big base of users who use Android 6 or below,  and our findings suggest that the plugin functions seamlessly without the current minSdkVersion restriction.

Considering the significant number of users still utilizing Android 6, I believe it would be highly beneficial to either remove the constraint entirely or, at the very least, consider supporting API level 23.

Thank you for your time and attention to this matter. I appreciate the effort you've invested in developing and maintaining this amazing plugin.

**Comment by 781flyingdutchman** [comment]
Hi,

Unfortunately the code does not compile properly when minSdkk is set to 23, as we do use APIs only available in 24. 23 is very old, and while I understand you may have a sizable installed base, locking myself into supporting version 23 is not something I am prepared to do.

**Comment by 781flyingdutchman** [comment]
Hi, with some recent changes it became easier to support lower API, so minimum is now API 21. Hope this helps!

**Comment by suryansh-t** [comment]
Thanks for the great work!
