### ISSUE TITLE
Add option to disable NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by Aulig** [781flyingdutchman/background_downloader#213]
**Is your feature request related to a problem? Please describe.**
After upgrading to version 8 (thanks to your help with getting it to work on Xcode 14 ❤️), I tried uploading my app to App Store Connect, where my build was rejected with the following e-mail:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, ****

Please correct the following issues, then upload again.

ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Runner.app” bundle should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources. 
```

I don't use the new feature to move downloaded files into the photo library, so my app doesn't really need the permission. I'm currently making up a reason as to why the permission is necessary, but I've previously had Apple reject the app because a given permission reason is not valid in their eyes.

**Describe the solution you'd like**
My proposed solution: Offer compiling out the permission, for example like it's done in [the permission_handler package](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) (see iOS section where certain permissions can be disabled using the Podfile). The [audio_session plugin ](https://github.com/ryanheise/audio_session#ios-setup)does something like that too.

**Comment by 781flyingdutchman** [comment]
Thanks for the suggestion - I'll look into this.

**Comment by 781flyingdutchman** [comment]
See PR #219 -> would love your feedback

**Comment by 781flyingdutchman** [comment]
Implemented in V8.0.3

**Comment by Nico04** [comment]
I've just uploaded my first build using background_downloader to the App Store, and I received the same issue regarding NSPhotoLibraryUsageDescription. And I'm not using any of the share lib APIs.
I'm using background_downloader v8.5.2 and Flutter v3.22.2

**Comment by 781flyingdutchman** [comment]
Hi, please read the section on bypassing permissions checking on iOS in the docs. You have to set a compiler flag to prevent the code related to those permissions getting compiled.
