### ISSUE TITLE
Need to monitor downloaded bytes

### ISSUE THREAD

**Issue by alllohaaa** [781flyingdutchman/background_downloader#214]
[some fileservers](https://filesamples.com/formats/mkv#google_vignette) does not return content length, so downloader does not provide progress updates. I need to show at least something to user, currently on Android I do 
```  
final checkTimer = Timer.periodic(const Duration(seconds: 1), (Timer timer) async {
      // if (fileSize.value != null) return;
      var cacheDir = await getTemporaryDirectory();
      rxDownloaded.value = cacheDir.listSync()
        .where((f) => f.path.contains('com.bbflight.background_downloader'))
        .map((f) => File(f.path))
        .where((f) => f.existsSync())
        .firstOrNull?.lengthSync();
    }); 
``` 
but this smells. Please include downloaded bytes in progress updates

**Comment by 781flyingdutchman** [comment]
Hi, I understand what you're looking for - it's not a priority at the moment. Meanwhile, you can approximate progress by passing a `Known-Content-Length` header if you know the (approximate) file size, see [here](https://pub.dev/packages/background_downloader#monitoring-the-task). Alternatively you can use the `onElapsedTime` callback to get a regular ping during download that you can use to create animation (somewhat similar to your code snippet, but of course without the actual temp file size). 

Marking this as an enhancement, and closing it as I won't be able to work on this for now. If you have the time and confidence to implement this on all three platforms then please submit a PR.
