### ISSUE TITLE
How to limit the maximum number of simultaneous downloads?

### ISSUE THREAD

**Issue by luigi-bar** [781flyingdutchman/background_downloader#215]
Hi,
    first of all, many thanks for this very cool library, it's a lifesaver :+1: 

Now my question: I would like to download something like 1000 files, 1M each from my server. I have modified the example code for the "bunch" test accordingly and the package works fine, but I have the impression that it is trying to download all these files at once... is it correct?

If yes, I am basically DDoS-ing my own server :smile: ... Is there a way to limit the number of simultaneous downloading tasks?
Thanks!

**Comment by 781flyingdutchman** [comment]
Yep, look at TaskQueue here:
https://pub.dev/packages/background_downloader#task-queues

**Comment by luigi-bar** [comment]
Sorry I missed that one in the docs, many thanks!
