### ISSUE TITLE
Ios Notification

### ISSUE THREAD

**Issue by Meshkat-Shadik** [781flyingdutchman/background_downloader#216]
I'm using something like that to have the download with notification behavior. Which works on android but not in ios.
**Currently I'm testing on Ios Simulator (iPhone 14 Pro Max - iOS 17.2)**
```dart
final taskId = await FileDownloader()
          .configureNotification(
            running: const TaskNotification(
              'Downloading {filename}',
              '{progress}%',
            ),
            complete: TaskNotification(
              'Download completed',
              'file : $fileName',
            ),
            error: TaskNotification(
              'Download failed',
              'file : $fileName',
            ),
            paused: TaskNotification(
              'Download paused',
              'file : $fileName',
            ),
            progressBar: true,
            tapOpensFile: true,
          )
          .download(
            DownloadTask(
              url:
                  'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4',
              directory: downloadPath,
              httpRequestMethod: 'GET',
              filename: 'big_buck_bunny_720p_20mb.mp4',
              baseDirectory: BaseDirectory.root,
              creationTime: DateTime.now(),
              allowPause: true,
              updates: Updates.statusAndProgress,
              headers: {
                'Accept': 'application/json',
                'Connection': 'keep-alive',
                'Authorization': 'Bearer $token',
              },
            ),
          );
      FileDownloader().updates.listen((update) {
        if (update is TaskStatusUpdate) {
          if (update.status == TaskStatus.complete) {
            'Download completed'.toast(true);
            FileDownloader().cancelTaskWithId(taskId.task.taskId);
          } else if (update.status == TaskStatus.failed) {
            FileDownloader().cancelTaskWithId(taskId.task.taskId);
            'Download failed'.toast(false);
          }
        }
      });
```
Note: the file download is working perfectly, but the problem is only about notification.

**Comment by 781flyingdutchman** [comment]
The iOS notification system works very differently from Android, so I suspect it's a matter of it behaving as intended, but different from what you expect. For example, iOS notifications are not visible when the app is open, and the progress percentage is not supported on iOS. Please read the notifications section of the documentation, including Apple's guidelines for how notifications are supposed to work on iOS.

**Comment by Meshkat-Shadik** [comment]
> The iOS notification system works very differently from Android, so I suspect it's a matter of it behaving as intended, but different from what you expect. For example, iOS notifications are not visible when the app is open, and the progress percentage is not supported on iOS. Please read the notifications section of the documentation, including Apple's guidelines for how notifications are supposed to work on iOS.

Yeah,
I check permission of notification from the permission handler package.  Actually that was my bad to not check the proper documentation about ios integration (as it is collapsed-expansion-tile initially).
![image](https://github.com/781flyingdutchman/background_downloader/assets/31488481/c17c18e5-7a6e-4e36-bf34-600cd9215c98)

Finally, I modified the pod file as it mentioned in the documentation
![image](https://github.com/781flyingdutchman/background_downloader/assets/31488481/0ff59d81-adb3-4d6d-a7c9-8cbbeafc6f56)


Finally, it works fine!
