### ISSUE TITLE
 Error for taskId 1: Cleartext HTTP traffic to commondatastorage.googleapis.com not permitted

### ISSUE THREAD

**Issue by dghub-founder** [781flyingdutchman/background_downloader#224]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If possible, include logs that capture the issue:
```
logs
```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
Code
```

**Additional context**

**Comment by dghub-founder** [comment]
Tested Android

**Comment by 781flyingdutchman** [comment]
https://www.geeksforgeeks.org/android-cleartext-http-traffic-not-permitted/
