### ISSUE TITLE
Download paused percent is wrong show

### ISSUE THREAD

**Issue by dghub-founder** [781flyingdutchman/background_downloader#225]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If possible, include logs that capture the issue:
```
logs
```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
Code
```

**Additional context**

**Comment by 781flyingdutchman** [comment]
I believe this is the fourth bug you've filed without providing any detail beyond the title.
