### ISSUE TITLE
Warning in compiling project for Android

### ISSUE THREAD

**Issue by jennie-metacast** [781flyingdutchman/background_downloader#228]
**Describe the bug**
This is not a bug per se, but it is a warning compiling for Android. The background_downloader package compiles for android SDK 34, whereas flutter compiles for android SDK 33.

**To Reproduce**
1. I have updated to the latest version of background downloader. In `pubspec.yaml`: `background_downloader: ^8.0.5`
2. My `android/app/build.gradle` follows the recommended convention for setting the SDK version for flutter projects:
```
android {
    compileSdkVersion flutter.compileSdkVersion
...
}
```

**Expected behavior**
Flutter does not yet support Android 34: https://github.com/flutter/flutter/issues/134220
Expected behavior is for the `background_downloader` package to continue to compile on SDK 33 until flutter supports 34.

**Logs**
If possible, include logs that capture the issue:
```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
Warning: The plugin background_downloader requires Android SDK version 34.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /Users/jennie/Metacast/orcapod_app/android/app/build.gradle:
android {
  compileSdkVersion 34
  ...
}
```

**Code**
n/a

**Additional context**
Bump to compile 34 was in this commit: https://github.com/781flyingdutchman/background_downloader/commit/905ea720b55bc7b4f9b8458f615794caf175cd41

**Comment by 781flyingdutchman** [comment]
Interesting, I did not know that! I'll change the CompileSdk entry as you suggest. Does your app compile by overriding the API level to what you set in your app?

**Comment by 781flyingdutchman** [comment]
Actually, according to [this](https://docs.flutter.dev/reference/supported-platforms) API 34 is supported, though not everything works (especially predictive back navigation). Have your tried compiling with 34?

**Comment by 781flyingdutchman** [comment]
Ok, I've played around with this but if I change it to `compileSdkVersion flutter.compileSdkVersion` then teh example app doesn't compile for me, and if I leave it out altogether (also suggested somewhere) it doesn't compile either, so I am going have to leave it as is.
