### ISSUE TITLE
Inquiry about target platform requirements for windows

### ISSUE THREAD

**Issue by akindone** [781flyingdutchman/background_downloader#229]
Hello,

I am interested in using this plugin for a project that targets Windows. Before I proceed, I would like to confirm the minimum supported version of the Windows SDK required by this plugin to ensure compatibility with my development environment and target Windows platforms.

I have checked the CMakeLists.txt and other documentation but could not find specific information regarding the Windows SDK version.
Could you please provide some guidance on the minimum Windows SDK version that is compatible with this plugin? This information will be very helpful for setting up my development environment correctly.

Thank you for your assistance and for the work you've put into this plugin.

Best regards

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out. The Windows version (as well as the MacOS and Linux versions) do not use any native code, just pure Dart (unlike Android and iOS versions that are implemented natively). Therefore, I believe the compatibility requirements are the same as they are for Dart and Flutter itself. 

I have tested the plugin on Windows and it works well, by I have not tested it with a variety of versions, so unfortunately I cannot provide more details.

Hope this helps, let me know if you have any questions.

**Comment by 781flyingdutchman** [comment]
https://docs.flutter.dev/reference/supported-platforms has more details
