### ISSUE TITLE
 MicroSD card support on Android

### ISSUE THREAD

**Issue by azeek** [781flyingdutchman/background_downloader#23]
In the case of background download, there are many downloads of large files. 

Many Android users often expand their capacity with a microSD card. 

I want to set the download path to the micro sd card path, but there is no such method in the current plug-in.

You can think of moving files after downloading by implementing them separately, but since MircroSD Card is a separate physical storage device, the cost is higher than moving files internally.

https://pub.dev/packages/sdcard_path_manager

**Comment by 781flyingdutchman** [comment]
The way to do this is to download a file to - for example - temporary storage and upon completion call moveToSharedStorage with your desired destination. This is a small extra step that avoids polluting the main download API with platform dependent inconsistencies, so worth the tradeoff in my opinion.
