### ISSUE TITLE
How can I download an M3U8 file and subsequently download all its TS segments?

### ISSUE THREAD

**Issue by Hilbert2048** [781flyingdutchman/background_downloader#232]
Could anyone provide suggestions on how to implement a function for downloading an M3U8 file and all associated TS segments? and make it looks like a single download task.

related packages: https://github.com/HiroyukiTamura/flutter_hls_parser.git

**Comment by Tonybobo** [comment]
My guess is that you can use the batch download function. The onProgress callback function can be use to update your state mangement as a indicator. Haven't tried it yet but seems workable

**Comment by markst** [comment]
Likely need to be backed by `AVAssetDownloadURLSession` on iOS

**Comment by Hilbert2048** [comment]
> Likely need to be backed by `AVAssetDownloadURLSession` on iOS

thanks for your information.

**Comment by Hilbert2048** [comment]
After looking over the source code, I can't just add (extends) an M3u8DownloadTask class directly to hit my goal. Instead, we must directly modify the original source code to archive my goat.

Alternatively, we can achieve this by adding an extra downloader layer that builds upon background_downloader.

**Comment by abhishek-m-raj** [comment]
> After looking over the source code, I can't just add (extends) an M3u8DownloadTask class directly to hit my goal. Instead, we must directly modify the original source code to archive my goat.
> 
> Alternatively, we can achieve this by adding an extra downloader layer that builds upon background_downloader.

i did that. https://pub.dev/packages/background_downloader_hls
