### ISSUE TITLE
Plugin does not provide a `kotlin_version` anymore?

### ISSUE THREAD

**Issue by lyio** [781flyingdutchman/background_downloader#233]
**Describe the bug**
After upgrading to v8.0.5 I have noticed that I can only build for Android if I set a `ext.kotlin_version` in my `build.gradle`. However, the recommended way to set these variables is to set them in a `settings.gradle`. But this does not (by design I suppose) propagate to dependencies. So the build fails because `kotlin_version` is undefined. 

```
1: Task failed with an exception.
-----------
* Where:
Build file ~/pub-cache/hosted/pub.dev/background_downloader-8.0.5/android/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':background_downloader'.
> Could not get unknown property 'kotlin_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

In commit 6065d2b48bc205bdeb734eb0846a2f364c7d0880 the version was commented out for some reason.

**Comment by 781flyingdutchman** [comment]
I've added it back in just-published V8.1.0. It's honestly rather confusing what is supposed to go where, and what needs to be hard-coded versus inherited from the app that the plugin is part of, so let's see if this is better!
