### ISSUE TITLE
DownloadTask: How to pass POST request body

### ISSUE THREAD

**Issue by hadi7khan** [781flyingdutchman/background_downloader#235]
I want to download an Image with the url but I need to pass request body to it. e.g data: {"name": image.jpg}, how can i pass that to download task.

`DownloadTask(
        url: 'myurl',
        filename: 'image..jpg',
        directory: 'my/subdir',
        baseDirectory: BaseDirectory.temporary);`

**Comment by 781flyingdutchman** [comment]
Set the `post` field of the `DownloadTask` to the JSON-encoded string representing your map, e.g. using the `jsonEncode` function; `post=jsonEncode({'name': 'image.jpg'})`
