### ISSUE TITLE
change file after downloaded to download dir of ios && sound for notification in android & ios

### ISSUE THREAD

**Issue by MostafaTawfik7** [781flyingdutchman/background_downloader#239]
No sound when notifications appear knowing that I use awasome notifications and how change dir of files after download to download dir in ios 
and thanks

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out. No sound for notifications is as intended: download notifications are not typically important enough to justify adding sound, so they are silent.

I don't quite understand your second question. Can you please elaborate?

**Comment by MostafaTawfik7** [comment]
How to save files in download dir in ios?

**Comment by 781flyingdutchman** [comment]
Ah, you can't. Access to the downloads folder on iOS is highly restricted - only apps like Safari and Chrome have access. I have not found a way to get access in the plugin. You can make files you download visible in other apps - please consult the plugin documentation on how to do that.

Closing this issue, as both questions unfortunately don't have a viable solution.
