### ISSUE TITLE
Incorrect MIME type when moving files to shared storage

### ISSUE THREAD

**Issue by rebaz94** [781flyingdutchman/background_downloader#24]
Hi, 

I've noticed that sometimes the `getMimeType` function in Android returns an incorrect MIME type, which can cause issues when trying to insert media files into a specified destination.  I've modified the code to correctly get the MIME type from the file name, and added an optional mimeType parameter that can be set when moving files to ensure that the correct mime type is used even if not determined easily.

**Comment by rebaz94** [comment]
Please check [this commit](https://github.com/781flyingdutchman/background_downloader/compare/main...rebaz94:background_downloader:main)

**Comment by 781flyingdutchman** [comment]
Implemented in 5.4.3
