### ISSUE TITLE
how to upload tow files in the same endpoint

### ISSUE THREAD

**Issue by AhmedHussein22** [781flyingdutchman/background_downloader#240]
![Capture](https://github.com/781flyingdutchman/background_downloader/assets/63206011/5d737e14-96f5-4644-b62d-6d1f923866b8)

**Comment by 781flyingdutchman** [comment]
Hi, I suggest reading the [Uploads](https://pub.dev/packages/background_downloader#uploads) section of the documentation. Based on your description, I _think_ you should use a MultiUploadTask and use the `files` field, e.g.:
```
task = MultiUploadTask(url: yourUrl, files: [('myVidep', 'myData.txt'), ('value', image.path)];
```
What field names to use depends on your server, so you may have to experiment to get it right. The above sends two files, one under 'myVidep' and one under 'value', similar to what you seemed to want to do.

Let me know if this works.

**Comment by AhmedHussein22** [comment]
> Hi, I suggest reading the [Uploads](https://pub.dev/packages/background_downloader#uploads) section of the documentation. Based on your description, I _think_ you should use a MultiUploadTask and use the `files` field, e.g.:
> 
> ```
> task = MultiUploadTask(url: yourUrl, files: [('myVidep', 'myData.txt'), ('value', image.path)];
> ```
> 
> What field names to use depends on your server, so you may have to experiment to get it right. The above sends two files, one under 'myVidep' and one under 'value', similar to what you seemed to want to do.
> 
> Let me know if this works.

thanks, now it work
