### ISSUE TITLE
numTotal and numFinished showing count as 1 after uploading 4 or more files

### ISSUE THREAD

**Issue by Pranavmaid** [781flyingdutchman/background_downloader#243]
numTotal and numFinished showing count as 1 after uploading 4 or more files

**To Reproduce**
1. code `static Future<void> initialize() async {
    FileDownloader().configure(globalConfig: [
      (Config.requestTimeout, const Duration(minutes: 2)),
    ], androidConfig: [
      (Config.useCacheDir, Config.whenAble),
    ], iOSConfig: [
      (Config.localize, {'Cancel': 'StopIt'}),
    ]).then((result) => debugPrint('Configuration result = $result'));

    await FileDownloader().trackTasks();

    // Registering a callback and configure notifications
    FileDownloader()
        .registerCallbacks(taskNotificationTapCallback:
            (Task task, NotificationType notificationType) {
          debugPrint(
              'Tapped notification $notificationType for taskId ${task.taskId} ${task.directory} d: ${task.baseDirectory}');
        })
        .configureNotificationForGroup(FileDownloader.defaultGroup,
            // For the main download button
            // which uses 'enqueue' and a default group
            running: const TaskNotification('{filename}',
                'File: {filename} - {progress} - speed {networkSpeed} and {timeRemaining} remaining'),
            complete:
                const TaskNotification('{displayName} {filename}', 'Completed'),
            error: const TaskNotification('{filename}', 'Failed'),
            paused: const TaskNotification(
                '{filename}', 'Paused with metadata {metadata}'),
            tapOpensFile: true,
            progressBar: true)
        .configureNotificationForGroup('bunch',
            running: const TaskNotification(
                'Uploaded {numFinished} out of {numTotal}',
                'Progress = {progress}'),
            complete:
                const TaskNotification("Done!", "Loaded {numTotal} files"),
            error: const TaskNotification(
                'Error', '{numFailed}/{numTotal} failed'),
            paused: const TaskNotification(
                '{filename}', 'Paused with metadata {metadata}'),
            progressBar: true,
            tapOpensFile: true,
            groupNotificationId: 'notGroup')
        .configureNotificationForGroup('add_task',
            running: const TaskNotification(
                'Uploaded {numFinished} out of {numTotal}', 'Progress = {progress}'),
            complete: const TaskNotification(
                "Task {displayName} Added successfully",
                "" // "Uploaded {numFinished} out of {numTotal} files"
                ),
            error: const TaskNotification(
                'Error', '{numFailed}/{numTotal} failed'),
            paused: const TaskNotification(
                '{filename}', 'Task {displayName} Upload Paused.'),
            progressBar: true,
            tapOpensFile: true,
            groupNotificationId: 'notGroup')
        .configureNotificationForGroup('add_issue',
            running: const TaskNotification(
                'Uploaded {numFinished} out of {numTotal}',
                'Progress = {progress}'),
            complete:
                const TaskNotification("Issue {displayName} Added successfully", ""

                    ///"Uploaded {numFinished} out of {numTotal} files"
                    ),
            error: const TaskNotification('Error', '{numFailed}/{numTotal} failed'),
            paused: const TaskNotification('{filename}', 'Issue {displayName} Upload Paused'),
            progressBar: true,
            tapOpensFile: true,
            groupNotificationId: 'notGroup')
        .configureNotificationForGroup('mark_complete', running: const TaskNotification('Uploaded {numFinished} out of {numTotal}', 'Progress = {progress}'), complete: const TaskNotification("Task {displayName} Mark Complete successfully", "Uploaded {numFinished} out of {numTotal} files"), error: const TaskNotification('Error', '{numFailed}/{numTotal} failed'), paused: const TaskNotification('{filename}', 'Paused with metadata {metadata}'), progressBar: true, tapOpensFile: true, groupNotificationId: 'notGroup')
        .configureNotification(
            // for the 'Download & Open' dog picture
            // which uses 'download' which is not the .defaultGroup
            // but the .await group so won't use the above config
            // progressBar: true,
            progressBar: true,
            // complete: const TaskNotification(
            //     '{filename}', 'complete'),
            running: const TaskNotification('{filename}', 'File: {filename} - {progress} - speed {networkSpeed} and {timeRemaining} remaining'),
            complete: const TaskNotification('{displayName} {filename}', 'Completed'),
            error: const TaskNotification('{filename}', 'Failed'),
            paused: const TaskNotification('{filename}', 'Paused with metadata {metadata}'),
            tapOpensFile: true); // dog can also open directly from tap`
2. `String id =
            "UploadTask-${payload["task_name"]!.replaceAll(" ", "")}-${DateTime.now().millisecondsSinceEpoch}";
        var filesLT = filesUpload
            .map((e) => ("task_files", e["path"]))
            .toList();

        var task = MultiUploadTask(
          taskId: id,
          url: "${ServerRoutes.baseUrl}${ServerRoutes.markTaskComplete}",
          // filename: selectedFiles.files[i].name,
          headers: {
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'x-access-token': accessToken
          },
          fields: payload,
          group: "mark_complete",
          // fileField: "task_files",
          // directory: selectedFiles.files[i].path!
          //     .replaceAll("/${selectedFiles.files[i].name}", ""),
          baseDirectory: BaseDirectory.root,
          displayName: payload["task_name"]!,
          updates:
              Updates.statusAndProgress, // request status and progress updates
          requiresWiFi: false,
          retries: 5,
          priority: 10,
          files: filesLT,
        );
        // Start download, and wait for result. Show progress and status changes
        // while downloading
        await FileDownloader().enqueue(
          task,
        );`

image 1: selected files
![WhatsApp Image 2024-02-09 at 10 47 24 PM](https://github.com/781flyingdutchman/background_downloader/assets/64965878/8514f73e-71b2-469a-987f-1e67dce5c353)

image 2: Notification recived after task completed
![WhatsApp Image 2024-02-09 at 10 48 13 PM](https://github.com/781flyingdutchman/background_downloader/assets/64965878/c74a89d4-436a-4ab6-a4ea-7eeb86899543)

**Comment by 781flyingdutchman** [comment]
Hi, if I understand it correctly yu are uploading 4 files as one `MultiUploadTask`, correct? If so, this is working as intended, as the notification counter counts tasks, and a single `MultiUploadTask` is considered one task/file. This is  because in most cases, the multiple files you're uploading in one go are related (e.g. a file and a thumbnail JPEG) and are therefore considered one operation.  I appreciate this may not be what you want in this specific scenario, but it's the common use case. If you want to count each file, I suggest you schedule them as separate tasks (that also improves resilience, as a single file upload failure then does not require all files to be re-uploaded, as is the case with your current code).
