### ISSUE TITLE
Get taskProgress and TaskStatus in one Function

### ISSUE THREAD

**Issue by Nahid-mk** [781flyingdutchman/background_downloader#244]
This package is amazing. Background downloader has an option to register callbacks. Where I can register 3 functions. taskProgressCallback, traskStatusCallback, taskNotificationTapCallback. Now is it possible to get taskProgress and taskStatus in one function? 

it would be very helpful. because by using that function I will be able to trace my progress by task ID. I will be to change progress by task id

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out. The most Dart-like way to obtain updates is not by registering a callback but by listening to the `updates` stream, which sends a `TaskUpdate` (which is the superclass and can be a `TaskStatusUpdate` or a `TaskProgressUpdate`) to the listener, like this:
```
FileDownloader().updates.listen((TaskUpdate update) {
  final taskId = update.task.taskId;
  switch (update) {
    case TaskStatusUpdate():
      print('New status for $taskId is ${update.status}');
      
    case TaskProgressUpdate():
      print('Progress for $taskId is ${update.progress}');
  }
});
```

Using a listener has the added  benefit that it ensures you only listen to updates in one place, ensuring that you don't miss any updates.

If you want to use callbacks, then you can accomplish something similar like this:
```
/// your single, unified callback function
void processUpdate(TaskUpdate update) {
  final taskId = update.task.taskId;
  switch (update) {
    case TaskStatusUpdate():
      print('New status for $taskId is ${update.status}');

    case TaskProgressUpdate():
      print('Progress for $taskId is ${update.progress}');
  }
}

// register this unified callback for both status and progress updates
FileDownloader().registerCallbacks(
    taskStatusCallback: (update) => processUpdate(update),
    taskProgressCallback: (update) => processUpdate(update));
```

**Comment by Nahid-mk** [comment]
Thanks a lot.
