### ISSUE TITLE
If there is any download task ongoing, and User force kill the App. User behavior for both platform(Android/iOS) is different.

### ISSUE THREAD

**Issue by kcs-govindtank** [781flyingdutchman/background_downloader#246]
**Describe the bug**
So While Testing with latest version 8.2.0 in the app, if there is any download task is enqueued and it started downloading, meanwhile if user force-kill the app (by removing the app from recent apps), that download task stops (which should be correct required behavior), but when app is again started by user,
 **Android Case**
 that same download task again start downloading from where it left at last time, and finishes the download in the **Android Device**.
**iOS Case**
in iOS, when app killed from recent apps, it stops the downloading, and once again when user starts the app, that download task not started where it left previously like Android. 

**To Reproduce**
**Android**  Steps to reproduce the behavior:
1. Start Downloading Any Track
2. When that track is downloading, force kill the app from the recent apps
3. If you have configured the notification, sometime it removes the app, but sometime the notification for the download task not removed from the notification bar.
4. Also, when user restart the app, the download task will keep on running and finishes its work.

**iOS**  Steps to reproduce the behavior:
1. Start Downloading Any Track
2. When that track is downloading, force kill the app from recent apps
3. If you have configured the notification, the notification are not being removed and it will show "running state: downloading" in notification bar.
4. Also, when user restart the app, the download task will stop where it previously was. (Example; if before app kill, the download was completed 40%, then after restart it will show the last 40% progress, but won't auto run again like android.

**Expected behavior**
If there is any download task is ongoing, and user kills the app, it should stop the download and remove notification for that download as well. and when user again open the app it should have "Retry" status or waitingToRetry status, so user can again able to start the download either from last progress saved or from fresh 0% download progress.

**Code**
```
There are too many code files so won't able to paste the whole code. but in summary, I track all the running task from start of the main.dart file.

  **await fileDownloader.trackTasks();**
  
  For any download task, I add them in queue using
  
  **await fileDownloader.enqueue(downloadTask);**
  
  then in my download screen, I am keep updating the status and progress of any download task which are available in the 
  
  **fileDownloader.database.allRecords();**
  
 using streamContorller. so overall there is single centric screen in the app which tracks all the downloads of the app. 
  
  
**Additional context**
I have tried manually to stop (running) downloadTask using 

  **    if(a.status==TaskStatus.running){
await fileDownloader.cancelTaskWithId(a.taskId);  
}
**

but there is issue detecting app kill due to limitation of flutter described here [https://github.com/flutter/flutter/issues/124945#issuecomment-1514159238](url) 

so in case if i had got the success here,  So Please provide some update on this. or provide some feature/flag where we can control the changes based on requirement when downloadTask is halted and restarted by app kill.

**Comment by 781flyingdutchman** [comment]
Thanks for raising this. Unfortunately, killing the app is handled entirely by the OS - the app is not notified of this happening, and can therefore not "intercept" this to act on it. As a result, the behavior is going to differ between platforms and and I don't believe there is anything I can (or should) do about this. It is generally better to let the OS manage apps in the background, instead of force killing apps, to avoid errant behavior.

I'm going to close this issue as there is no remedy.
