### ISSUE TITLE
Getting build fail error

### ISSUE THREAD

**Issue by Abdullah-Mazumder** [781flyingdutchman/background_downloader#248]
![Screenshot 2024-02-21 114834](https://github.com/781flyingdutchman/background_downloader/assets/93310710/9ad764fe-5e19-48ba-be15-a10d371126bf)

I am getting this error.

**Comment by 781flyingdutchman** [comment]
You need to use Kotlin version 1.9.20. Add `ext.kotlin_version = '1.9.20'` in the `buildScript` section of `build.gradle`. From your log it looks like you are using Kotlin 1.7

**Comment by Abdullah-Mazumder** [comment]
![Screenshot 2024-02-21 130119](https://github.com/781flyingdutchman/background_downloader/assets/93310710/21bf4329-c40d-4084-89ed-294ce64a433b)
![Screenshot 2024-02-21 130252](https://github.com/781flyingdutchman/background_downloader/assets/93310710/4a709d93-bd81-4c2f-8bde-34cdbf0ea459)
here it is showing completed 7 out of 7. but when i go to that directory then there is no audio file

**Comment by 781flyingdutchman** [comment]
It looks like the `directory` you provide is an absolute path. Please read the [documentation](https://pub.dev/packages/background_downloader#specifying-the-location-of-the-file-to-download-or-upload) on how to specify the location of the file to download.

**Comment by Abdullah-Mazumder** [comment]
how can i download files in external storage like in sd card.

/storage/emulated/0/Android/data/com.example.alquran_flutter/files/audio

i have to download files in this directory

**Comment by Abdullah-Mazumder** [comment]
yeah when i use basdirectory.root then it is working

**Comment by 781flyingdutchman** [comment]
Read the docs
