### ISSUE TITLE
Is a binary PUT without headers possible?

### ISSUE THREAD

**Issue by matgallacher** [781flyingdutchman/background_downloader#251]
Trying to PUT a jpeg to a Firebase storage URL.  The upload is working fine but when I open the file I can see the headers embedded.  Is it possible to create a Task that does a raw PUT?

This is code I'm using for the upload

```
   FileDownloader().upload(
      UploadTask(
          taskId: snapshot.key,
          url: val['url'],
          filename: basename(file.path),
          httpRequestMethod: 'PUT',
          baseDirectory: BaseDirectory.applicationSupport),
      onStatus: (status) {
        // doing some things to upate the status which is all working nicely
      },
    );
```

This is a sample upload, if you open the file you can see the following embedded. 

```
-------background_downloader-akjhfw281onqciyhnIk
Content-Disposition: form-data; name="file"; filename="scaled_c006083b-ca62-4245-91d4-2c65ca0ccdcc1648361797339208015.jpg"
Content-Type: image/jpeg
```

![sample_uploaded_file](https://github.com/781flyingdutchman/background_downloader/assets/12884742/5735070a-2786-474d-a2a1-8537abab1404)

Any assistance or advice would be greatly appreciated

Thank you!

**Comment by 781flyingdutchman** [comment]
The way you've set it up you are uploading using the multipart format. Remove the `httpRequestMethod` argument and add `post: 'binary'` to make the uploader use the binary upload format (see the Uploading section of the docs). I think that solves it - let me know.

**Comment by 781flyingdutchman** [comment]
Sorry, correction: don't remove the `httpRequestMethod` argument if indeed you want PUT, as it defaults to POST.

**Comment by matgallacher** [comment]
This is perfect, works like a charm, thank you!
