### ISSUE TITLE
how to prevent download automatically when restart app

### ISSUE THREAD

**Issue by Tiny1213** [781flyingdutchman/background_downloader#252]
After I add a download task and then kill the app. When I restart the app, the added task continues to download automatically. I don't want it to download automatically. What should I do?

**Comment by 781flyingdutchman** [comment]
See issue #246 : the app cannot distinguish between a start from a normal end versus a start from being killed. The only way to prevent donwloads from restrating is to kill all downloads when you start your app (e.g. using `FileDownloader().reset()`) but be aware that this then will happen also when the users restarts the app normally, which will lead to strange behavior.
