### ISSUE TITLE
Failed to build on Android, looking for kotlin-serialization-compiler-plugin-embeddable

### ISSUE THREAD

**Issue by flushr** [781flyingdutchman/background_downloader#253]
**Describe the bug**
Failed to build on Android side, it's looking for ```kotlin-serialization-compiler-plugin-embeddable``` but could not be found. No problem found on iOS side.

I can build and run the example project that come with the package, but not if used on another project.

**To Reproduce**
1. Create a new Flutter project
2. Add ```background_downloader: ^8.2.1``` dependency into ```pubspec.yml```
3. Do pub get 
4. Change ```minimumSdkVersion``` to ```21``` in ```build.gradle```
5. Add Internet and storage permission into ```AndroidManifest.xml```
6. Run AVD (Android emulator)
7. Try to run the project

**Expected behavior**
The project is successfully build and run into the emulator.

**Logs**
Failed build logs:
```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_downloader:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':background_downloader:compileDebugKotlin'.
   > Could not resolve all files for configuration ':background_downloader:kotlinCompilerPluginClasspathDebug'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
        Required by:
            project :background_downloader

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Error: Gradle task assembleDebug failed with exit code 1
```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
No code added
```

**Additional context**
Android Studio Hedgehog 2023.1.1 Patch 2

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by 781flyingdutchman** [comment]
You need to use Kotlin version 1.9.20. Add ext.kotlin_version = '1.9.20' in the buildScript section of build.gradle. From your log it looks like you are using Kotlin 1.7

**Comment by flushr** [comment]
Thank you for your prompt response.

I'm using the default that's coming with create flutter project, and I've added the version that you mentioned before to ```android/app/build.gradle```, but still getting the same error, below are the contents:

```
buildscript {
    ext.kotlin_version = '1.9.20'
}

plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.background_downloader_test"
    compileSdk flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.background_downloader_test"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {}
```

**Comment by 781flyingdutchman** [comment]
I think you've modified the wrong build.gradle. The line needs to be in the `projectName/android/build.gradle`, not on the `app` one.

**Comment by flushr** [comment]
I'll try to modify the other ```build.gradle``` file. Thank you.

**Comment by flushr** [comment]
Hi @781flyingdutchman,

Wanted to update, after I modify ```android/build.gradle```, sadly the error is still there.

Here are the contents of the ```android/build.gradle``` file:

```
buildscript {
    ext.kotlin_version = '1.9.20'
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

**Comment by 781flyingdutchman** [comment]
Is it still referring to Kotlin 1.7? There are many ways to set the Kotlin compiler on Android - please Google around to see how you can make your specific project use version 1.9.20? Based on your initial error log, that really is the issue.

**Comment by bysonstudio** [comment]
version of org.jetbrains.kotlin.android moved to settings.gradle

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
//    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
    id "org.jetbrains.kotlin.android" version "1.9.20" apply false
}

only change 1.7.10 -> 1.9.20

**Comment by bysonstudio** [comment]
version of org.jetbrains.kotlin.android moved to settings.gradle

plugins {
id "dev.flutter.flutter-plugin-loader" version "1.0.0"
id "com.android.application" version "7.3.0" apply false
// id "org.jetbrains.kotlin.android" version "1.7.10" apply false
id "org.jetbrains.kotlin.android" version "1.9.20" apply false
}

just change 1.7.10 -> 1.9.20

**Comment by 781flyingdutchman** [comment]
V8.4.0 uses the new declarative way to apply Gradle 🔌 plugins on Android, and this may also help solve the problem.
