### ISSUE TITLE
IOS Download file error :[Downloader] Failed to move file from 

### ISSUE THREAD

**Issue by yudehai0204** [781flyingdutchman/background_downloader#254]
**Describe the bug**
Ios Download file error " cannot move file 

**Logs**
If possible, include logs that capture the issue:
```
[Downloader] Failed to move file from /var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/c*/CFNetworkDownload_7ESYDB.tmp to /var/mobile/Containers/Data/Application/BBA5867F-2747-4016-B337-7FEC217862A0/Documents/video.mp4:
```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
    final task = DownloadTask(
            url: fileUrl,
            filename: filename,
            directory: 'gameFile',
            updates: Updates.statusAndProgress, // request status and progress updates
            requiresWiFi: false,
            retries: 5,
            allowPause: false,
            );
```

Do I need to configure any permissions?
Already added background fetch

**Comment by yudehai0204** [comment]
downloaer version:  8.0.3

**Comment by yudehai0204** [comment]
Sorry,I missed the reason :  
[Downloader] Failed to move file from /var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/c*/CFNetworkDownload_zEaNja.tmp to /var/mobile/Containers/Data/Application/B54A7ABA-63C0-44FB-B97D-6D4491D28835/Documents/video.mp4: “CFNetworkDownload_zEaNja.tmp” couldn’t be moved because you don’t have permission to access “Documents”.

**Comment by yudehai0204** [comment]
<img width="402" alt="694cda0207786272feaac98ca3ab166" src="https://github.com/781flyingdutchman/background_downloader/assets/10924643/2700e673-1305-4f6c-a22c-e6182d2199e5">
<img width="772" alt="4579b0a3a53c7ce684a309ee56e3062" src="https://github.com/781flyingdutchman/background_downloader/assets/10924643/91725116-f59b-4a47-a29e-cab1252aeece">
 xcode project setting

**Comment by yudehai0204** [comment]
This problem does not occur on the simulator
SimulatorInfo: iphone14pro - ios16.2
DeviceInfo : iphone 6s Plus - ios 15.7.6

**Comment by yudehai0204** [comment]
@781flyingdutchman  Hello, do I need to configure any permissions? If you use it on a ios device。

**Comment by 781flyingdutchman** [comment]
Can you answer the remaining 4 questions above?

**Comment by yudehai0204** [comment]
@781flyingdutchman  Sorry,This is the error related information:
1.error logs :
`lutter: Download::(true)  Status: TaskStatus.running
flutter: Download::(true)  Progress: 0.0
flutter: Download::(true)  Progress: 0.020712943468388784
flutter: Download::(true)  Progress: 0.041429107546393354
flutter: Download::(true)  Progress: 0.0619415586675333
flutter: Download::(true)  Progress: 0.08204177175785271
flutter: Download::(true)  Progress: 0.10214358888720255
flutter: Download::(true)  Progress: 0.12306506996110218
flutter: Download::(true)  Progress: 0.14337220408634707
flutter: Download::(true)  Progress: 0.16408836816435166
flutter: Download::(true)  Progress: 0.18419018529370149
flutter: Download::(true)  Progress: 0.20531698336349616
flutter: Download::(true)  Progress: 0.2262384644373958
flutter: Download::(true)  Progress: 0.2502380964106907
flutter: Download::(true)  Progress: 0.2709542604886953
flutter: Download::(true)  Progress: 0.2943379414743051
flutter: Download::(true)  Progress: 0.31505410555230967
flutter: Download::(true)  Progress: 0.3357718736693447
flutter: Download::(true)  Progress: 0.3562827207514542
flutter: Download::(true)  Progress: 0.37638453788080406
flutter: Download::(true)  Progress: 0.3971007019588086
flutter: Download::(true)  Progress: 0.4180221830327082
flutter: Download::(true)  Progress: 0.43812400016205805
flutter: Download::(true)  Progress: 0.45822581729140793
flutter: Download::(true)  Progress: 0.4785329514166528
flutter: Download::(true)  Progress: 0.4986331645069722
flutter: Download::(true)  Progress: 0.5193509326240072
flutter: Download::(true)  Progress: 0.5404777306938019
flutter: Download::(true)  Progress: 0.5611938947718065
flutter: Download::(true)  Progress: 0.5823206928416012
flutter: Download::(true)  Progress: 0.6024241140099814
flutter: Download::(true)  Progress: 0.6235493080407456
flutter: Download::(true)  Progress: 0.6442670761577807
flutter: Download::(true)  Progress: 0.6647779232398902
flutter: Download::(true)  Progress: 0.6852903743610301
flutter: Download::(true)  Progress: 0.7066224894267198
flutter: Download::(true)  Progress: 0.7269280195129343
flutter: Download::(true)  Progress: 0.7476457876299692
flutter: Download::(true)  Progress: 0.7683619517079738
flutter: Download::(true)  Progress: 0.7888727987900834
flutter: Download::(true)  Progress: 0.8093852499112233
flutter: Download::(true)  Progress: 0.830306730985123
flutter: Download::(true)  Progress: 0.8510244991021579
flutter: Download::(true)  Progress: 0.8713300291883724
flutter: Download::(true)  Progress: 0.8916371633136173
flutter: Download::(true)  Progress: 0.9123533273916219
flutter: Download::(true)  Progress: 0.9328657785127619
flutter: Download::(true)  Progress: 0.9539925765825565
flutter: Download::(true)  Progress: 0.9749140576564561
flutter: Download::(true)  Progress: 0.9956318257734911
[Downloader] Failed to move file from /var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/c*/CFNetworkDownload_deHJ8y.tmp to /var/mobile/Containers/Data/Application/01D5E8C8-61C0-4CFD-9496-9150BFE7652F/Documents/gameFile/video.mp4: “CFNetworkDownload_deHJ8y.tmp” couldn’t be moved because you don’t have permission to access “gameFile”.
flutter: Download::(true)  Status: TaskStatus.waitingToRetry
flutter: Download::(true)  Progress: -4.0`
2 and 3. download code:
<img width="748" alt="0e89f766eae7be9c5e87011acb7e2eb" src="https://github.com/781flyingdutchman/background_downloader/assets/10924643/1702588a-0613-4384-a5b7-7d187f2d6188">
4. I'm not trying move the file , just  use api download it.
5. the device has sufficient sotrage. you mean is  cache storage space of app?

**Comment by yudehai0204** [comment]
I have two iphone  , and the other one(iphone14 ios16.4) works;

**Comment by 781flyingdutchman** [comment]
Very helpful. I think I found the issue, working on a fix. I don't have access to an iPhone running iOS 15, so can you help test this when I have the fix?

**Comment by 781flyingdutchman** [comment]
Can you test the current `dev` branch to see if this fixes your problem? Change your pubspec.yaml to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: dev
```

Please let me know if it works, and if so I'll publish as the next version (includes a few unrelated changes).

**Comment by yudehai0204** [comment]
@781flyingdutchman  Sorry,My device has xcode14 installed at most and may not support some syntax.
`Swift Compiler Error (Xcode): Expected initial value after '='
/Users/admin/.pub-cache/git/background_downloader-2d9256af6bb57f20e005f1ee9a2d3bd1da92dc56/ios/Classes/ParallelDownloader.swift:404:39

Swift Compiler Error (Xcode): Consecutive statements on a line must be separated by ';'
/Users/admin/.pub-cache/git/background_downloader-2d9256af6bb57f20e005f1ee9a2d3bd1da92dc56/ios/Classes/ParallelDownloader.swift:404:38

Swift Compiler Error (Xcode): 'nil' requires a contextual type
/Users/admin/.pub-cache/git/background_downloader-2d9256af6bb57f20e005f1ee9a2d3bd1da92dc56/ios/Classes/ParallelDownloader.swift:412:16`

**Comment by yudehai0204** [comment]
After modifying the code, it works, but the problem persists;
change code :
`/// Finish the [ParallelDownloadTask] by posting a statusUpdate and clearning up
    private func finishTask(status: TaskStatus) {
        let taskId = parentTask.taskId
        let mimeType = BDPlugin.mimeTypes[taskId]
        let charSet = BDPlugin.charSets[taskId]
        var responseStatusCode: Int? = nil
        switch status {
            case .complete:
            responseStatusCode = initialResponseStatusCode
            break;
            case .notFound:
            responseStatusCode = 404
            break;
            default:
            responseStatusCode = nil
            break;
        }
        processStatusUpdate(task: parentTask, status: status, taskException: taskException, responseBody: responseBody, responseHeaders: responseHeaders, responseStatusCode: responseStatusCode, mimeType: mimeType, charSet: charSet)
        BDPlugin.mimeTypes.removeValue(forKey: taskId)
        BDPlugin.charSets.removeValue(forKey: taskId)
        BDPlugin.tasksWithSuggestedFilename.removeValue(forKey: taskId)
        ParallelDownloader.downloads.removeValue(forKey: taskId)
    }`

error log :
[Downloader] Failed to move file from /var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/c*/CFNetworkDownload_UCnwe4.tmp to /var/mobile/Containers/Data/Application/921E8B15-1F09-4CAE-BEA7-C3E0C343B1C1/Documents/gameFile/video.mp4: “CFNetworkDownload_UCnwe4.tmp” couldn’t be moved because you don’t have permission to access “gameFile”.

**Comment by yudehai0204** [comment]
After modifying the code, it works, but the problem persists
code:


    private func finishTask(status: TaskStatus) {
        let taskId = parentTask.taskId
        let mimeType = BDPlugin.mimeTypes[taskId]
        let charSet = BDPlugin.charSets[taskId]
        var responseStatusCode: Int? = nil
        switch status {
            case .complete:
            responseStatusCode = initialResponseStatusCode
            break;
            case .notFound:
            responseStatusCode = 404
            break;
            default:
            responseStatusCode = nil
            break;
        }
        processStatusUpdate(task: parentTask, status: status, taskException: taskException, responseBody: responseBody, responseHeaders: responseHeaders, responseStatusCode: responseStatusCode, mimeType: mimeType, charSet: charSet)
        BDPlugin.mimeTypes.removeValue(forKey: taskId)
        BDPlugin.charSets.removeValue(forKey: taskId)
        BDPlugin.tasksWithSuggestedFilename.removeValue(forKey: taskId)
        ParallelDownloader.downloads.removeValue(forKey: taskId)
    }

err logs:
[Downloader] Failed to move file from /var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/c*/CFNetworkDownload_UCnwe4.tmp to /var/mobile/Containers/Data/Application/921E8B15-1F09-4CAE-BEA7-C3E0C343B1C1/Documents/gameFile/video.mp4: “CFNetworkDownload_UCnwe4.tmp” couldn’t be moved because you don’t have permission to access “gameFile”.

**Comment by 781flyingdutchman** [comment]
Thanks for sharing. I'll change the code as you have, but now I do wonder if the issue is caused by your use of XCode 14 (and an older Swift version). Can you try when you compile using XCode 15?

**Comment by yudehai0204** [comment]
Sorry,xcode15 is not supported on my device.
But I used UrlSession to download the test myself and it was fine
code:
func  testFileDown(){
    
        tagPrint(tag: "test", items: "StartDown")
        let fileURLString = "https://ssp.myqcloud.com/ssp/202111/index.mp4"
        let fileURL = URL(string: fileURLString)!

        let downloadTask = URLSession.shared.downloadTask(with: fileURL) { location, response, error in
            guard let location = location else {
                if let error = error {
                    tagPrint(tag: "test", items: "Download failed with error: \(error.localizedDescription)")
                }
                return
            }
            
            tagPrint(tag: "test", items: "locationPath \(location.absoluteString)")
            let fileManager = FileManager.default
            let documentDirectoryURL = try! fileManager.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
            let destinationURL = documentDirectoryURL.appendingPathComponent("download.mp4")
            
            do {
                try fileManager.moveItem(at: location, to: destinationURL)
                tagPrint(tag: "test", items: "Download completed. File saved at: \(destinationURL.absoluteString)")
            } catch {
                tagPrint(tag: "test", items: "Failed to move downloaded file: \(error.localizedDescription)")
            }
        }

        downloadTask.resume()
    }

log:
(DZ) test ::  ["StartDown"]
(DZ) test ::  ["locationPath file:///private/var/mobile/Containers/Data/Application/1D82C1E1-430A-434A-8999-EB33D34996D7/tmp/CFNetworkDownload_yXtzAp.tmp"]
(DZ) test ::  ["Download completed. File saved at: file:///var/mobile/Containers/Data/Application/1D82C1E1-430A-434A-8999-EB33D34996D7/Documents/download.mp4"]

the different is  the tmp file addr; use backgrounddownloader the tmp is in (y/Caches/com.apple.nsurlsessiond/Downloads )

**Comment by 781flyingdutchman** [comment]
I'm really puzzled by this. Have you tried running the example app from the github repo of the plugin? It also downloads a simple file to the documents directory (just like you are doing) so let's see if that works.

**Comment by yudehai0204** [comment]
demo has the same error:
_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundDownloadTask <D241069C-875E-4880-8C74-251D5470DC92>.<4>",
    "LocalDownloadTask <D241069C-875E-4880-8C74-251D5470DC92>.<4>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLStringKey=https://storage.googleapis.com/approachcharts/test/5MB-test.ZIP, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}
[Downloader] Error for taskId 1994190954: An SSL error has occurred and a secure connection to the server cannot be made.
dnssd_clientstub read_all(15) DEFUNCT
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(154)] Could not register as server for FlutterDartVMServicePublisher. Check your network settings and relaunch the application.
dnssd_clientstub read_all(17) DEFUNCT
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(154)] Could not register as server for FlutterDartVMServicePublisher. Check your network settings and relaunch the application.
[Downloader] Starting task with id 1743765812
[Downloader] Failed to move file from /var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/c*/CFNetworkDownload_ZBZCiM.tmp to /var/mobile/Containers/Data/Application/E61464B1-EDFD-4587-9752-443BC59BDC88/Documents/my/directory/zipfile.zip: “CFNetworkDownload_ZBZCiM.tmp” couldn’t be moved because you don’t have permission to access “directory”.

**Comment by yudehai0204** [comment]
<img width="629" alt="51a7d58ad9e255f0079a05fcaf5e615" src="https://github.com/781flyingdutchman/background_downloader/assets/10924643/a1131d47-0563-49e7-953b-48434729fba8">
use .default  ; work on ios15 device。 maybe permission problem

**Comment by yudehai0204** [comment]
and on ios15, the  second boot will crash

Incident Identifier: 47EDB8BF-6EF8-4486-8B8C-A68004F5865E
CrashReporter Key:   764334819f6c3c4174a833ad27fae42481825b20
Hardware Model:      iPhone9,2
Process:             Runner [1512]
Path:                /private/var/containers/Bundle/Application/632391BF-E749-4BCB-AFCB-A4A10756D889/Runner.app/Runner
Identifier:          com.bbflight.fileDownloaderExample
Version:             2.0.0 (2.0.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.bbflight.fileDownloaderExample [746]

Date/Time:           2024-03-11 15:55:55.4021 +0800
Launch Time:         2024-03-11 15:55:55.3172 +0800
OS Version:          iPhone OS 15.7.3 (19H307)
Release Type:        User
Baseband Version:    9.61.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes: 0x0000000000000001, 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4296245248
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   100138000-100140000 [   32K] r-x/r-x SM=COW  ...er.app/Runner
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [1512]

Triggered by Thread:  0

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libswiftCore.dylib            	       0x1857ceff0 swift_getObjectType + 36
1   background_downloader         	       0x1003b5e88 static BDPlugin.register(with:) + 108
2   background_downloader         	       0x1003b5e88 static BDPlugin.register(with:) + 108
3   background_downloader         	       0x1003b60f0 @objc static BDPlugin.register(with:) + 56
4   background_downloader         	       0x1003b2b10 +[BackgroundDownloaderPlugin registerWithRegistrar:] + 72
5   Runner                        	       0x10013ea7c +[GeneratedPluginRegistrant registerWithRegistry:] + 112
6   Runner                        	       0x10013ec1c AppDelegate.application(_:didFinishLaunchingWithOptions:) + 180
7   Runner                        	       0x10013eee4 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) + 188
8   UIKitCore                     	       0x18332d5c4 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 336
9   UIKitCore                     	       0x183501d98 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3508
10  UIKitCore                     	       0x1834eb4bc -[UIApplication _runWithMainScene:transitionContext:completion:] + 1176
11  UIKitCore                     	       0x1833592d4 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 148
12  UIKitCore                     	       0x1831bfff8 _UIScenePerformActionsWithLifecycleActionMask + 96
13  UIKitCore                     	       0x1832e2a2c __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 188
14  UIKitCore                     	       0x1833f8008 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 240
15  UIKitCore                     	       0x183620434 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 744
16  UIKitCore                     	       0x1835b0174 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 336
17  UIKitCore                     	       0x1831c0d44 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 188
18  UIKitCore                     	       0x18327c934 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 812
19  UIKitCore                     	       0x1831c2ad4 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 248
20  UIKitCore                     	       0x1832a7184 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 356
21  UIKitCore                     	       0x1836fcf38 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.578 + 772
22  UIKitCore                     	       0x1831f077c -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
23  UIKitCore                     	       0x18323251c -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 264
24  UIKitCore                     	       0x18335dd3c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 560
25  UIKitCore                     	       0x1832a55a0 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 360
26  FrontBoardServices            	       0x191f00c50 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 412
27  FrontBoardServices            	       0x191f22f98 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.180 + 100
28  FrontBoardServices            	       0x191ee3bdc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
29  FrontBoardServices            	       0x191ee4fd4 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 312
30  libdispatch.dylib             	       0x180a3c094 _dispatch_client_callout + 16
31  libdispatch.dylib             	       0x1809df150 _dispatch_block_invoke_direct$VARIANT$mp + 220
32  FrontBoardServices            	       0x191ee52ac __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
33  FrontBoardServices            	       0x191ee47c0 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 176
34  FrontBoardServices            	       0x191ee8960 -[FBSSerialQueue _performNextFromRunLoopSource] + 24
35  CoreFoundation                	       0x180d9c468 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
36  CoreFoundation                	       0x180dac598 __CFRunLoopDoSource0 + 204
37  CoreFoundation                	       0x180cee774 __CFRunLoopDoSources0 + 256
38  CoreFoundation                	       0x180cf3e48 __CFRunLoopRun + 768
39  CoreFoundation                	       0x180d07194 CFRunLoopRunSpecific + 572
40  GraphicsServices              	       0x1a183a988 GSEventRunModal + 160
41  UIKitCore                     	       0x183509a88 -[UIApplication _run] + 1080
42  UIKitCore                     	       0x1832a2fc8 UIApplicationMain + 336
43  Runner                        	       0x10013f05c main + 64
44  dyld                          	       0x1003204d0 start + 444

Thread 1:
0   libsystem_pthread.dylib       	       0x1dc0e0934 start_wqthread + 0

Thread 2 name:   Dispatch queue: com.apple.UIKit.KeyboardManagement
Thread 2:
0   libsystem_kernel.dylib        	       0x1bb64b688 __ulock_wait + 8
1   libdispatch.dylib             	       0x1809dcd60 _dlock_wait + 52
2   libdispatch.dylib             	       0x1809dcb4c _dispatch_thread_event_wait_slow$VARIANT$mp + 52
3   libdispatch.dylib             	       0x1809e9bfc __DISPATCH_WAIT_FOR_QUEUE__ + 320
4   libdispatch.dylib             	       0x1809e9820 _dispatch_sync_f_slow + 136
5   UIKitCore                     	       0x183373ac0 __37-[_UIRemoteKeyboards startConnection]_block_invoke_3 + 112
6   CoreFoundation                	       0x180d09d10 __invoking___ + 144
7   CoreFoundation                	       0x180d25df8 -[NSInvocation invoke] + 300
8   Foundation                    	       0x1824304d8 __NSXPCCONNECTION_IS_CALLING_OUT_TO_REPLY_BLOCK__ + 20
9   Foundation                    	       0x182450328 -[NSXPCConnection _decodeAndInvokeReplyBlockWithEvent:sequence:replyInfo:] + 568
10  Foundation                    	       0x18242c2d8 __88-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]_block_invoke_3 + 208
11  libxpc.dylib                  	       0x1dc1172ec _xpc_connection_reply_callout + 60
12  libxpc.dylib                  	       0x1dc10b568 _xpc_connection_call_reply_async + 76
13  libdispatch.dylib             	       0x180a3c10c _dispatch_client_callout3 + 16
14  libdispatch.dylib             	       0x1809f5840 _dispatch_mach_msg_async_reply_invoke$VARIANT$mp + 344
15  libdispatch.dylib             	       0x1809e2610 _dispatch_lane_serial_drain$VARIANT$mp + 344
16  libdispatch.dylib             	       0x1809e3224 _dispatch_lane_invoke$VARIANT$mp + 456
17  libdispatch.dylib             	       0x1809ecec8 _dispatch_workloop_worker_thread + 632
18  libsystem_pthread.dylib       	       0x1dc0e0e10 _pthread_wqthread + 284
19  libsystem_pthread.dylib       	       0x1dc0e093c start_wqthread + 8

Thread 3 name:  com.apple.uikit.eventfetch-thread
Thread 3:
0   libsystem_kernel.dylib        	       0x1bb64aaac mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1bb64b07c mach_msg + 72
2   CoreFoundation                	       0x180cefcc8 __CFRunLoopServiceMachPort + 368
3   CoreFoundation                	       0x180cf3fd0 __CFRunLoopRun + 1160
4   CoreFoundation                	       0x180d07194 CFRunLoopRunSpecific + 572
5   Foundation                    	       0x182414eac -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
6   Foundation                    	       0x182453fd0 -[NSRunLoop(NSRunLoop) runUntilDate:] + 88
7   UIKitCore                     	       0x183488ef4 -[UIEventFetcher threadMain] + 512
8   Foundation                    	       0x182461bdc __NSThread__start__ + 792
9   libsystem_pthread.dylib       	       0x1dc0e2348 _pthread_start + 116
10  libsystem_pthread.dylib       	       0x1dc0e0948 thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x1dc0e0934 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1dc0e0934 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x8000000100440430   x2: 0xd000000000000022   x3: 0x0000000000000000
    x4: 0x0000000000000052   x5: 0x0000000100000058   x6: 0x0000000000000000   x7: 0x0000000000000001
    x8: 0xd000000000000022   x9: 0x8000000100440430  x10: 0x0000000185834f90  x11: 0x00000001857a0f48
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x000000001f400000  x15: 0x000000020bb68000
   x16: 0x00000001857cefcc  x17: 0x000000019859fb1c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x00000001f610bb40  x21: 0x000000019afb40cb  x22: 0x0000000000000001  x23: 0x0000000000000001
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x000000019b1f4db6  x27: 0x000000002b870064
   x28: 0x0000000000000010   fp: 0x000000016fcc5230   lr: 0x00000001003b5e88
    sp: 0x000000016fcc5220   pc: 0x00000001857ceff0 cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1854a9000 -        0x185906fff libswiftCore.dylib arm64  <6ff6c88d49693ec698a2e4967aaff14a> /usr/lib/swift/libswiftCore.dylib
       0x1003ac000 -        0x10044bfff background_downloader arm64  <b2e1eeeb739d3e0b9a0730e99c2c1398> /private/var/containers/Bundle/Application/632391BF-E749-4BCB-AFCB-A4A10756D889/Runner.app/Frameworks/background_downloader.framework/background_downloader
       0x100138000 -        0x10013ffff Runner arm64  <fea85d52616038f9b07a7a4274b29df0> /private/var/containers/Bundle/Application/632391BF-E749-4BCB-AFCB-A4A10756D889/Runner.app/Runner
       0x183024000 -        0x1847bffff UIKitCore arm64  <697c7d5c976136e98e0f200035bf3f39> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x191eda000 -        0x191f79fff FrontBoardServices arm64  <7c13c168280e3e9eb3af4f49b0c3731a> /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
       0x1809d8000 -        0x180a5afff libdispatch.dylib arm64  <34ef3925030330bf9946ad99311620dd> /usr/lib/system/libdispatch.dylib
       0x180ce9000 -        0x181126fff CoreFoundation arm64  <55c76f8ebcc93a4c9f6216eac0ba8ab8> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x1a1839000 -        0x1a1841fff GraphicsServices arm64  <8f5bd2c4f5d5358e82bd1b2259a5c050> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x100308000 -        0x10035bfff dyld arm64  <58ab16ced7e032d3946d4f68fb1a4a17> /usr/lib/dyld
       0x1dc0df000 -        0x1dc0effff libsystem_pthread.dylib arm64  <ad10e93329043dbc9575707033bf6949> /usr/lib/system/libsystem_pthread.dylib
       0x1bb64a000 -        0x1bb67dfff libsystem_kernel.dylib arm64  <af565ccf2e9d37b0ae60c41279a0025a> /usr/lib/system/libsystem_kernel.dylib
       0x1823fd000 -        0x1826e1fff Foundation arm64  <3f1763e110b63144b223e031482cbf46> /System/Library/Frameworks/Foundation.framework/Foundation
       0x1dc0fe000 -        0x1dc136fff libxpc.dylib arm64  <1b604e6983b739ae84fd6ed89baefca7> /usr/lib/system/libxpc.dylib

EOF

**Comment by lancezhaozai** [comment]
> <img alt="51a7d58ad9e255f0079a05fcaf5e615" width="629" src="https://private-user-images.githubusercontent.com/10924643/311621859-a1131d47-0563-49e7-953b-48434729fba8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI3NzE1NTEsIm5iZiI6MTc2Mjc3MTI1MSwicGF0aCI6Ii8xMDkyNDY0My8zMTE2MjE4NTktYTExMzFkNDctMDU2My00OWU3LTk1M2ItNDg0MzQ3MjlmYmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTEwVDEwNDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YTI4MWU2MmZmZmQxOGFiYzM2MjYxZTdiZjA4OThiMjNkZjUxNDk5MjNmNzMzMjBmZWViZWEwMzU0OGIyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DU-u-sQb0ly9a63nxSkIbppj-sOT8bRyFA3Wpzeh8ik"> use .default ; work on ios15 device。 maybe permission problem

this worked, to resolve permission issue, unable to move file from... to..., on iOS, thanks
