### ISSUE TITLE
Could not find com.android.tools.build:gradle:8.2.1

### ISSUE THREAD

**Issue by taheri79** [781flyingdutchman/background_downloader#257]
I can't build my project with this package.
i done everything i founded from googling.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':background_downloader'.
> Could not resolve all files for configuration ':background_downloader:classpath'.
   > Could not find com.android.tools.build:gradle:8.2.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.2.1/gradle-8.2.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.2.1/gradle-8.2.1.pom
     Required by:
         project :background_downloader
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':background_downloader' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':background_downloader' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by 781flyingdutchman** [comment]
Could be you're using an incompatible Gradle version, and/or an older Kotlin version (see #253 ). Take a look at the example app in the repo and compare the various build.gradle files to see if there's a hint there.

**Comment by 781flyingdutchman** [comment]
Also take a look at this: https://stackoverflow.com/questions/76840493/cant-resolve-could-not-find-com-android-tools-buildgradle8-2-1-error-when-b

**Comment by taheri79** [comment]
Thanks for yor help.
I looked at the example and the question from stackoverflow.

I decided to chenge my kotlin version to 1.9.20 and set distributionUrl to https\://services.gradle.org/distributions/gradle-8.2-all.zip

now im facing another error.

I tried any other solutions to from these answers and issues.


android/build.grandle:

`buildscript {
    ext.kotlin_version = '1.9.20'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
`
grandle/geandle-wrapper.properties:

`distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
#distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-all.zip
`


The new Error:

`FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\projects\dalfak_app2\android\settings.gradle' line: 26

* What went wrong:
Plugin [id: 'com.android.application', version: '7.3.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.android.application:com.android.application.gradle.plugin:7.3.0')
  Searched in the following repositories:
    Google
    MavenRepo
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
Error: Gradle task assembleDebug failed with exit code 1
`

**Comment by taheri79** [comment]
i found the problem

**Comment by taheri79** [comment]
I found the problem

my problem is because im in Iran the repositories are blocked from my ip due to sanctions.

thank for every ones. :)))))))))))

**Comment by taheri79** [comment]
I thinks developers must have free world. but goverments dont.

**Comment by 781flyingdutchman** [comment]
Sorry to hear that 😕
