### ISSUE TITLE
I need a callback for tasks following the download

### ISSUE THREAD

**Issue by Yeseung0610** [781flyingdutchman/background_downloader#260]
I intend to add logic to decompress the downloaded files and verify if the checksum matches after the download feature.

However, this operation won't work if the application is terminated because the processing after the download completion is executed on the main thread. 

I need a feature to register a vm:entry-point method as a callback so that desired logic can be executed after the download is finished.

Thank you for always providing great packages. I'm grateful for your work.

**Comment by 781flyingdutchman** [comment]
Hi, I'm not sure I understand the issue: you can register a static function as a callback using `FileDownloader().registerCallbacks`. The statusCallback will be called when the job completes. If the download completes while the job is in the background, the callback is 'saved' and will be sent to your registered callback as soon as you call `await FileDownloader().resumeFromBackground()` (which you should do early in your application startup sequence, but after you have registered your callbacks).  As a result, you should always be able to trigger the decompress when your download has finished. What you cannot do is start your decompress from the background download: that background operation is restricted to the download itself. But by ensuring you register your handler and calling `resumeFromBackground` you should be able to accomplish what you describe.

Let me know if I'm missing something about your questions, or if this solves the issue.

**Comment by Yeseung0610** [comment]
I have reviewed the contents of the package (Android-based). Currently, there is no way to execute the flutterEngine if the native main thread is not alive. Therefore, there is no way to execute Dart code from workmanager when the app has completely exited. However, by running a Service, you can keep the main thread alive and register and execute callbacks even when the app is completely exited.

I have created a minimal android flutter project that can run the modified package. Please review it!
[https://github.com/Yeseung0610/download_test_sample_application](url)

**Comment by 781flyingdutchman** [comment]
I understand this is possible, but running the downloader as a service is much more resources intense than leveraging the WorkManager. As I mentioned above, I believe you can accomplish what you want by using the downloader callback functionality. If you prefer to use a modified version then of course that's ok, but I don't want to adopt that approach for the plugin as published.

**Comment by Yeseung0610** [comment]
Understood! Thank you for your answer.
