### ISSUE TITLE
TaskException: Could not enqueue task ParallelDownloadTask

### ISSUE THREAD

**Issue by horlann** [781flyingdutchman/background_downloader#262]
Hello!I stuck in a trouble to create "multipart" download using ParallelDownloadTask.I need a get multiple chunks from BE (max 10mb per request) and aggregate them into 1 file on ios/android device.No matter which link ill provide and which amount of chunks.All attempts to enqueue returned that error,but when I tried to download something from protected server without bearer token in response I got 401 exception

` final task = ParallelDownloadTask(
            //url: urls,
            url: [
              'https://live.staticflickr.com/8243/8466462590_60cef1c48a_b.jpg',
              'https://live.staticflickr.com/8243/8466462590_60cef1c48a_b.jpg'
            ],
            // filename: file.name,
            // headers: {'Authorization': 'Bearer $bearer'},
            updates: Updates.statusAndProgress,
            chunks: 2,
          );`
          
   ` await FileDownloader().enqueue(task);
`

**Comment by 781flyingdutchman** [comment]
Hi, a few questions/clarifications:
1. On which platform(s) (Android, iOS, Desktop) does this problem occur?
2. If Android, can you share the LogCat output around the time of the error? It is more detailed than the Flutter logs
3. The 'Could not enqueue' error suggests you are using `FileDownloader().download` and not `FileDownloader().enqueue` as you have in your example. Can you share the full code snippet where you create the task and kick off the download?
4. In the example you enqueue two urls, but they are both the same. Given you also pass `chunks=2` you will break the download into 4 parts (2 chunks for each of 2 urls). Have you tried using just one url and `chunks=2`?
5. Are you sure that your server allows for parallel downloads (i.e. accepts a Range header and multiple requests to the same file)?

Once we have this data let's take another look.

**Comment by horlann** [comment]
1)It is IOS
2)Cannot test on android unfortunately
3)This error occurs in both cases: .enqueue .download

My BE returns me data by binary in 10mb chunks
For example ill provide 2 links
https/file.com/download/multipart/uiisd-4312-7212?start=0&end=100000
https/file.com/download/multipart/uiisd-4312-7212?start=100000&end=200000

**Comment by horlann** [comment]
I also created something like this
code a bit messy cause it is investigation example.Maybe i didnt correctly understood posibilities of background_downloader
` try {
      final urls = <String>[];
      final tasks = <DownloadTask>[];
      int counter = 1;
      int index = 0;
      while (counter < file.size) {
        final int incrementedCounter = counter + maxPartSize;
        final url =
            'https://file.devenv/file/multipart/download?key=${file.id}&from=$counter&to=$incrementedCounter';
        urls.add(url);
        final task = DownloadTask(
            url: url,
            filename: '$index|${file.name}',
            headers: {'Authorization': 'Bearer $bearer'},
            updates: Updates.statusAndProgress);
        tasks.add(task);
        counter = incrementedCounter;
        index = index + 1;
      }
      final tempDirectory = await getApplicationDocumentsDirectory();
      final File tempFile = File('${tempDirectory.path}/${file.name}.tmp');
      int inn = 0;
      for (final task in tasks) {
        final result = await FileDownloader().download(task,
            onProgress: (progress) => print('Progress: ${progress * 100}%'),
            onStatus: (status) =>
                print('Status: $status')); // Act on the result
        switch (result.status) {
          case TaskStatus.failed:
            LoggerService().log(
                'Download not successful ${result.responseHeaders} ${result.responseBody} ${result.exception}');
            _updateStatus(
              isErrorOccured: true,
              taskId: result.task.taskId,
              percents: 0,
            );
          default:
        }
        final loadedFIlePath = await task.filePath();
        final openFile = File(loadedFIlePath);
        final bytes = await openFile.readAsBytes();
        await tempFile.writeAsBytes(bytes, mode: FileMode.append);
        await openFile.delete();
        inn = inn + 1;
      }
      await tempFile.rename('${tempDirectory.path}/${file.name}');
    } `

**Comment by 781flyingdutchman** [comment]
The parallel download assumes a single url and uses the Range header to extract a specific chunk. This is the only "standard" way to do it. Using the query parameters (start and end in your example, or from and to in the other) is a server/backend specific way and won't work with ParallelDownload. If using start/end is the preferred way to download chunks, then you'll have to create multiple regular download tasks yourself (using the query parameters to select different parts) and stitch them together yourself.

Note that the way you've implemented your stitching seems to assume that downloads complete in the order they were enqueued, and that's not a valid assumption so you'll have to create a smarter custom stitch function.

**Comment by horlann** [comment]
Ok thanks!Ill share with others my solution here,when it will looks cool!

**Comment by horlann** [comment]
I can request BE modifying to enable support of ParallelDownloadTask
Can you please provide requirements,Because I cant extract main differences

**Comment by horlann** [comment]
Also faced with problem,that app stucks whem amount of chunnks more than 10.Any downloading progress and hot restart didnt help
Looks like operation overflow,is it possible to limit amount of simultaneously operaions?

**Comment by 781flyingdutchman** [comment]
I answered the question about requirements on your other issue. The lockup is likely related to your server - there isn't an issue with 10 parallel tasks from the downloader perspective, but quite possible from the server or bandwidth

**Comment by horlann** [comment]
Problem was on my BE
1)BE didnt provide proper response headers,which must be 
<img width="1197" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/61031890/6ce0fbf4-4714-4959-a581-21d4c82ab03c">

2)BE operated with bytes in range 0-n,by this library sends bytes in bundles starting from 1
