### ISSUE TITLE
Content-length issue

### ISSUE THREAD

**Issue by horlann** [781flyingdutchman/background_downloader#263]
After investigation of  the source code I found that calculation of total file size provided by 'Content-Length' header value from BE,but if server returns value by chunks in means that  'Content-Length' must be different from actual response size.Maybe better will be prioritize our custom provided 'Known-Content-Length' instead of BE provided value.

Example:
Total file size 100mb and max response capacity is 10mb per request.It will be 10 request by 10mb 

<img width="1083" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/61031890/960be57f-7f59-4e9e-bca3-4af5a8766842">

<img width="841" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/61031890/bdb298c9-a721-4c58-a06d-a6dd01bf93ff">

Also found in tests yours example.This exactly my goal,but it will works only when BE dont provide any 'Content-Length'
<img width="615" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/61031890/c5c73c61-4571-408d-9775-d26b14a8c9ff">

**Comment by 781flyingdutchman** [comment]
Your server should send the total file content length in the header, and include the "Accept-Ranges" header with the value "bytes", and then of course respond appropriately when the subsequent request includes a "Range" header.  Each chunk is it's own (invisible to you) task so it doesn't really matter what content length is sent for those requests I believe.
