### ISSUE TITLE
Fail to install background downloader on ios 15 v17

### ISSUE THREAD

**Issue by Pranavmaid** [781flyingdutchman/background_downloader#265]
Flutter Doctor
<img width="650" alt="Screenshot 2024-03-14 at 1 29 46 AM" src="https://github.com/781flyingdutchman/background_downloader/assets/64965878/b5ae8f7b-cf3f-4488-ac38-baaf374a9a4d">

**To Reproduce**
1] cd ios
2] pod deintegrate
3] pod inatall
4] CocoaPods could not find compatible versions for pod "background_downloader":
  In Podfile:
    background_downloader (from `.symlinks/plugins/background_downloader/ios`)

Specs satisfying the `background_downloader (from `.symlinks/plugins/background_downloader/ios`)` dependency were found, but they required a higher minimum deployment target.

AppDelegate.swift
`
import UIKit
import Flutter
import FirebaseCore

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
`
<img width="1068" alt="Screenshot 2024-03-14 at 1 28 45 AM" src="https://github.com/781flyingdutchman/background_downloader/assets/64965878/8ae9c4a2-c56e-421a-88bb-fe9c4c459228">

**Comment by 781flyingdutchman** [comment]
The minimum deployment target for iOS is 13, and from the error it looks like your app has a lower deployment target. You should update that to 13 - if that's not possible then unfortunately you can't use the background_downloader.

**Comment by Pranavmaid** [comment]
Yess this solved the issue!
can you add this info in pkg info it will be help full for others

**Comment by 781flyingdutchman** [comment]
It's in the 'limitations' section of the docs :)
