### ISSUE TITLE
Canot move shared storage path

### ISSUE THREAD

**Issue by this-sunil** [781flyingdutchman/background_downloader#269]
Canot move shared storage path flutter I have downloaded file move file in video library I want move Android store path

**Comment by 781flyingdutchman** [comment]
There are several requirements (e.g. permissions) to do this, so please please read the [documentation](https://pub.dev/packages/background_downloader#shared-and-scoped-storage) about shared and scoped storage and make sure you follow all those instructions.

If it doesn't work, please file a proper issue - one sentence is not going to help me help you.
