### ISSUE TITLE
Windows: reports canceled after app restart

### ISSUE THREAD

**Issue by eivihnd** [781flyingdutchman/background_downloader#27]
I am experiencing a problem in my implementation of the background_downloader.

**My setup:**
I have implemented my own queue database with queued files for download. Once an item is added to the queue, a worker (that subscribes to queue changes) will initiate a download (if no other downloads are active).
The same worker will on initialisation start a download (if no other downloads are active). 

A queue item will have an ID, and this id is used as taskId for the background_downloader download task.

**My problem**
Below is the steps used to produce the issue:

1. Start a download with `taskId = x` (not literarily x, but for the sake of simplicity x is used here)
2. Close the app
3. Restart the app
4. Start new (the same url) download with `taskId = x` (same id as in step 1)

In the debug console, the following information is printed:
`2 flutter: TaskStatus.enqueued
2 flutter: TaskStatus.running
flutter: FileDownloader>FINE: 2023-04-04 15:18:51.204115: Could not delete temp file C:\Users\FLUTTE~1\AppData\Local\Temp\com.bbflight.background_downloader3078630720
flutter: TaskStatus.canceled`

The downloader reports that the task is cancelled, and does not emit running status even though the download progress is clearly working. Finally it emits complete status when the download is complete and the file is successfully downloaded.

Is this a bug, or is the problem that I am not using a unique id for every download?
And do you have an idea why Windows is not able to delete the temp file?

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out! Quick reaction before I head off to work: I do think the core issue is that you are reusing the ID when starting the download after closing the app, which is not "the contract" for the downloader plugin. The easiest way to address the issue therefore would be to use a new unique ID when restarting a task that was killed when the app closed. That said, i want to look into what exactly causes the issue you describe. Do you know if it behaves the same on another desktop platform (MacOS or Linux)?

**Comment by 781flyingdutchman** [comment]
Hi, I haven't been able to replicate what you're describing. I use the example app and modify the task to use the same ID (and modify the downloader a bit so it takes long for the download to complete), start the download, kill the app, start it again (with the same id) and it just completes normally. 

I also don't quite understand how there can be any remnant of a task still running after you kill the app (though perhaps the isolate where the download happens keeps running after the app closes? That seems weird but possible, and would then continue to generate status updates with the same taskID). Even so, the new download should not interfere with whatever remains ongoing (and per your logs it suggests it does indeed complete normally), even if it reuses the id, as it will use a new temp file to download to (unless the Dart `Random` implementation is not random and regenerates the same filename). It's possible that if there is a 'ghost isolate' from the previous app run it gets killed by the OS eventually, but that should lead to 'failed' and not 'canceled'. Is there anywhere you are issuing a `cancel` command, or `reset`?

The message about not being able to delete the temp file means that by the time it wanted to cancel the task (and delete the partial download stored in the temp file) the temp file was no longer there, or was in use - possibly the OS cleans it up when you kill the app?

Sorry I don't have any better answers. Please try using a different (random) id and see if it works then, or if not please post the full logs for both app runs.

**Comment by 781flyingdutchman** [comment]
Hi @eivihnd wanted to see if you've been able to solve the problem by using a unique ID? As mentioned, I wasn't able to replicate the issue so unless you can provide more details I will close this issue in a few days.
