### ISSUE TITLE
download history

### ISSUE THREAD

**Issue by pigivc** [781flyingdutchman/background_downloader#270]
hello 

I am wondering if there is any api or method to retrieve downloaded files history . I have tried 
`await FileDownloader().database.allRecords()`
but it returns empty list

thanks in advance

**Comment by 781flyingdutchman** [comment]
Hi, please read the [documentation](https://pub.dev/packages/background_downloader#using-the-database-to-track-tasks) about the database. In particular, you need to activate tracking when you start your app before attempting to use the database, by calling `await FileDownloader().trackTasks();`
