### ISSUE TITLE
multiple file not download at time getting override issue

### ISSUE THREAD

**Issue by tulsi-virani** [781flyingdutchman/background_downloader#272]
**Describe the bug**
multiple file not download at time getting override issue

**Code**
If possible, paste in the code snippet where you interact with the package:
background_downloader: ^8.0.4

Code
main.dart
`
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:pdf_downloader_task/downloading_screen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'PDF Downloader',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PDF Downloader'),
        centerTitle: true,
      ),
      body: Center(
        child: ElevatedButton(
          child: const Text("Start"),
          onPressed: () {
            Get.to(const DownloadingScreen());
          },
        ),
      ),
    );
  }
}
`

** controller.dart

` import 'dart:async';

import 'package:background_downloader/background_downloader.dart';
import 'package:get/get.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf_downloader_task/download_model.dart';
import 'package:http/http.dart' as http;

class DownloaderController extends GetxController {
  RxList<DownloadModel> downloadingList = <DownloadModel>[].obs;
  List<String> staticUrl = [
    "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
    // "https://research.nhm.org/pdfs/10840/10840.pdf",
  ];

  void loadPdfData() async {
    for (int i = 0; i < staticUrl.length; i++) {
      downloadingList.add(DownloadModel(pdfUrl: staticUrl[i]));
    }

    for (int i = 0; i < downloadingList.length; i++) {
      String url = downloadingList[i].pdfUrl;
      String fileName = DateTime.now().millisecondsSinceEpoch.toString() +
          url.split('/').last;
      downloadingList[i].backgroundDownloadTask = DownloadTask(
        url: url,
        filename: fileName,
        directory: 'my/directory',
        baseDirectory: BaseDirectory.applicationDocuments,
        updates: Updates.statusAndProgress,
        retries: 3,
        allowPause: true,

      );
      downloadingList[i].taskId =
          downloadingList[i].backgroundDownloadTask?.taskId ?? '';
      downloadingList[i].name =
          downloadingList[i].backgroundDownloadTask?.filename ?? '';
      bool isCalled = false;

      int total = await getFileBytes(url);
      FileDownloader()
          .configureNotification(
              running:
                  const TaskNotification('Downloading', 'file: {filename}'),
              progressBar: false)
          .registerCallbacks(
        taskProgressCallback: (TaskProgressUpdate update) async {
          print("update: $i : ${update.toJson()}");
          if(update.progress < 0) return;
          int progress = (update.progress * 100).round();
          int received = ((progress * total) / 100).round();
          if (progress == 100 && !isCalled) {
            isCalled = true;
            var tempPath = await getApplicationDocumentsDirectory();
            downloadingList[i].downloadPercentage = 100;
            downloadingList[i].pdfUrl =
                "${tempPath.path}/${update.task.directory}/${update.task.filename}";
            downloadingList.refresh();
          } else {
            downloadingList[i].downloadPercentage =
                ((received * 100) / total).round();
            downloadingList.refresh();
          }
        },
        taskStatusCallback: (TaskStatusUpdate taskStatusUpdate) async {
          downloadingList[i].taskStatus = taskStatusUpdate.status;
          downloadingList.refresh();
        },
      );
      FileDownloader().enqueue(downloadingList[i].backgroundDownloadTask!);
    }
  }

  Future<void> buttonClick(
      TaskStatus taskStatus, DownloadTask? downloadTask) async {
    if (taskStatus == TaskStatus.paused) {
      if (downloadTask != null) {
        await FileDownloader().resume(downloadTask);
      }
    } else if (taskStatus == TaskStatus.running ||
        taskStatus == TaskStatus.enqueued) {
      if (downloadTask != null) {
        await FileDownloader().pause(downloadTask);
      }
    }
  }

  Future<int> getFileBytes(String filesUrl) async {
    DateTime startDateTime = DateTime.now();
    http.Response response = await http.Client().head(Uri.parse(filesUrl));
    int fileBytes = int.parse(response.headers["content-length"] ?? '0');
    print(
        "getFileSize Size $fileBytes Bytes || Time: ${DateTime.now().difference(startDateTime).inSeconds} Second");
    return fileBytes;
  }
}
`
** model.dart

`import 'package:background_downloader/background_downloader.dart';
import 'package:pdf_downloader_task/temp.dart';

class DownloadModel {
  String taskId;
  String pdfUrl;
  String name;
  int downloadPercentage;
  TaskStatus taskStatus;
  DownloadTask? backgroundDownloadTask;

  DownloadModel({
    this.taskId = '',
    required this.pdfUrl,
    this.name = '',
    this.downloadPercentage = 0,
    this.taskStatus = TaskStatus.waitingToRetry,
    this.backgroundDownloadTask,
  });
}
`

** cards,dart

`import 'package:background_downloader/background_downloader.dart';
import 'package:flutter/material.dart';
import 'package:pdf_downloader_task/download_model.dart';

class DownloadingCard extends StatelessWidget {
  final DownloadModel downloadModel;
  final VoidCallback? onPressed;
  final VoidCallback? onOpenCallBack;

  const DownloadingCard(
      {required this.downloadModel,
      this.onPressed,
      this.onOpenCallBack,
      super.key});

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(10),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(downloadModel.name),
            Text(downloadModel.pdfUrl, maxLines: 2),
            const SizedBox(height: 10),
            Row(
              children: [
                Expanded(
                  child: TweenAnimationBuilder<double>(
                    duration: const Duration(milliseconds: 500),
                    curve: Curves.easeInOut,
                    tween: Tween<double>(
                      begin: 0,
                      end: downloadModel.downloadPercentage / 100,
                    ),
                    builder: (context, value, _) => ClipRRect(
                      borderRadius: const BorderRadius.all(Radius.circular(5)),
                      child: LinearProgressIndicator(
                        value: value,
                        color: Colors.deepPurple,
                        backgroundColor: Colors.grey.shade300,
                        minHeight: 20,
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 10),
                Text("${downloadModel.downloadPercentage}%"),
              ],
            ),
            Align(
              child: Row(
                children: [
                  if (downloadModel.taskStatus != TaskStatus.complete)
                    IconButton(
                        onPressed: onPressed != null
                            ? () {
                                onPressed!.call();
                              }
                            : null,
                        icon: Text(downloadModel.taskStatus ==
                                TaskStatus.waitingToRetry
                            ? 'Running'
                            : downloadModel.taskStatus == TaskStatus.failed ||
                                    downloadModel.taskStatus ==
                                        TaskStatus.notFound
                                ? 'Error'
                                : downloadModel.taskStatus == TaskStatus.paused
                                    ? 'Resume'
                                    : 'Pause')),
                  if (onOpenCallBack != null)
                    IconButton(
                        onPressed: onOpenCallBack != null
                            ? () {
                                onOpenCallBack!.call();
                              }
                            : null,
                        icon: const Text('Open')),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
`
** downloadscreen.dart

`import 'package:background_downloader/background_downloader.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:pdf_downloader_task/downloading_card.dart';
import 'package:pdf_downloader_task/download_controller.dart';
import 'package:pdf_downloader_task/download_model.dart';
import 'package:pdf_downloader_task/pdf_viewer.dart';

class DownloadingScreen extends StatefulWidget {
  const DownloadingScreen({super.key});

  @override
  State<DownloadingScreen> createState() => _DownloadingScreenState();
}

class _DownloadingScreenState extends State<DownloadingScreen> {
  DownloaderController controller = Get.put(DownloaderController())
    ..loadPdfData();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Downloading'),
        centerTitle: true,
      ),
      body: Obx(
        () => ListView.separated(
          itemCount: controller.downloadingList.length,
          padding: const EdgeInsets.all(15),
          itemBuilder: (context, index) {
            DownloadModel downloadModel = controller.downloadingList[index];
            return DownloadingCard(
              downloadModel: downloadModel,
              onPressed: () {
                controller.buttonClick(
                  controller.downloadingList[index].taskStatus,
                  controller.downloadingList[index].backgroundDownloadTask,
                );
              },
              onOpenCallBack: () {
                Get.to(PDFViewerScreen(index: index));
              },
            );
          },
          separatorBuilder: (context, index) {
            return const SizedBox(height: 5);
          },
        ),
      ),
    );
  }
}
`
** pdfvier.dart

`import 'dart:async';

import 'package:background_downloader/background_downloader.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_pdfview/flutter_pdfview.dart';
import 'package:get/get.dart';
import 'package:pdf_downloader_task/downloading_card.dart';
import 'package:pdf_downloader_task/download_controller.dart';

class PDFViewerScreen extends StatefulWidget {
  final int index;

  const PDFViewerScreen({required this.index, super.key});

  @override
  State<PDFViewerScreen> createState() => _PDFViewerScreenState();
}

class _PDFViewerScreenState extends State<PDFViewerScreen> {
  final Completer<PDFViewController> _controller =
      Completer<PDFViewController>();
  int? pages = 0;
  int? currentPage = 0;
  bool isReady = false;
  String errorMessage = '';
  DownloaderController controller = Get.find();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PDF Viewer'),
        centerTitle: true,
      ),
      body: Obx(
        () => controller.downloadingList[widget.index].taskStatus !=
                TaskStatus.complete
            ? Center(
                child: DownloadingCard(
                  downloadModel: controller.downloadingList[widget.index],
                  onPressed: () {
                    controller.buttonClick(
                      controller.downloadingList[widget.index].taskStatus,
                      controller
                          .downloadingList[widget.index].backgroundDownloadTask,
                    );
                  },
                ),
              )
            : Stack(
                children: <Widget>[
                  PDFView(
                    filePath: controller.downloadingList[widget.index].pdfUrl,
                    enableSwipe: true,
                    swipeHorizontal: false,
                    autoSpacing: false,
                    pageFling: true,
                    pageSnap: true,
                    defaultPage: currentPage!,
                    fitPolicy: FitPolicy.BOTH,
                    preventLinkNavigation: false,
                    onRender: (pages) {
                      setState(() {
                        this.pages = pages;
                        isReady = true;
                      });
                    },
                    onError: (error) {
                      setState(() {
                        errorMessage = error.toString();
                      });
                      if (kDebugMode) {
                        print(error.toString());
                      }
                    },
                    onPageError: (page, error) {
                      setState(() {
                        errorMessage = '$page: ${error.toString()}';
                      });
                      if (kDebugMode) {
                        print('$page: ${error.toString()}');
                      }
                    },
                    onViewCreated: (PDFViewController pdfViewController) {
                      _controller.complete(pdfViewController);
                    },
                    onLinkHandler: (String? uri) {
                      if (kDebugMode) {
                        print('goto uri: $uri');
                      }
                    },
                    onPageChanged: (int? page, int? total) {
                      if (kDebugMode) {
                        print('page change: $page/$total');
                      }
                      setState(() {
                        currentPage = page;
                      });
                    },
                  ),
                  errorMessage.isEmpty
                      ? !isReady
                          ? const Center(
                              child: CircularProgressIndicator(),
                            )
                          : Container()
                      : Center(
                          child: Text(errorMessage),
                        )
                ],
              ),
      ),
    );
  }
}
`

**Comment by 781flyingdutchman** [comment]
That's a lot of code, and very little explanation. Can you share what exactly the issue is (the behavior you see, versus the behavior you expect), the detailed error message and surrounding logs, and the relevant code piece only?
