### ISSUE TITLE
Unable to upload a file into aws s3 bucket

### ISSUE THREAD

**Issue by bbalachandhar** [781flyingdutchman/background_downloader#273]
**Describe the bug**
I am trying to upload an image file into my s3 bucket by uploadtask, but only getting 400, 403 error.

these are the headers that I am sending with my uploadtask object,

Map <String, String> custHeader ={"Authorization": authoriztionString,
    "Signature": signatureString,
    "Content-Type":"image/jpeg",
    "Content-Length":'$sizeInBytes',
  "Host" : "[exxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx30724650-qa.s3.us-east-1.amazonaws.com](http://etxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx30724650-qa.s3.us-east-1.amazonaws.com/)",
    "Date" : DateTime.now().toString()
  };

  queryParams.addAll(custHeader);
  print("Bala Test AuthString ${authoriztionString} \n all headers ${queryParams} and file ${file}");
  final task = UploadTask.fromFile(file: file,
      url: "https://exxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx30724650-qa.s3.us-east-1.amazonaws.com/public/",
      httpRequestMethod: "PUT",
       //urlQueryParameters: queryParams,
      headers: queryParams,
    retries: 3,
      fields: {'datafield': 'value'},
      fileField: 'myFile',
      updates: Updates.statusAndProgress
  );

if you provide the correct documentation for the s3 upload task, would be very useful. 

thanks,
bala

**Comment by 781flyingdutchman** [comment]
Hi, I'm not familiar with S3 but if you search the issues for S3 you will find a few others who have made this work. Perhaps that can help you also.
