### ISSUE TITLE
iOS background_downloader: ^8.0.2 crash

### ISSUE THREAD

**Issue by zhouyuanbo** [781flyingdutchman/background_downloader#275]
**Describe the bug**
When downloading pictures, firebase crashlytics reports crash issues.

**To Reproduce**
The problem doesn’t happen every time.

**Logs**

com.apple.main-thread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  GraphicsServices               0x1368 GSEventRunModal + 164
8  UIKitCore                      0x3a2d88 -[UIApplication _run] + 888
9  UIKitCore                      0x3a29ec UIApplicationMain + 340
10 Runner                         0x18590 main + 31 (AppDelegate.swift:31)
11 ???                            0x1d996d948 (Missing)

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  Foundation                     0x41818 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41700 -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4d788c -[UIEventFetcher threadMain] + 436
10 Foundation                     0x5ace8 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16cc _pthread_start + 148
12 libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

io.flutter.1.ui
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  Flutter                        0x2e1830 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
8  Flutter                        0x2e0ea4 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

io.flutter.1.raster
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  Flutter                        0x2e1830 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
8  Flutter                        0x2e0ea4 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  Flutter                        0x2e1830 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
8  Flutter                        0x2e0ea4 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2480 kevent + 8
1  Flutter                        0x597538 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
2  Flutter                        0x5c5494 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  libsystem_pthread.dylib        0x16cc _pthread_start + 148
4  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x55424 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x2dab9c (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

****Crashed: com.apple.NSURLSession-delegate
0  background_downloader          0x58778 specialized UrlSessionDelegate.urlSession(_:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:) + 35 (BDPlugin.swift:35)
1  background_downloader          0x539ac @objc UrlSessionDelegate.urlSession(_:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:) + 92**_**
2  CFNetwork                      0x7c1bc CFURLResponseCreateWithHTTPResponse + 40592
3  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
5  libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
6  libdispatch.dylib              0xc214 _dispatch_lane_invoke + 436
7  libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
8  libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
9  libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x214cc FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0x218ac FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0x1895c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x1b1e0 FIRCLSMachExceptionServer + 521 (FIRCLSMachException.c:521)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  CoreFoundation                 0xc5014 CFRunLoopRun + 64
8  CoreMotion                     0x13b14 CLMotionActivity::isTypeInVehicle(CLMotionActivity::Type) + 22624
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.NSURLSession-work
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  libdispatch.dylib              0x1f364 _dispatch_mach_send_and_wait_for_reply + 540
5  libdispatch.dylib              0x1f6ec dispatch_mach_send_with_result_and_wait_for_reply + 60
6  libxpc.dylib                   0xf8b0 xpc_connection_send_message_with_reply_sync + 240
7  Foundation                     0xa2574 __NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__ + 16
8  Foundation                     0x359bc -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 2236
9  Foundation                     0x3418c -[NSXPCConnection _sendSelector:withProxy:arg1:] + 116
10 Foundation                     0x340c4 _NSXPCDistantObjectSimpleMessageSend1 + 60
11 CFNetwork                      0x2c548 CFURLRequestSetHTTPRequestMethod + 23188
12 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
13 libdispatch.dylib              0x13574 _dispatch_lane_barrier_sync_invoke_and_complete + 56
14 CFNetwork                      0x58484 CFURLCacheCopySharedURLCache + 7460
15 CFNetwork                      0x3d974 CFURLRequestSetShouldStartSynchronously + 31880
16 background_downloader          0x9700 specialized BDPlugin.scheduleDownload(task:taskDescription:baseRequest:resumeData:) + 248 (BDPlugin.swift:248)
17 background_downloader          0xb244 (1) suspend resume partial function for specialized BDPlugin.doEnqueue(taskJsonString:notificationConfigJsonString:resumeDataAsBase64String:) + 217 (BDPlugin.swift:217)
18 libswift_Concurrency.dylib     0x41e9c swift::runJobInEstablishedExecutorContext(swift::Job*) + 420
19 libswift_Concurrency.dylib     0x42da8 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
20 libdispatch.dylib              0x15a6c _dispatch_root_queue_drain + 396
21 libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
22 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
23 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0xb90 start_wqthread + 254

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0xf3c70 scavenger_thread_main + 1364
3  libsystem_pthread.dylib        0x16cc _pthread_start + 148
4  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  CFNetwork                      0x254bac _CFURLStorageSessionDisableCache + 61076
8  Foundation                     0x5ace8 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x689d58 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
3  Flutter                        0x6c3bc8 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
4  Flutter                        0x689724 (Missing UUID 4c4c44fd55553144a110a8c20a7cc896)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

**Code**

final tq = MemoryTaskQueue();
    tq.maxConcurrent = 4;
    tq.maxConcurrentByHost = 2;
    tq.maxConcurrentByGroup = 3;
    FileDownloader().addTaskQueue(tq);

    FileDownloader().addTaskQueue(MemoryTaskQueue());
    await FileDownloader().enqueue(
      DownloadTask(
          taskId: imageUrl,
          url: imageUrl,
          filename: key,
          directory: cacheImageFolderName,
          baseDirectory: BaseDirectory.temporary,
          group: 'downloadImages',
          updates: Updates.none),
    );

I plan to upgrade to the latest 8.4.1 version, but I'm not sure if it will solve my problem.
Any suggestions from your side?
Thank you so much.

**Comment by 781flyingdutchman** [comment]
Which version are you using (so I can see what code the error refers to)?

Also, you're not using the TaskQueue correctly: if you add one, then to use it you need to add tasks to the TaskQueue you created, not enqueue directly with the downloader (that bypasses the TaskQueue).

**Comment by zhouyuanbo** [comment]
Thank you for responding to my question so quickly.

The version I am using now is background_downloader: ^8.0.2.

Below is the modified code based on your suggestions.
I will modify my project with the latest 8.4.1 version and the above code and see if the crash problem continues to occur.
Thank you again for your help.
