### ISSUE TITLE
IOS and adroid app stucks when chunks amount more then 10

### ISSUE THREAD

**Issue by horlann** [781flyingdutchman/background_downloader#276]
Also faced with problem,that app stucks when amount of chunks more than 10.Any downloading progress(last status enqueued,running didnt start) and hot restart didnt help
Looks like operation overflow,is it possible to limit amount of simultaneously operaions?

_Originally posted by @horlann in https://github.com/781flyingdutchman/background_downloader/issues/262#issuecomment-1983783761_

**Comment by horlann** [comment]
Hello again!I cant solve that issue for a long time in IOS...
It occurs with different apis
1)http://212.183.159.230/200MB.zip
2)https://ash-speed.hetzner.com/100MB.bin

All works proper before I set amount of chunks more then 8-12.I cant figure out myself and wll be glad for any help!

**Comment by horlann** [comment]
Here is parts of my code for better understanding

for (final file in files) {
        final task = await createTask(file, bearer ?? '', id);
         await _enqueueTask(task);
      }
      
      
      
       Future<ParallelDownloadTask> _createTaskForBigFile(
    FileModel file,
    String bearer,
    String sessionId,
  ) async {
    const url =
        'https://ash-speed.hetzner.com/100MB.bin';
    final task = ParallelDownloadTask(
      url: url,
      urlQueryParameters: {'key': file.id},
      headers: {
        'Authorization': 'Bearer $bearer',
      },
      chunks: (file.size / _maxPartSize).ceil(),
      filename: file.name,
      updates: Updates.statusAndProgress,
      retries: 2,
      allowPause: true,
    );
    final uploadModel = DownloadingModel(
      statusData: const UploadingStatusData(
        status: UploadingStatus.inProgress,
        percents: 0,
      ),
      fileName: file.name,
      path: file.name,
      taskId: task.taskId,
      fileModel: file,
      actionType: UploadingAction.download,
    );
    _addTaskToSession(sessionId, uploadModel);
    return task;
  }

  Future<void> _enqueueTask(DownloadTask task) async {
    try {
      _tq.add(task);
    } catch (e, s) {
      _updateStatus(
        exception: EnqueueDownloadTaskException(),
        taskId: task.taskId,
        percents: 0,
      );
      LoggerService().log(
        'EnqueueTask task error',
        error: e,
        stackTrace: s,
        logLevel: LogLevel.error,
        logAction: LogAction.general,
        sendToRemote: true,
      );
    }
  }

**Comment by 781flyingdutchman** [comment]
Hi, in the latest version I've added the option to configure a HoldingQueue - this may solve your problem. Please take a look at the [documentation](https://pub.dev/packages/background_downloader#task-queues) to see how to configure the holding queue to limit the number of concurrent tasks per host (don't use the MemoryTaskQueue for this) and let me know if that solves the issue.

**Comment by horlann** [comment]
Ive tried HoldingQueue,but in didnt help(

**Comment by horlann** [comment]
Here is log from XCode to clarify what happened.It is amount of chunks 10 for 102mb file,when amount<10 downlaoding proccess was succeful.It occurs with all apis on both platforms
<img width="575" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/61031890/0c3a4153-c638-45e7-98f9-00593ef14cae">

**Comment by 781flyingdutchman** [comment]
Fixed in V8.4.2 - sorry for the wait!

**Comment by horlann** [comment]
thanks a lot!!!!Ill check it today
You did it before our first release)

**Comment by horlann** [comment]
fixed!
