### ISSUE TITLE
Native task status did not got to the flutter listener

### ISSUE THREAD

**Issue by horlann** [781flyingdutchman/background_downloader#279]
In flutter code (code of listener below) I didnt got any task in             case TaskStatus.failed:

<img width="584" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/61031890/7cba808f-7193-45c6-b62e-98a3fb127c93">

 Future<void> _initListeners() async {
    try {
      FileDownloader().updates.asBroadcastStream().listen((update) {
        if (update is TaskStatusUpdate) {
          switch (update.status) {
            case TaskStatus.complete:
              _updateStatus(
                taskId: update.task.taskId,
                percents: 1,
              );
            case TaskStatus.failed:
              LoggerService().log(
                'Download file failed ${update.exception}'
                ' ${update.responseBody}',
                stackTrace: StackTrace.current,
                logLevel: LogLevel.warning,
                logAction: LogAction.general,
              );
              _updateStatus(
                exception: update.exception,
                taskId: update.task.taskId,
                percents: 0,
              );
            case TaskStatus.waitingToRetry:
              LoggerService().log(
                'Waiting for retry Download file failed ${update.exception}'
                ' ${update.responseBody}',
                stackTrace: StackTrace.current,
                logLevel: LogLevel.warning,
                logAction: LogAction.general,
              );
            default:
          }
        } else if (update is TaskProgressUpdate) {
          LoggerService().log(
            'Downloading in progress:\n ${update.expectedFileSize} ${update.task.taskId} ${update.progress}',
            stackTrace: StackTrace.current,
            logLevel: LogLevel.warning,
            logAction: LogAction.general,
          );
          _updateStatus(
            taskId: update.task.taskId,
            percents: update.progress,
          );
        }
      });
    } catch (e, s) {
      LoggerService().log(
        'Downloading task status update subscription error',
        error: e,
        stackTrace: s,
        logLevel: LogLevel.error,
        logAction: LogAction.filesIO,
        sendToRemote: true,
      );
    }
  }
`Future<void> _initListeners() async {
    try {
      FileDownloader().updates.asBroadcastStream().listen((update) {
        if (update is TaskStatusUpdate) {
          switch (update.status) {
            case TaskStatus.complete:
              _updateStatus(
                taskId: update.task.taskId,
                percents: 1,
              );
            case TaskStatus.failed:
              LoggerService().log(
                'Download file failed ${update.exception}'
                ' ${update.responseBody}',
                stackTrace: StackTrace.current,
                logLevel: LogLevel.warning,
                logAction: LogAction.general,
              );
              _updateStatus(
                exception: update.exception,
                taskId: update.task.taskId,
                percents: 0,
              );
            case TaskStatus.waitingToRetry:
              LoggerService().log(
                'Waiting for retry Download file failed ${update.exception}'
                ' ${update.responseBody}',
                stackTrace: StackTrace.current,
                logLevel: LogLevel.warning,
                logAction: LogAction.general,
              );
            default:
          }
        } else if (update is TaskProgressUpdate) {
          LoggerService().log(
            'Downloading in progress:\n ${update.expectedFileSize} ${update.task.taskId} ${update.progress}',
            stackTrace: StackTrace.current,
            logLevel: LogLevel.warning,
            logAction: LogAction.general,
          );
          _updateStatus(
            taskId: update.task.taskId,
            percents: update.progress,
          );
        }
      });
    } catch (e, s) {
      LoggerService().log(
        'Downloading task status update subscription error',
        error: e,
        stackTrace: s,
        logLevel: LogLevel.error,
        logAction: LogAction.filesIO,
        sendToRemote: true,
      );
    }
  }`

**Comment by horlann** [comment]
Weird things...Recently the same code had another behaviour,but now I get 405 error ,cause BE has GET error,but library awaiting for  HEAD

**Comment by 781flyingdutchman** [comment]
You should not treat updates as a broadcast stream: broadcast streams do not guarantee every message gets passed and it leads to errors like you experience. You should start listening to updates at app startup in a permanent object (like a Singleton) and never stop listening

**Comment by horlann** [comment]
I alredy did it
<img width="316" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/61031890/406cbf98-ec50-4a02-9d53-80bd9dcd4481">

**Comment by 781flyingdutchman** [comment]
Looking at your log again, i think you're starting a ParallelDownloadTask (the only place where the downloader makes a HEAD request). That request is done as part of enqueue (before the actual download of the chunks starts) and an error there should result in the enqueue call returning false. Because the enqueue fails, the task doesn't start and there are therefore no status updates. You should monitor the result of the enqueue call.
