### ISSUE TITLE
uploaded files are throwing corrupted error

### ISSUE THREAD

**Issue by bbalachandhar** [781flyingdutchman/background_downloader#283]
**Describe the bug**
I am using UploadTask.fromFile, once my file is uploaded then I am manually downloading from the server and trying to open it, but the uploaded files are always corrupted. both video and image i.e .jpg and .mp4

**To Reproduce**

**Expected behavior**

**Logs**
If possible, include logs that capture the issue:
```
logs
```

**Code**
```
final task = UploadTask.fromFile(file: file,
        fileField: fileName,
        metaData: fileName,
        url: "https://iugpun1oja.execute-api.us-east-1.amazonaws.com/qa/asdasdasdasdasdasdasdasdasd4650-qa/public%2f${fileName}",
        httpRequestMethod: "PUT",
        group: Constants.ftFishUploadingGroup,
        retries: 5,
      );
```

**Comment by bbalachandhar** [comment]
adding content length and post as 'binary', fixed my issue. now I can able to submit a file into s3 without any issue. 


 final task = UploadTask.fromFile(file: file,
        headers: {"Content-Length":"${sizeInBytes}"},
        metaData: fileName,
        fileField: fileName,
        post:'binary',
        url: "https://iugpxxxxxxxxxe-api.us-east-1.amazonaws.com/qa/exxxxxxxxxxxxxxxxxxxxxx50-qa/public%2f${fileName}",
        httpRequestMethod: "PUT",
        group: Constants.ftFishUploadingGroup,
        retries: 5,
      );

**Comment by 781flyingdutchman** [comment]
You shouldn't have to add Content-Length as the plugin does that. Are you saying that without it is doesn't work?  I got you on the tricky 'post' field - I may just add a subclass `BinaryUploadTask` that simply sets that for you :)

**Comment by bbalachandhar** [comment]
File upload is not working if the file size is beyond 5mb, am I missing something else with my code(below is the snipper that I am using for uploading task, its working fine for <5mb files.

final (baseDirectory, directory, filename) = await Task.split(filePath: '${dir}/${fileName}'); 
final task = UploadTask(
        url:
        "https://ixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx650-qa/public%2f${fileName}",
        filename: filename,
        baseDirectory: baseDirectory,
        directory: directory,
        post: 'binary',
        httpRequestMethod: "PUT",
        group: Constants.ftFishUploadingGroup,
        retries: 5,
        metaData: fileName,
        fileField: fileName,
      );
