### ISSUE TITLE
 Feature Request: Support App Privacy Manifest

### ISSUE THREAD

**Issue by snipd-min** [781flyingdutchman/background_downloader#284]
**Is your feature request related to a problem? Please describe.**
Apple has announced that starting in 2024 May 1st, apps will be required to include more privacy-related reasoning for "third-party SDKs." This includes providing details in privacy manifests about data use by these SDKs. 

Thank you for your attention to this matter.
https://developer.apple.com/news/?id=3d8a9yyh

**Describe the solution you'd like**
Upon scanning the codebase, it seems like the use of `NSPrivacyAccessedAPICategoryUserDefaults` and `NSPrivacyAccessedAPICategoryDiskSpace` (and potentially more?) would need to be declared in the privacy info file.

In Flutter SDK 3.19, this kind of support has already been implemented. You can find more details at: https://github.com/flutter/packages/pull/5846.

**Additional context**
You can read more about this requirement on the Apple Developer website: [Describing Data Use in Privacy Manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc)

**Comment by 781flyingdutchman** [comment]
Yes, I'm aware but I'm waiting until this is closer to becoming a requirement, as I suspect there will be some changes in how this should be handled. Note that the use of compiler flags for permissions already avoids most of the issue: if you set the appropriate BYPASS flags for the phot album permission then that code simply won't show up in the binary, and Apple will no complain.

**Comment by 781flyingdutchman** [comment]
Published in V8.9.1
