### ISSUE TITLE
Compilation error : Argument type error

### ISSUE THREAD

**Issue by NaveenKumar-07** [781flyingdutchman/background_downloader#286]
I am using background_downloader-8.4.3 for a UploadTask function. But when I try to run the app I get this below error
```
/C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/background_downloader-8.4.3/lib/src/desktop/upload_isolate.dart:78:47: Error: The argument type 'EventSink<List<int>>' can't be assigned to the parameter type 'StreamSink<List<int>>'.
 - 'EventSink' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'StreamSink' is from 'dart:async'.
        await transferBytes(inStream, request.sink, fileSize, task, sendPort);

                                              ^
/C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/background_downloader-8.4.3/lib/src/desktop/upload_isolate.dart:195:29: Error: The argument type 'EventSink<List<int>>' can't be assigned to the parameter type 'StreamSink<List<int>>'.
 - 'EventSink' is from 'dart:async'.
 - 'List' is from 'dart:core'.

 - 'StreamSink' is from 'dart:async'.
          inStream, request.sink, contentLength, task, sendPort);`
                            ^
Target kernel_snapshot failed: Exception
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```

**Additional context**
Below are the kotlin and gradle versions currently used :
kotlin version : '1.9.0'
build-gradle version : '7.3.0'

**Comment by 781flyingdutchman** [comment]
I suggest running `flutter clean` and checking that you have a recent version of Dart.

**Comment by NaveenKumar-07** [comment]
Thanks for the quick reply. I've updated Flutter to the recent version and also used `flutter clean` but still same error exist.
Screenshot of the error: 
![Capture (1)](https://github.com/781flyingdutchman/background_downloader/assets/78958995/f6919ec4-3382-46ec-881a-ec8996f836bb)

**Comment by 781flyingdutchman** [comment]
Per issue #164 I think you may be using an older version of the async or html packages. Run `pub upgrade` and  make sure you go with the recent versions of those packages

**Comment by NaveenKumar-07** [comment]
Thank you so much for helping me solve this issue. I just upgraded the http package to latest version and it worked.
