### ISSUE TITLE
Batch download time left

### ISSUE THREAD

**Issue by Rimantovas** [781flyingdutchman/background_downloader#287]
**Is your feature request related to a problem? Please describe.**
I am building a game launcher. When a user wants to download a game I create download tasks for all the needed files and start a batch download. While I can show a progress bar using batchProgressCallback, I can't seem to find a way how to show how much time is left to download all the files.

**Describe the solution you'd like**
batchProgressCallback could return timeRemaining for the whole batch

**Comment by 781flyingdutchman** [comment]
Not included in the base functionality but you can build something yourself: get the size of each file (and the total of the batch) ahead of the download operation (see below), note the start time of your batch download, and in your batch completion callback you can 'tick off' each file as it completes (by removing it from the list of `sizes` and, based on 1) how long it took to get there, 2) how many bytes you have downloaded, and 3) how many left you can approximate the time remaining.

Code to get the file sizes and total (untested):
```    final tasks = <DownloadTask>[];
    final sizes = <String, int>{};
    for (var task in tasks) {
      final headResult = await FileDownloader().request(task.copyWith(httpRequestMethod: 'HEAD'));
      final size = int.tryParse(headResult.headers['content-length'].toString());
      if (size != null) {
        sizes[task.taskId] = size;
      }
    }
    final batchSizeInBytes = sizes.values.reduce((value, size) => value + size);
    // now you have the size of each file in the batch and can 'tick them off'
    // whenever they complete, and calculate how many bytes left, how much
    // time therefore left, etc.
```
