### ISSUE TITLE
org.jetbrains.kotlinx.serialization.gradle.SerializationGradleSubplugin not a subtype

### ISSUE THREAD

**Issue by PercyMichael** [781flyingdutchman/background_downloader#295]
**Describe the bug**
Running **./gradlew clean build** produces

**FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':background_downloader'.
> Failed to notify project evaluation listener.
   > org.jetbrains.kotlin.gradle.plugin.KotlinGradleSubplugin: org.jetbrains.kotlinx.serialization.gradle.SerializationGradleSubplugin not a subtype

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
4 actionable tasks: 4 up-to-date**

**Comment by 781flyingdutchman** [comment]
Most likely you're using an older version of Kotlin in your project.  Make sure to use Kotlin 1.9.20 or newer.  Where/how you do that depends on your configuration and what version of the Android Gradle Plugin you're using, so you'll have to Google around for that. In general, best to stay close to most recent on both Kotlin and AGP to ensure compatibility.

**Comment by PercyMichael** [comment]
Launching lib/main.dart on TECNO BF6 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_file_downloader'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Error: Gradle task assembleDebug failed with exit code 1


Exited (1).

**Comment by 781flyingdutchman** [comment]
The error suggests that you haven't defined the namespace for your project

**Comment by PercyMichael** [comment]
> The error suggests that you haven't defined the namespace for your project

Been told the issue is with the google AGP Android Gradle Plugin, kindly tell me which version is used for this project

**Comment by 781flyingdutchman** [comment]
I think the example app uses 8.2

**Comment by PercyMichael** [comment]
Ive tried everything for 4 days now noting works,its always giving me this error,but the project was working before,

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_file_downloader'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by PercyMichael** [comment]
Actually it worked🤝🎉😎🤩 after more hours of searching found the answer on stackoverflow:

Modifiying the block **subprojects** to look like this under **android/build.gradle**

```
subprojects {
     afterEvaluate { project ->
       if (project.hasProperty('android')) {
           project.android {
               if (namespace == null) {
                   namespace project.group
               }
           }
       }
   }
}
```

Now **android/build.gradle** should look like this:
```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
     afterEvaluate { project ->
       if (project.hasProperty('android')) {
           project.android {
               if (namespace == null) {
                   namespace project.group
               }
           }
       }
   }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

Then **android/app/build.gradle** looks like:

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.realdeejays.app"
    compileSdk flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.realdeejays.app"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {}
```

Then my **android/settings.gradle** looks loke:

```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.1.2" apply false
    id "org.jetbrains.kotlin.android" version "1.9.20" apply false
}

include ":app"
```
Then my **android/gradle/wrapper/gradle-wrapper.properties** looks like:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip
```

**Comment by PercyMichael** [comment]
> Actually it worked🤝🎉😎🤩 after more hours of searching found the answer on stackoverflow:
> 
> Modifiying the block **subprojects** to look like this under **android/build.gradle**
> 
> ```
> subprojects {
>      afterEvaluate { project ->
>        if (project.hasProperty('android')) {
>            project.android {
>                if (namespace == null) {
>                    namespace project.group
>                }
>            }
>        }
>    }
> }
> ```
> 
> Now **android/build.gradle** should look like this:
> 
> ```
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>      afterEvaluate { project ->
>        if (project.hasProperty('android')) {
>            project.android {
>                if (namespace == null) {
>                    namespace project.group
>                }
>            }
>        }
>    }
> }
> 
> tasks.register("clean", Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> Then **android/app/build.gradle** looks like:
> 
> ```
> plugins {
>     id "com.android.application"
>     id "kotlin-android"
>     id "dev.flutter.flutter-gradle-plugin"
> }
> 
> def localProperties = new Properties()
> def localPropertiesFile = rootProject.file('local.properties')
> if (localPropertiesFile.exists()) {
>     localPropertiesFile.withReader('UTF-8') { reader ->
>         localProperties.load(reader)
>     }
> }
> 
> def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
> if (flutterVersionCode == null) {
>     flutterVersionCode = '1'
> }
> 
> def flutterVersionName = localProperties.getProperty('flutter.versionName')
> if (flutterVersionName == null) {
>     flutterVersionName = '1.0'
> }
> 
> android {
>     namespace "com.realdeejays.app"
>     compileSdk flutter.compileSdkVersion
>     ndkVersion flutter.ndkVersion
> 
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> 
>     kotlinOptions {
>         jvmTarget = '1.8'
>     }
> 
>     sourceSets {
>         main.java.srcDirs += 'src/main/kotlin'
>     }
> 
>     defaultConfig {
>         // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
>         applicationId "com.realdeejays.app"
>         // You can update the following values to match your application needs.
>         // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
>         minSdkVersion 21
>         targetSdkVersion flutter.targetSdkVersion
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>     }
> 
>     buildTypes {
>         release {
>             // TODO: Add your own signing config for the release build.
>             // Signing with the debug keys for now, so `flutter run --release` works.
>             signingConfig signingConfigs.debug
>         }
>     }
> }
> 
> flutter {
>     source '../..'
> }
> 
> dependencies {}
> ```
> 
> Then my **android/settings.gradle** looks loke:
> 
> ```
> pluginManagement {
>     def flutterSdkPath = {
>         def properties = new Properties()
>         file("local.properties").withInputStream { properties.load(it) }
>         def flutterSdkPath = properties.getProperty("flutter.sdk")
>         assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
>         return flutterSdkPath
>     }
>     settings.ext.flutterSdkPath = flutterSdkPath()
> 
>     includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")
> 
>     repositories {
>         google()
>         mavenCentral()
>         gradlePluginPortal()
>     }
> }
> 
> plugins {
>     id "dev.flutter.flutter-plugin-loader" version "1.0.0"
>     id "com.android.application" version "8.1.2" apply false
>     id "org.jetbrains.kotlin.android" version "1.9.20" apply false
> }
> 
> include ":app"
> ```
> 
> Then my **android/gradle/wrapper/gradle-wrapper.properties** looks like:
> 
> ```
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip
> ```

THANKS IN ADVANCE

**Comment by 781flyingdutchman** [comment]
Thanks for sharing your answer!  Gotta love the Android build system :)

I'm closing this but will refer others to your answer if they run into this. Thanks and good luck!
