### ISSUE TITLE
Enqueue multiple download tasks to  (around 1000) hangs main thread on Android

### ISSUE THREAD

**Issue by dko-orion** [781flyingdutchman/background_downloader#296]
Hi!

I'm using latest version (8.4.3) of background downloader to download multiple images from few different sources.

First I tried batch download to download them and on iOS it works perfectly and my app (that has google maps) works perfectly smooth and my images downloaded successfully. But on android maps begin behave laggy. So I returned to documentation and decided to work with HoldingQueue to ensure that downloading will be finished in background.

My configuration: ` FileDownloader()..configure(globalConfig: (Config.holdingQueue, (3, 2, 1))),`

After configuring HoldingQueue the time come to ensue my 1000+ download tasks like in code sample below. (Average size for whole images is around 50 mb).

And this hangs UI thread for some time until enqueue is not finished.

```
for (DownloadTask task in downloadTasksBatch) {
   await _downloader.enqueue(task);
}
```

Meanwhile tasks successfully enqueued
>  I/BackgroundDownloader(16134): Enqueueing task with id c13585e7-69ac-48b4-84d1-16ead75c7404 to the HoldingQueue

Ok, next I tried to add delay to let main thread actions to complete, it helped a bit but still not so well and overtime hangs main thread for some time and do not react on interactions.

```
  for (var i = 0; i < downloadTasksBatch.length; i++) {
    if (i % 5 == 0) {
      await Future.delayed(const Duration(milliseconds: 80));
    }

    await _downloader.enqueue(downloadTasksBatch[I]);
  }
```

On iOS still this works magically fine even on old iPhone :)

Then I thought why not put it in compute method as long as FileDonwloader is singleton, but there I faced multiple different issues probably because of `path_provider` issues with isolates like this:
>[: [FATAL:flutter/lib/ui/window/platform message response dart_port.cc(53)] Check failed: did_send. F/libc (14732): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1473]

or 
> Unhandled Exception: UI actions are only available on root isolate. E/flutter (10714): #0 PlatformDispatcher.__nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart)

So how can I enqueue multiple tasks without hanging main thread? Or what do I do wrong?

Or maybe you plan to introduce method like `enqueueTasks(List<Task> tasks)`?

Also need to mention fact, that seems that downloading in a HoldingQueue takes a little bit more effort.

Small update:
The only solution that worked so far was to use standard MemoryTaskQueue and push all tasks to it. It has effect on ui thread but not so tremendous like other solutions. But as documentation said that this tasks will be suspended in case of OS decide to kill it. 

Here is question: what if I want to download another 1000+ files, should I add to memory  existing memory queue or create new one and add to downloader?

**Comment by 781flyingdutchman** [comment]
Thanks for reaching out and yes this does take some extra work and has limitations, as the enqueue process in Android simply takes time, so 1000+ tasks will take time. Isolates unfortunately don't work due to a Flutter limitation on two-way plugin communication. What has worked for me (also queuing 1000+ tasks) i susing the `MemoryTaskQueue` just as a buffer (i.e. without any constraints) so that the enqueue operation itself is instant, and the queue manages the pacing of the actual enqueue with the downloader. You can play around with the interval settings to see what works for you. but at the default 20ms interval per enqueue you are talking about 20 seconds to enqueue 1000 tasks, and Android won't suspend your app in that timeframe, so you can likely increase the interval (set the queue's `minInterval`) and give the main thread time to catch up on other things.  Just use one queue, there is no benefit to using two. Let me know if you get it to work.

**Comment by dko-orion** [comment]
@781flyingdutchman Hi! Thank you for your kind and quick response!)
Tried your suggestion and set minInterval to 150 milliseconds and it did work for Android pretty well, yes, it, maybe, slow down download a bit, but not so crucial because host itself not so fast :) 
Also read in another thread proposal to make persistent queue storage and it eliminates a need to do it in a HoldingQueue.

> Just use one MemoryTaskQueue (and check if you need the HoldingQueue with constraints, as preferably you don't - it depends on your server and varies by Android phone, unfortunately)

Is it possible to have memory task queue and HoldingQueue at the same time?

**Comment by 781flyingdutchman** [comment]
Yes, you can use both together. The MemoryQueue is for buffering (avoids starving the UI thread) and the HoldingQueue is to constrain concurrency of the actual downloads. That way, your buffer only takes a short time to clear out, and the HoldingQueue ensures that you don't overload your server.

**Comment by dko-orion** [comment]
Seems I mistakenly assume that HoldingQueue is for letting DownloadWorker or Background Fetch do its job. 
Or MemoryQueue also uses native tools to ensure that downloading will continue when app is in background?

**Comment by dko-orion** [comment]
So and how should algorithm of copying from MemoryQueue to HoldingQueue should look like?

**Comment by 781flyingdutchman** [comment]
There's nothing needed to do that:
1) Configure your HoldingQueue with the constraints you want
2) Create a MemoryTaskQueue without any constraints, and modify the `minInterval` value as you see fit
3) Add the MemoryTaskQueue to the downloader
4) Add your tasks using the MemoryTaskQueue `add` method.

That's it

**Comment by dko-orion** [comment]
Thank you a lot for your kind support!
