### ISSUE TITLE
Image Upload on iOS doesn't start

### ISSUE THREAD

**Issue by johnsonejezie** [781flyingdutchman/background_downloader#300]
**Describe the bug**
Image upload on Android works fine but iOS doesn't start and no log of status or progress

**Code**
If possible, paste in the code snippet where you interact with the package:
```
final task = UploadTask.fromFile(
          file: file,
          url: url,
          headers: headers,
          httpRequestMethod: "POST",
          metaData: message.id,
          fields: {Constants.PREFIX: Constants.PREFIX_MESSAGES},
          updates: Updates.statusAndProgress,
          requiresWiFi: false);
      print("#### Task Ready ${task.toJson()}");
      final successfullyEnqueued = await FileDownloader().enqueue(task);
      log("#### Started $successfullyEnqueued");
```
The last log never get called. This works fine on Android

**Comment by 781flyingdutchman** [comment]
Assuming this is a binary upload, you need to set `post` to `'binary'` as otherwise this will be a form/multipart upload.

**Comment by johnsonejezie** [comment]
> binary

Thanks for the reply. It is a form/multipart upload. iOS is not getting queued

**Comment by 781flyingdutchman** [comment]
Strange - can you share the iOS logs (from the Console app on a Mac) as well as the Flutter logs (from your app)?

**Comment by johnsonejezie** [comment]
> Strange - can you share the iOS logs (from the Console app on a Mac) as well as the Flutter logs (from your app)?

The weird thing is there is no flutter log on my app. After calling the method to queue the upload, no log show up. I don't see any exception. The same code works perfect on Android. 
I am testing on iPhone device running iOS 17.4.1. My flutter version is 3.19.6

**Comment by 781flyingdutchman** [comment]
I'm looking for the iOS logs. When you run your app on a simulator (on a Mac) you can get those in the Console app. You filter by Category "Downloader". Please send me those logs (not a screenshot, just paste the text). Thanks.

**Comment by johnsonejezie** [comment]
`default	04:36:53.257807+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <2CEBA32F-60E3-4A37-AF5D-EA4030635E7D>.<51> type com.apple.MobileAsset.UAF.Siri.DialogAssets repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:36:57.381892+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <803E83CF-4F75-4B28-8BF8-CB053E0A87C9>.<8> type com.apple.MobileAsset.LinguisticData repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:36:58.640499+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <95974D3F-191E-4264-88E7-7A800DD98FB4>.<52> type com.apple.MobileAsset.UAF.Siri.DialogAssets repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:37:04.145060+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <278DD299-BDCE-43EE-B110-8B73D51EDF6F>.<53> type com.apple.MobileAsset.UAF.Siri.DialogAssets repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:37:09.971115+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <E1FF1AAC-6556-4999-A9BD-0BE3D0B6C659>.<54> type com.apple.MobileAsset.UAF.Siri.DialogAssets repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:37:17.377897+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <3A409194-CA37-44EB-8F05-380A7D45856B>.<16> type com.apple.MobileAsset.CoreSuggestions repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:38:03.958677+0100	kernel	AMFI: '/Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/Containers/Bundle/Application/85FFCEE5-6E46-449E-BAD0-85A426B8050C/RunnerStage.app/Frameworks/background_downloader.framework/background_downloader' is adhoc signed.
default	04:38:03.960376+0100	amfid	/Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/Containers/Bundle/Application/85FFCEE5-6E46-449E-BAD0-85A426B8050C/RunnerStage.app/Frameworks/background_downloader.framework/background_downloader not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/Containers/Bundle/Application/85FFCEE5-6E46-449E-BAD0-85A426B8050C/RunnerStage.app/Frameworks/background_downloader.framework/background_downloader, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
default	04:38:55.999562+0100	RunnerStage	BackgroundSession <585CDBB1-9CD2-4150-AFCF-109678004019> background session setup will wait for reply: session <__NSURLBackgroundSession: 0x10a96d750> with identifier com.bbflight.background_downloader.Downloader
default	04:38:55.011967+0100	nsurlsessiond	Creating session with identifier: com.bbflight.background_downloader.Downloader for bundle id: chat.glib.groupchat.stage
default	04:38:55.013806+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> Session <585CDBB1-9CD2-4150-AFCF-109678004019> is for <chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader> using resource timeout: 14400.000000, request timeout: 60.000000 allowsCellularAccess: 1, allowsExpensiveAccess: 1, _sourceApplicationBundleIdentifier: (null), _sourceApplicationSecondaryIdentifier: (null), hasSqliteSupport: 1
default	04:38:55.014014+0100	RunnerStage	BackgroundSession <585CDBB1-9CD2-4150-AFCF-109678004019> background session setup reply received: session <__NSURLBackgroundSession: 0x10a96d750> with identifier com.bbflight.background_downloader.Downloader
default	04:38:55.013833+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019>.<chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader>: created successfully
default	04:38:55.013859+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> Using XPC connection <NSXPCConnection: 0x60000333c280> connection from pid 67425 on mach service named com.apple.nsurlsessiond for client chat.glib.groupchat.stage with identifier com.bbflight.background_downloader.Downloader and PID 67425
default	04:38:55.017726+0100	nsurlsessiond	Task <32C7D3A2-5DE5-44D9-A2B1-E8AE6D9B8CD1>.<1> is for <chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader>.<1>
default	04:38:58.340171+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> client chat.glib.groupchat.stage is active result (Y), XPC(Y) proxy(Y) for com.bbflight.background_downloader.Downloader
default	04:39:27.319417+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <A6041672-3251-43EA-B1A3-263A86FF1E5E>.<55> type com.apple.MobileAsset.TTSAXResourceModelAssets repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:40:48.413280+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> client chat.glib.groupchat.stage disconnected, XPC(Y) proxy(Y) for com.bbflight.background_downloader.Downloader
default	04:40:48.416953+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019>.<chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader>: removing session
default	04:40:48.417443+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019>.<chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader> Lost connection to app -- connection invalidated
default	04:40:48.417469+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> client chat.glib.groupchat.stage disconnected, XPC(N) proxy(N) for com.bbflight.background_downloader.Downloader
default	04:41:51.026166+0100	mobileassetd	-[DownloaderSessionDelegate URLSession:downloadTask:didFinishDownloadingToURL:]: Moving file in didFinishDownloadingToURL, extractor: 1. Session <__NSURLBackgroundSession: 0x105506a50> task BackgroundDownloadTask <53810FBF-CFBA-4037-AF4E-F428705491F3>.<13> type com.apple.MobileAsset.GeoPolygonDataAssets repository /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/private/var/MobileAsset/AssetsV2
default	04:45:24.894397+0100	GoogleUpdater	[67846:259:0502/044524.894375:VERBOSE2:request_sender.cc(103)] Sending Omaha request: {"request":{"@os":"mac","@updater":"updater","acceptformat":"crx3,puff","app":[{"ap":"universal","appid":"com.google.chrome","brand":"CHFA","cohort":"1:1y5/2d5f/2d5l:","cohortname":"Control","enabled":true,"event":[{"download_time_ms":33582,"downloaded":207001696,"downloader":"direct","eventresult":1,"eventtype":14,"nextversion":"124.0.6367.94","previousversion":"124.0.6367.93","url":"http://edgedl.me.gvt1.com/edgedl/release2/chrome/addbwuavbxxv27ujgxljw6wni2ma_124.0.6367.94/com-google-chrome_124.0.6367.94_all_i5ywbvzbwuctyftzk7bkfxbsha.crx3"},{"eventresult":1,"eventtype":3,"nextfp":"1.95ace87f4a8d9264b42386d458856ae488830b4c405a01a89ecbbf933ffaf48e","nextversion":"124.0.6367.94","previousfp":"1.3ab56fcce430a6f8f0fb5e4c23cf78f6f2a444e1a26a828e0fc87bb3b2524417","previousversion":"124.0.6367.93"}],"packages":{"package":[{"fp":"1.95ace87f4a8d9264b42386d458856ae488830b4c405a01a89ecbbf933ffaf48e"}]},"version":"124.0.6367<…>
default	04:53:11.130426+0100	RunnerStage	BackgroundSession <585CDBB1-9CD2-4150-AFCF-109678004019> background session setup will wait for reply: session <__NSURLBackgroundSession: 0x10a96d750> with identifier com.bbflight.background_downloader.Downloader
default	04:53:11.139636+0100	nsurlsessiond	Creating session with identifier: com.bbflight.background_downloader.Downloader for bundle id: chat.glib.groupchat.stage
default	04:53:11.145503+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> Session <585CDBB1-9CD2-4150-AFCF-109678004019> is for <chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader> using resource timeout: 14400.000000, request timeout: 60.000000 allowsCellularAccess: 1, allowsExpensiveAccess: 1, _sourceApplicationBundleIdentifier: (null), _sourceApplicationSecondaryIdentifier: (null), hasSqliteSupport: 1
default	04:53:11.145533+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019>.<chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader>: created successfully
default	04:53:11.145549+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> Using XPC connection <NSXPCConnection: 0x60000331af80> connection from pid 67425 on mach service named com.apple.nsurlsessiond for client chat.glib.groupchat.stage with identifier com.bbflight.background_downloader.Downloader and PID 67425
default	04:53:11.145687+0100	RunnerStage	BackgroundSession <585CDBB1-9CD2-4150-AFCF-109678004019> background session setup reply received: session <__NSURLBackgroundSession: 0x10a96d750> with identifier com.bbflight.background_downloader.Downloader
default	04:54:19.110445+0100	nsurlsessiond	Task <E8EC9DEE-5A94-48F6-8386-6422D972ADC6>.<1> is for <chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader>.<1>
default	04:54:23.215194+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> client chat.glib.groupchat.stage is active result (Y), XPC(Y) proxy(Y) for com.bbflight.background_downloader.Downloader
default	04:56:01.305767+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> client chat.glib.groupchat.stage disconnected, XPC(Y) proxy(Y) for com.bbflight.background_downloader.Downloader
default	04:56:01.310628+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019>.<chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader>: removing session
default	04:56:01.311783+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019>.<chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader> Lost connection to app -- connection invalidated
default	04:56:01.312397+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> client chat.glib.groupchat.stage disconnected, XPC(N) proxy(N) for com.bbflight.background_downloader.Downloader
default	04:57:06.750758+0100	RunnerStage	BackgroundSession <585CDBB1-9CD2-4150-AFCF-109678004019> background session setup will wait for reply: session <__NSURLBackgroundSession: 0x10a96d750> with identifier com.bbflight.background_downloader.Downloader
default	04:57:06.752407+0100	nsurlsessiond	Creating session with identifier: com.bbflight.background_downloader.Downloader for bundle id: chat.glib.groupchat.stage
default	04:57:06.754343+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> Session <585CDBB1-9CD2-4150-AFCF-109678004019> is for <chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader> using resource timeout: 14400.000000, request timeout: 60.000000 allowsCellularAccess: 1, allowsExpensiveAccess: 1, _sourceApplicationBundleIdentifier: (null), _sourceApplicationSecondaryIdentifier: (null), hasSqliteSupport: 1
default	04:57:06.754579+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019>.<chat.glib.groupchat.stage>.<com.bbflight.background_downloader.Downloader>: created successfully
default	04:57:06.754839+0100	nsurlsessiond	NDSession <585CDBB1-9CD2-4150-AFCF-109678004019> Using XPC connection <NSXPCConnection: 0x600003309680> connection from pid 67425 on mach service named com.apple.nsurlsessiond for client chat.glib.groupchat.stage with identifier com.bbflight.background_downloader.Downloader and PID 67425
default	04:57:06.755217+0100	RunnerStage	BackgroundSession <585CDBB1-9CD2-4150-AFCF-109678004019> background session setup reply received: session <__NSURLBackgroundSession: 0x10a96d750> with identifier com.bbflight.background_downloader.Downloader

`
@781flyingdutchman Here is log from Mac

**Comment by 781flyingdutchman** [comment]
Two thoughts:
1) Per `default 04:38:03.960376+0100 amfid /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/Containers/Bundle/Application/85FFCEE5-6E46-449E-BAD0-85A426B8050C/RunnerStage.app/Frameworks/background_downloader.framework/background_downloader not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain"` it looks like there is a problem with how you have signed your app. I am not familiar with this, but this is not a normal log message and you should fix code signing (I don't know how)
2) These logs appear to be about downloads, not uploads.

Please try the code signing and get it to run without errors like these

**Comment by johnsonejezie** [comment]
> Strange - can you share the iOS logs (from the Console app on a Mac) as well as the Flutter logs (from your app)?



> Two thoughts:
> 
> 1. Per `default 04:38:03.960376+0100 amfid /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/Containers/Bundle/Application/85FFCEE5-6E46-449E-BAD0-85A426B8050C/RunnerStage.app/Frameworks/background_downloader.framework/background_downloader not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain"` it looks like there is a problem with how you have signed your app. I am not familiar with this, but this is not a normal log message and you should fix code signing (I don't know how)
> 2. These logs appear to be about downloads, not uploads.
> 
> Please try the code signing and get it to run without errors like these

**Comment by johnsonejezie** [comment]
> Two thoughts:
> 
> 1. Per `default 04:38:03.960376+0100 amfid /Users/johnsonejezie/Library/Developer/CoreSimulator/Devices/A10A3A14-68FB-4560-884F-D3EE8B21E915/data/Containers/Bundle/Application/85FFCEE5-6E46-449E-BAD0-85A426B8050C/RunnerStage.app/Frameworks/background_downloader.framework/background_downloader not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain"` it looks like there is a problem with how you have signed your app. I am not familiar with this, but this is not a normal log message and you should fix code signing (I don't know how)
> 2. These logs appear to be about downloads, not uploads.
> 
> Please try the code signing and get it to run without errors like these
Now I see this. Never complete

Enqueueing task with id 604141698
timeoutIntervalForResource = 14400 seconds
timeoutIntervalForRequest = 60 seconds
Not using proxy for any task
Starting/resuming taskId 604141698

**Comment by 781flyingdutchman** [comment]
This seems to be a different issue, so please don't mix it with the upload one. Closing this one, and I suspect there is still something wrong with your setup
