### ISSUE TITLE
Pause / Resume / Cancel only for download tasks?

### ISSUE THREAD

**Issue by MartinSchultz** [781flyingdutchman/background_downloader#301]
I fail to find how I can stop / cancel / resume / pause upload tasks. Clearly visible for download tasks, but not for uploading. Is this something I overlooked or not in there yet? 

Thanks a lot for the great library!
Martin

**Comment by 781flyingdutchman** [comment]
Correct, there is no standard for partial uploads (as there is for partial downloads) and different servers have implemented different approaches. As I understand a standard is being developed, so perhaps I can add that when it is there.

**Comment by MartinSchultz** [comment]
Cool thanks for the info!

To understand it right, that means uploads are "self-cleaning" in a way that if an upload fails, it gets removed after the max retry count?

And if it is suspended, it starts all over again with the upload?

**Comment by 781flyingdutchman** [comment]
Yes, it is just like a download with `allowPause` set to false. It's still
using the background mechanisms, so it won't get suspended when you're app
gets suspended.
