### ISSUE TITLE
When uploading and the state of the app goes from active to inactive the upload fails on Android

### ISSUE THREAD

**Issue by tbigueres** [781flyingdutchman/background_downloader#302]
**Describe the bug**
I try to handle a file upload that should be working on foreground or background. 
It works correctly on iOS, but when I try to do the same thing on Android an error occured. 

**To Reproduce**
Here is the code that I use to do the upload : 

```
Future<bool> unauthedUpload(String endpoint, File file,
      {void Function(TaskStatusUpdate)? sendStatus,
      void Function(TaskProgressUpdate)? sendProgress}) {
    int fileSize = file.lengthSync();

    Map<String, String> defaultHeaders = {
      "Content-Type": "application/octet-stream",
      "Content-Length": fileSize.toString()
    };

    String randomGroupName = DateTime.now().millisecondsSinceEpoch.toString();

    final task = UploadTask(
        url: endpoint,
        group: randomGroupName,
        baseDirectory: BaseDirectory.root,
        directory: file.parent.path,
        filename: file.path.split("/").last,
        headers: defaultHeaders,
        httpRequestMethod: 'PUT',
        post: 'binary',
        retries: 2,
        priority: 10,
        updates: Updates.statusAndProgress);

    final downloader = FileDownloader();

    downloader.registerCallbacks(
      group: randomGroupName,
      taskStatusCallback: (update) => sendStatus?.call(update),
      taskProgressCallback: (update) => sendProgress?.call(update),
    );

    return downloader.enqueue(task);
  }
```

**Expected behavior**
I would expect that when passing from active to inactive during the upload, the application would keep on uploading the file (which correctly works on iOS). 
When adding the retries, I see that once the task is cancelled when the app goes in inactive state, the system launches a retry and tries to do the upload again, but from the start. 
Same thing happens when I go back on the app and it goes back again from inactive to active, the task is cancelled and recreated from start. 

**Logs**
If possible, include logs that capture the issue:
```
I/flutter (10302): 🐛 [UPLOAD_BLOCK] {task: {url: https://*******.s3.eu-west-3.amazonaws.com/d******.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=*****Feu-west-3%2Fs3%2Faws4_request&X-Amz-Date=20240507T140926Z&X-Amz-Expires=4800&X-Amz-Signature=*******&X-Amz-SignedHeaders=host&x-id=PutObject, headers: {Content-Type: application/octet-stream, Content-Length: 1282269184}, httpRequestMethod: PUT, post: binary, retries: 2, retriesRemaining: 0, creationTime: 1715090967142, taskId: 1154777590, filename: 80394f73-ddf3-4816-bee2-0e449790d6f6.tar.gz, directory: storage/emulated/0/Android/data/com.mitral.apnealCTMobile/files/Acquisitions, baseDirectory: 4, group: 1715090967133, updates: 3, requiresWiFi: false, allowPause: false, priority: 10, metaData: , displayName: , taskType: UploadTask, fileField: file
I/WM-WorkerWrapper(10302): Work [ id=*******, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=1154777590, group=1715090967133 } ] was cancelled
I/WM-WorkerWrapper(10302): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(10302):      at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
I/WM-WorkerWrapper(10302):      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
I/WM-WorkerWrapper(10302):      at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
I/WM-WorkerWrapper(10302):      at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
I/WM-WorkerWrapper(10302):      at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
I/WM-WorkerWrapper(10302):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
I/WM-WorkerWrapper(10302):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
I/WM-WorkerWrapper(10302):      at java.lang.Thread.run(Thread.java:1012)
I/FA      (10302): Application backgrounded at: timestamp_millis: 1715091152170
```

Is there anything I can do to prevent this behavior ? 

Thanks

**Comment by 781flyingdutchman** [comment]
Hi, a few thoughts:
* Please don't include AWS credentials in your logs
* Task cancellation by OS is difficult to control, and differs substantially by device manufacturer - some simply force background task suspension when the app suspends to improve performance/battery life, and there is nothing you can do about that. So, please check if this happens on other devices too
* See if setting priority to 0 (high priority) makes a difference (you have set it to 10, which is low)
* If none of this works, consider configuring the downloader to 'runInForeground' on Android (see the docs)
* It _is_ normal for the task to restart from the beginning if it fails (or is canceled) and you have retries remaining. There is no standardized way to pause/resume uploads, so the only standardized way is to try again.

**Comment by tbigueres** [comment]
Thank you for noticing the AWS credentials I've just removed them !

**Comment by tbigueres** [comment]
I will try the different things you suggest !

**Comment by 781flyingdutchman** [comment]
> Thank you for noticing the AWS credentials I've just removed them !

Just know they can still be found (there is edit history in comments) so if these are not temporary credentials I strongly suggest you change them :)

**Comment by 781flyingdutchman** [comment]
A few other thoughts:
1) You should not add a `Content-Length` header (not sure it hurts, but the plugin does this for you)
2) The file appears to be quite big, and may therefore exceed the default 9 minute limit for background tasks, which may be what triggers the cancellation. If so, the only way around that for uploads is to configure for running in the foreground, see [here](https://pub.dev/packages/background_downloader#configuration)
3) Not sure what the location of your file is, but make sure you have access to that location when your app is in the background. It is better not to use `BaseDirectory.root` and instead use `Task.split` as in the following example:
```dart
final (baseDirectory, directory, filename) = await Task.split(filePath: yourPath);
final task = UploadTask(
        url: 'https://google.com',
        baseDirectory: baseDirectory,
        directory: directory,
        filename: filename);
```

**Comment by tbigueres** [comment]
Thank you for your quick answers ! 

Quick question concerning foreground mode. You mention that the app needs to display a notification while doing foreground upload. Is this something that is handled by the background_downloader library, or do we need to implement it ? 
As I've seen that there is a configureNotification I was wondering if this is something I should use ? But my understanding is that this is for download only. 

Thanks

**Comment by 781flyingdutchman** [comment]
Yes, you do need to show a 'running' notification and you need to do that using the library. You need to first test and ask for permission,  and configure the notification per the docs before enqueueing the task

**Comment by tbigueres** [comment]
Hey thank you for all your insights ! 

I've managed to show upload notifications. 
I guess you need to update your documentation about notification as it states that this is only for downloads (first sentence): 
<img width="812" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/2139076/24c99910-1e1c-4d5b-b87e-f8429fc7572d">

From my understanding and tests : 
- When using foreground service on Android, you can display upload notifications for Android
- This does not work for iOS (only download notifications are available) 
Do you confirm ? 

I see that indeed it depends on the phone I'm using (exemple motorola kills the task even if it is in foreground for some reasons). 

We will do some more testing and I'll let you know if we can close the ticket !

**Comment by 781flyingdutchman** [comment]
Notifications can indeed be configured also for uploads (I'll update the docs) on both Android and iOS. IOS notifications behalve differently though, eg the .running notification is not updated during upload or download.

iOS does not have the concept of `runInForeground` and does not need it, as you can configure the `resourceTimeout` and give the task weeks to complete if needed.

I hope that clarified things

**Comment by tbigueres** [comment]
Hi @781flyingdutchman 
Thank you very much for all your informations and support. It is muchly appreciated. 

I have a last question and we can then close this issue. 
Is there a possibility to do chunk upload with your library ? Or do we need to manually handle the chunk of the file and then do multiple uploads with the library ? 

Thanks for your answer !

**Comment by 781flyingdutchman** [comment]
Not at this moment. There isn't a good standard for chunking uploads (although AWS and GCP support a very similar approach) but I understand a standard is in development. Until then you'll have to manually chunk and create multiple upload tasks

**Comment by FluffyDiscord** [comment]
TUS upload standard would be too niche?

**Comment by 781flyingdutchman** [comment]
I think so: the questions in getting tend to be about uploads to the big cloud platforms
