### ISSUE TITLE
Content type is not set in UploadTask on iOS

### ISSUE THREAD

**Issue by ekuleshov** [781flyingdutchman/background_downloader#303]
**Describe the bug**
I need to submit a `application/x-www-form-urlencoded` data and enqueueing the `UploadTask` with `mimeType: 'application/x-www-form-urlencoded'` parameter worked fine on Android, but not on the iOS.

It looks like the iOS implementation is not using the `mimeType` parameter to set the `Content-Type` http header when server request is created.

**To Reproduce**
It is hard to reproduce this in an isolated example. I traced this issue to this code in the iOS native implementation:

https://github.com/781flyingdutchman/background_downloader/blob/ec8223477da54a5a93f0bf54e0c05cfe650af07e/ios/Classes/BDPlugin.swift#L270-L275

The Android native code seems to be setting the `Content-Type` header using `task.mimeType` as expected.

https://github.com/781flyingdutchman/background_downloader/blob/ec8223477da54a5a93f0bf54e0c05cfe650af07e/android/src/main/kotlin/com/bbflight/background_downloader/UploadTaskWorker.kt#L117-L124

**Expected behavior**
It would be great if Android and iOS implementations behaved the same.

**Logs**
N/A

**Code**
N/A

**Additional context**
N/A

**Comment by 781flyingdutchman** [comment]
Published in V8.5.0
