### ISSUE TITLE
Unable to resume a task after getting the task from taskForId

### ISSUE THREAD

**Issue by sahilasopa** [781flyingdutchman/background_downloader#305]
I am storing the download in my own database as I wish to store more metadata alongside what's provided, I start download using the code below
```dart
final task = DownloadTask(
      url: downloadUrl,
      filename: 'video-${id}.mp4',
      directory: appDocDir.path,
      updates: Updates.statusAndProgress,
      retries: 5,
      allowPause: true,
      metaData: id,
    );
```
and store the returned task.id in my database so I can use it on other screens or maybe after a pause + restart, there can be cases when user paused the download and cleared the notification, so now user has no way to resume a download, this is where I use the APIs provided by this package, in my download page, I follow this flow
```dart
// assuming I already made sure that the task was paused
final task = await FileDownloader().taskForId(downloadItem!.taskId); // this returns Task?
if (task != null){
  if (await FileDownloader().taskCanResume(task)){ // can resume expects Task
    FileDownloader().resume(task); // This expects DownloadTask, but there is no method to get a DownloadTask
  }
}
```

**Expected behavior**
I dug down a bit, and although the signature for resume is `Future<bool> resume(DownloadTask task)`, it calls the method `_downloader.resume(task)`, which has a signature `Future<bool> resume(Task task)`, so why not change the signature of the public resume method

**Comment by sahilasopa** [comment]
Note: I am aware we can cast Task to DownloadTask, but it does not make sense to
first cast Task to DownloadTask
then it casts that DownloadTask to Task

**Comment by 781flyingdutchman** [comment]
Thanks for sharing. I think the more elegant way to solve this is to have `taskForId` return a properly typed Task. Right now resume is limited to DownloadTask (though that may change) so it makes sense to have the resume call expect one. I may look into this for a future update - for now you'll have to cast

**Comment by 781flyingdutchman** [comment]
HI, turns out that `taskForId` does already return a properly typed task, so instead of changing the signature of the public API (which is not something I want to do) just just need to test that the task you get is indeed a `DownloadTask` before calling `resume`. There is no need to cast:
```dart
// assuming I already made sure that the task was paused
final task = await FileDownloader().taskForId(downloadItem!.taskId);
if (task is DownloadTask){ // now the rest works without any issues and you can combine with the next `if`
  if (await FileDownloader().taskCanResume(task)){
    FileDownloader().resume(task);
  }
}
```
