### ISSUE TITLE
how to remove temp files when using config.useCacheDir = Never

### ISSUE THREAD

**Issue by Rohan487** [781flyingdutchman/background_downloader#307]
Hey, I've been using this plugin since 2023, and it's been great. However, recently, while checking my app, I noticed it was taking up 1 GB of space on my phone. This got me thinking about whether the background downloader plugin deletes temporary files when config.cachDir is set to 'never.' By default, the OS automatically clears files inside cacheDir, but what happens when it's set to 'never'? I'm curious about how the plugin handles incomplete downloads (paused or stuck).

If it does delete the temp files, that's great. If not, what's the proper process for deleting temporary files when canceling a task?

**Comment by 781flyingdutchman** [comment]
You are absolutely right that this may leave stray files (see the [documentation](https://github.com/781flyingdutchman/background_downloader/blob/main/CONFIG.md) that the OS will not clean up. Best to periodically check for files that "belong to" the downloader and clear those up (if you are not using the default cache behavior).
