### ISSUE TITLE
Library not working for Android 10

### ISSUE THREAD

**Issue by kcs-ravindrapatil** [781flyingdutchman/background_downloader#308]
**Library not working for Android 10**
I have try to implement this library for my project this is working well for **Android- 11, 12, 13 and 14**, but not work for **Android  10**.

**I got below error**

_**Error for taskId 640986285: /data/user/0/com.androidApp/cache/com.bbflight.background_downloader1990916996 -> /sdcard/download/ClubO7/Statement1715596642307.pdf**_

**_java.nio.file.NoSuchFileException: /data/user/0/com.clubO7/cache/com.bbflight.background_downloader1990916996 -> /sdcard/download/ClubO7/Statement1715596642307.pdf_**

**Comment by 781flyingdutchman** [comment]
Most likely the OS on this device has deleted the temporary file used to store the file during download. That behavior is highly dependent on vendor implementation of Android. Check the [configuration docs](https://github.com/781flyingdutchman/background_downloader/blob/main/CONFIG.md) on how to use `Config.useCacheDir` and experiment with different settings. Note that if you don't use cache dit you will have to clean up stray files in the Documents directory yourself.
