### ISSUE TITLE
iOS taskStatusCallback and taskProgressCallback not called

### ISSUE THREAD

**Issue by johnsonejezie** [781flyingdutchman/background_downloader#309]
**Describe the bug**
Weird that iOS is still not working for my app. I traced the issue to this point. https://github.com/781flyingdutchman/background_downloader/blob/174ad58184705dec82e205b18344c32ee8aadc6a/ios/Classes/TaskFunctions.swift#L492
The iOS invoked statusUpdate never get to the flutter side setMethodCallHandler. Uploads to server complete successfully (I can confirm this from the server.)

**To Reproduce**
My code
`static setup() {
    FileDownloader().registerCallbacks(
      taskStatusCallback: taskStatusCallback,
      taskProgressCallback: taskProgressCallback,
    );
  }

  static taskStatusCallback(TaskStatusUpdate update) {
    print("taskStatusCallback: status ${update.status}");
    if (update.status == TaskStatus.complete) {
      // final group = update.task.group;
      final metaData = update.task.metaData;
      final responseBody = update.responseBody;
      print("##### $responseBody");
      if (responseBody == null) return;
      // if (group == imageUploadGroup) {
      final json = jsonDecode(responseBody);
      _updateMessageImage(json: json, metaData: metaData);
      // }
    } else if (update.status == TaskStatus.failed) {
      final body = update.exception;
      print("##### ${body?.toJson()}");
    }
  }

  static taskProgressCallback(TaskProgressUpdate update) {
    print("taskProgressCallback: progress ${update.progress}");
  }

  static Future initiateUpload(
      {required File file, required String messageId, String? metaData}) async {
    try {
      String jwt = await FirebaseAuthenticationHelper().getIdToken();
      final url = FConfig.getBaseUrl() + "media";
      var headers =
          getFileUploadHeaders(jwt, Constants.PREFIX_MESSAGES, file.path);
      final task = UploadTask.fromFile(
        file: file,
        url: url,
        taskId: messageId,
        headers: headers,
        httpRequestMethod: "POST",
        metaData: metaData ?? "",
        fields: {Constants.PREFIX: Constants.PREFIX_MESSAGES},
        updates: Updates.statusAndProgress,
        requiresWiFi: false,
      );
      print("#### Task Ready ${task.toJson()}");
      final successfullyEnqueued = await FileDownloader().enqueue(task);
      print("#### Started $successfullyEnqueued");
    } catch (e) {
      GlibLogger.logger.e("#### $e");
    }
  }`
Android works fine.

**Comment by johnsonejezie** [comment]
I see this is caused by isolate I use for websocket. It works fine when isolate is killed

**Comment by 781flyingdutchman** [comment]
Yes, you cannot use the downloader from an isolate other than the main isolate

**Comment by johnsonejezie** [comment]
> Yes, you cannot use the downloader from an isolate other than the main isolate

I am not calling downloader from an isolate. I call it on main isolate. iOS callBacks doesn't work when there is an isolate running even though downloader was not called in the isolate.

**Comment by 781flyingdutchman** [comment]
Then it sounds like the other plugin isn't playing nice 🙂. There is a degree of cooperation required and as far as I know the downloader does that - eg it works with Firebase, which used some unusual approaches.
