### ISSUE TITLE
Bug With Cancellation Of Task

### ISSUE THREAD

**Issue by sahilasopa** [781flyingdutchman/background_downloader#313]
I initially start with starting a download by doing something like this
    final task = DownloadTask(
      url: baseItem.downloadUrl,
      filename: 'video-${baseItem.id}.mp4',
      directory: appDocDir.path,
      updates: Updates.statusAndProgress,
      retries: 5,
      allowPause: true,
      metaData: baseItem.id,
    );
    
I set retries to 5 to counter cases of bad network, wifi switch and so on, but when I click cancel button in the notification or call `FileDownloader().cancelTaskWithId(taskId)`, it has to be called 5 times before it actully cancels, it retries on all those 5 attempts and starts the download again

**Comment by 781flyingdutchman** [comment]
Which platform (s) do you observe this issue, and which version of the downloader are you using? Can you share logs, both from flutter and Android/iOS?

**Comment by sahilasopa** [comment]
> Which platform (s) do you observe this issue, and which version of the downloader are you using? Can you share logs, both from flutter and Android/iOS?

I have only tested this on Android, and this issue isn't constant, if I do the same step on 5 different downloads, this occurs only on 1-2 of them, and the logs are no different either, they're same as the ones which succeeded
