### ISSUE TITLE
Question: How does the native `HoldingQueue` relate to the tasks DB

### ISSUE THREAD

**Issue by lyio** [781flyingdutchman/background_downloader#319]
**Is your feature request related to a problem? Please describe.**
Not sure if this is a feature request, but it certainly is a question.
According to the documentation about the `HoldingQueue`

>A HoldingQueue is native to the OS and can be configured using FileDownloader().configure to limit the number of concurrent tasks that are executed (in total, by host or by group). When using this queue you do not change how you interact with the FileDownloader, but you cannot implement your own holding queue. Because this queue is native, it will continue to run when your app is suspended by the OS, but if the app is killed then tasks held in the holding queue will be lost (unlike tasks already enqueued natively, which persist)

Losing the tasks in the queue does not really sound enticing, so I was wondering if there is a way to make the queue persistent on the native side. As far as I understand the plugin, once actually enqueued the tasks are already persisted natively, right?

Implementing a `PersistentTaskQueue` has the drawback that it would only be active as long as the App is not suspended. Or am I misunderstanding how this works?

**Comment by 781flyingdutchman** [comment]
And yes if you implement a TaskQueue with persistent storage on the Dart side (so not a HoldingQueue) then those tasks will stop getting enqueued once the app suspends.
That said, WorkManager implementation is manufacturer specific and many will kill WorkManager tasks when the app is killed, so if this is a concern you should always check on startup what tasks are actually active (query FileDownloader) versus what you think is active (database).
