### ISSUE TITLE
Error information for failed downloads

### ISSUE THREAD

**Issue by khoadng** [781flyingdutchman/background_downloader#326]
**Is your feature request related to a problem? Please describe.**
I want to let user know why a specific download failed so it would be nice to have a way to access it.

**Comment by 781flyingdutchman** [comment]
The final `TaskStatusUpdate` has fields with response code and - if there was an error - the `TaskException` and other exception information. I think that should be enough to let your user know what went wrong - but let me know if you feel there's something missing.

**Comment by khoadng** [comment]
it works great! Thanks.
