### ISSUE TITLE
[Android] notification icon

### ISSUE THREAD

**Issue by Nico04** [781flyingdutchman/background_downloader#336]
It would be great to be able to customize Android notifcations icon, depending on state, like we can do with `configureNotification`
Thanks :)

**Comment by 781flyingdutchman** [comment]
Actually, before I make this too complicated: have you tried defining drawables in your Android app with the same name as those used in the plugin? I think if you create, for instance, a drawable in your app's `res/drawable` folder with the name `outline_download_done_24.xml` this will effectively override the icon used by the plugin.

Can you check and confirm this is the case or not?
