### ISSUE TITLE
Large attachment uploading takes a while

### ISSUE THREAD

**Issue by jamescardona11** [781flyingdutchman/background_downloader#337]
Does anyone know if the app-systems have limits on file upload speed; 

In my case, large files are taking a long time, or should I use some special strategy for large files?

**Comment by hedi-ghodhbane** [comment]
I also have a similar issue, the upload gets to 0.999, when i reload the image is uploader to server but it takes too much time to update the status to completed.

**Comment by 781flyingdutchman** [comment]
I'm not aware of any but the OS does manage how much resource is given to the background task, and that, together with possible server limitations, may affect download and upload speeds.
