### ISSUE TITLE
Build failure with `background_downloader` due to missing Kotlin plugin

### ISSUE THREAD

**Issue by Romanbot4** [781flyingdutchman/background_downloader#338]
**Description:**
I encountered a build failure when trying to use the `background_downloader` package in my Flutter project. The error indicates that the `kotlin-serialization-compiler-plugin-embeddable:1.7.10` could not be found.

**Environment:**
- OS: Windows 10, Version 10.0.19045.4598
- Plugin version: 8.5.2
- Flutter doctor output:
  ```
  [√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4598], locale en-US)
  [√] Windows Version (Installed version of Windows is version 10 or higher)
  [√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
  [X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
      ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
  [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
  [√] Android Studio (version 2024.1)
  [√] VS Code (version 1.90.2)
  [√] Connected device (3 available)
  [√] Network resources

  ! Doctor found issues in 1 category.
  ```

Steps to Reproduce:
1. Create a new Flutter project:
   ```bash
   flutter create example
   cd example
   ```
2. Add the `background_downloader` package:
   ```bash
   flutter pub add background_downloader
   ```
3. Run the project:
   ```bash
   flutter run
   ```

**Expected Result:**
The project should build and run without issues.

**Actual Result:**
The build fails with the following error:
```
Execution failed for task ':background_downloader:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':background_downloader:compileDebugKotlin'.
   > Could not resolve all files for configuration ':background_downloader:kotlinCompilerPluginClasspathDebug'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
```

**Possible Workaround:**
Works fine on [7.12.3](https://pub.dev/packages/background_downloader/versions/7.12.3)

**Comment by dickermoshe** [comment]
@Romanbot4 What did you do to fix this?

**Comment by 781flyingdutchman** [comment]
You need to upgrade to Kotlin 1.9.20

**Comment by dickermoshe** [comment]
@781flyingdutchman 

https://github.com/781flyingdutchman/background_downloader/pull/342

I think what I've added is accurate. Please double check if I missed something.

Seems that many people are running into this.

Also, I would recommend putting Setup info on top of the docs, instead of the bottom.
