### ISSUE TITLE
moveToSharedStorage does fail on iOS

### ISSUE THREAD

**Issue by chuber50** [781flyingdutchman/background_downloader#34]
First of all, thanks for the nice new plugin which i happily replaced the outdated flutter_downloader with!

An issue came up:
```
final task = DownloadTask(url: finalUrl, filename: fileName);
var downloadResult = await FileDownloader().download(task);
if (downloadResult == TaskStatus.complete) {
      final newFilePath = await FileDownloader().moveToSharedStorage(task, SharedStorage.downloads);
      if (newFilePath == null) {
        ERROR Msg
      } else {
        FileService().openFile(newFilePath);
      }
    }
```

Moving the file to the shared storage works fine on Android and my iOS simulator, but fails on some customer iPhones, returning null.
Feels like some permission issue..
Any idea what I could be missing? Thanks!

ad:
Or is there an option to open a file (e.g. pdf) direct after download from the app's document folder? I guess, i have to move it to the shared storage to allow an associated pdf viewer app to open it..

**Comment by chuber50** [comment]
Issue persists on as soon as i debug on a real device or publish a release:
`2023-04-21 12:05:50.566586+0200 AppName[844:109294] [Downloader] Failed to create directory /var/mobile/Containers/Data/Application/C3B5AEA3-D47D-48E0-8D76-62F33E7B3E1A/Downloads: You don’t have permission to save the file “Downloads” in the folder “C3B5AEA3-D47D-48E0-8D76-62F33E7B3E1A”.
`

**Comment by 781flyingdutchman** [comment]
Hi, thanks for highlighting this. I've fixed both issues in the latest version (overwriting the file is now default, and no error on `moveToSharedStorage'). I also wanted to clarify a few things that may affect what you're trying to do, as iOS is finicky w.r.t. the private app sandbox:
* On iOS, shared storage is unfortunately not the same as it is on Android: the user (or other aps) cannot access files in the "shared storage" as on iOS each app has a sandbox that you cannot get out of (this is highlighted in the documentation). Obviously, apps like Safari are able to store files in a properly shared "Downloads" folder, but I have not been able to figure out how to do that. Therefore, when calling `moveToSharedStorage` you are really moving the file to the subdirectory "Downloads" of the app's Documents directory. The files there remain private to the app
* To allow access to files by apps like the Files app you need to make the available. See [this article](https://www.appcoda.com/files-app-integration/) for how you can do that (it requires the files to be stored in the normal `BaseDirectory.documents` directory - not the shared storage directory)

Hope this helps!

**Comment by dwaiting** [comment]
I am facing the same issue as @chuber50.

`FileDownloader().moveToSharedStorage(task, SharedStorage.downloads);` works ok on the emulator but when I try on a physical device I get the same error:

`[Downloader] Failed to create directory /var/mobile/Containers/Data/Application/763DC745-CF31-4F00-A261-815AFF3682C8/Downloads: You don’t have permission to save the file “Downloads” in the folder “763DC745-CF31-4F00-A261-815AFF3682C8”.`

@781flyingdutchman mentions:

> Therefore, when calling moveToSharedStorage you are really moving the file to the subdirectory "Downloads" of the app's Documents directory.

According to the above statement, the function is currently trying to create the "Downloads" directory in the wrong place.

**Comment by 781flyingdutchman** [comment]
Hi, sorry to hear that - I thought we had fixed that issue. It's a holiday weekend here so I likely won't get to this for a bit, unfortunately. Meanwhile, if you are familiar with iOS sandbox permissions, do you know why I can't seem to move files to the "proper" Downloads directory (the one that is actually visible to other apps)? As mentioned in this thread, I can't get that to work, and that is why the hack is to create a Downloads directory within Documents instead (also to allow a degree of similarity with other platforms) but obviously I'd much prefer this to work properly on iOS.

**Comment by dwaiting** [comment]
I'm no iOS expert but it looks like iOS only lets Safari use the main Downloads directory.

If this is true, the most correct answer is probably that `moveToSharedStorage` should throw an exception on iOS because it is simply not possible.

In the documentation, you could mention that adding the following to `Info.plist` will make the downloads visible in the File browser, which is probably the main goal for most people:

```
<key>LSSupportsOpeningDocumentsInPlace</key>
<true/>
<key>UIFileSharingEnabled</key>
<true/>
```

**Comment by 781flyingdutchman** [comment]
Unfortunately I can't really resolve the issue elegantly, as iOS does not allow access to shared directories for media and downloads, so we have to 'fake' the shared storage by creating appropriately named subdirectories in the app's Documents directory. This is not consistent with Android or Desktop, but given the typical pairing of Android and iOS it felt better to implement a fake (with warnings in the documentation) than to just not implement anything. Developers can choose whether they use this on iOS, or find another solution.

Implemented in V7.5.0

**Comment by chuber50** [comment]
Thanks for your efforts!

**Comment by hadi7khan** [comment]
> moveToSharedStorage

What should we do for iOS now? tried to do this: baseDirectory: Platform.isAndroid
            ? BaseDirectory.applicationSupport
            : BaseDirectory.applicationDocuments, task is finished: "[Downloader] Finished task with id 1056542107" but where is image downloaded? not able to see it on iOS

**Comment by 781flyingdutchman** [comment]
You can get the path by calling `path = await task.filePath()`, see [here](https://pub.dev/documentation/background_downloader/latest/background_downloader/Task/filePath.html)
