### ISSUE TITLE
Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.

### ISSUE THREAD

**Issue by hongfeiyang** [781flyingdutchman/background_downloader#348]
**Describe the bug**

**To Reproduce**
Include this package in any android projects. It will try to resolve to a kotlin-serialisation-compiler-plugin-embeddable:1.7.10 which does not exist in maven central. (Maven central has 1.9 and above)

**Expected behavior**

**Logs**
If possible, include logs that capture the issue:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_downloader:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':background_downloader:compileDebugKotlin'.
   > Could not resolve all files for configuration ':background_downloader:kotlinCompilerPluginClasspathDebug'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
        Required by:
            project :background_downloader

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
Code
```

**Additional context**

**Comment by 781flyingdutchman** [comment]
You have to use Kotlin 1.9. you'll have to Google how to change the Gradle build file, as it depends a bit on what version of Gradle plugin you use

**Comment by hongfeiyang** [comment]
> You have to use Kotlin 1.9. you'll have to Google how to change the Gradle build file, as it depends a bit on what version of Gradle plugin you use

Thank you so much, I upgraded my kotlin version to 1.9.0 and included `org.jetbrains.kotlin.plugin.serialization` 1.9.0 in my project and it all works fine now ;) thanks

**Comment by 781flyingdutchman** [comment]
Great - I suggest going with 1.9.20 and I believe you then don't need to separately import the serialization plugin. Kotlin is already at 2.0 now, so even 1.9.0 is relatively old

**Comment by tmo1** [comment]
> You have to use Kotlin 1.9. you'll have to Google how to change the Gradle build file, as it depends a bit on what version of Gradle plugin you use

I just ran into this. For the record, in my case (an Android Studio project) the necessary changes were to the project level `build.gradle` file (the commented lines were the previous settings):

```
buildscript {
    ext.kotlin_version = "2.1.20"
    //ext.kotlin_version = "1.6.0"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.20'
        //classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20'
    }
}
```
