### ISSUE TITLE
IOS download error

### ISSUE THREAD

**Issue by pigivc** [781flyingdutchman/background_downloader#351]
Hello

Could you help me with this please? I get this error in IOS release mode (everything is alright in debug mode):

`"System.Exception","Message":"TaskFileSystemException: Failed to move file from /var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/com.bankofcitic.mobile/CFNetworkDownload_sfCq3k.tmp to /var/mobile/Containers/Data/Application/790472D0-4D3C-4DBD-9698-4578BA56DEF9/Documents/72b98f8c-358b-4350-8ff6-a47de3490ca0.mp3: “CFNetworkDownload_sfCq3k.tmp” couldn’t be moved because you don’t have permission to access “Documents”.`

Thanks in advance

**Comment by 781flyingdutchman** [comment]
Please read the documentation on required permissions and restrictions on iOS files

**Comment by pigivc** [comment]
> Please read the documentation on required permissions and restrictions on iOS files

but I have already read the whole document and configured it properly and as I said it works in dubug mode perfectly and I don't need special ios permission since I am storing the downloaded file in app document folder.

**Comment by 781flyingdutchman** [comment]
I recommend searching this "issues" section as I recall a few other instances where people had this issue on specific iOS devices. It has never been clear what the issue was

**Comment by pigivc** [comment]
Ok, thanks for your help and time.

**Comment by 781flyingdutchman** [comment]
Did you manage to get it to work?

**Comment by pigivc** [comment]
> Did you manage to get it to work?

No, I didn't,  I'm not sure, but perhaps the culprit is the certificate that I sign the app with, since it happens after I sign the app in release mode
