### ISSUE TITLE
kotlin-serialization-compiler-plugin-embeddable:1.7.10.

### ISSUE THREAD

**Issue by sunilshedge** [781flyingdutchman/background_downloader#352]
Invalid depfile: D:\sunil\mayamovies\.dart_tool\flutter_build\39496ebe27dd12be7ed1cb971bdc7671\kernel_snapshot.d
Invalid depfile: D:\sunil\mayamovies\.dart_tool\flutter_build\39496ebe27dd12be7ed1cb971bdc7671\kernel_snapshot.d
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_downloader:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':background_downloader:compileDebugKotlin'.
   > Could not resolve all files for configuration ':background_downloader:kotlinCompilerPluginClasspathDebug'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://jitpack.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
        Required by:
            project :background_downloader

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 20s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by 781flyingdutchman** [comment]
You need to upgrade your kotlin compiler to version 1.9.20
