### ISSUE TITLE
downloadBatch can't be cancelled mid download

### ISSUE THREAD

**Issue by dimityrivanov** [781flyingdutchman/background_downloader#356]
I have used this call 'downloadBatch' to download batch of items but for example when I try to destroy the BackgroundDownloader and reset all the tasks the downloadBatch continues to work and not stopping until all the tasks are done, should it be able to cancel it as well ?

**Comment by DenisMrGnusa** [comment]
same issue,

**Comment by dimityrivanov** [comment]
@781flyingdutchman Hey can we think something about it here ?
