### ISSUE TITLE
can't be cancelled mid download  all cancel api 

### ISSUE THREAD

**Issue by ANC1024GO** [781flyingdutchman/background_downloader#358]
* ## background_downloader: ^8.5.2

**Describe the bug**
all cancel api can't be cancelled mid download.
see this log is not stoping 

**Code**
```
 onElapsedTime: (elapsed) async {
        if(elapsed.inSeconds > 15){
          FileDownloader().cancelTaskWithId(curTask!.taskId).then((val){});
        }
        print('Elapsed time: ${elapsed}');
      }
```

**Logs**
```
flutter: Elapsed time: 0:00:05.000000
flutter: Elapsed time: 0:00:10.000000
flutter: Elapsed time: 0:00:15.000000
flutter: Elapsed time: 0:00:20.000000
flutter: Elapsed time: 0:00:25.000000
flutter: Elapsed time: 0:00:30.000000
flutter: Elapsed time: 0:00:35.000000
```

**Comment by 781flyingdutchman** [comment]
The task should cancel, but canceling doesn't stop the periodic timer which is simply set to periodic calls to `onElapsedTime`. your call to `download` will complete once the task cancels, and your lambda function will go out of scope.
