### ISSUE TITLE
Execution failed for task ':background_downloader:compileDebugKotlin'. > Error while evaluating property 'filteredArgumentsMap' of task ':background_downloader:compileDebugKotlin'.    > Could not resolve all files for configuration ':background_downloader:kotlinCompilerPluginClasspathDebug'.       > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.         Searched in the following locations:

### ISSUE THREAD

**Issue by sunilshedge** [781flyingdutchman/background_downloader#359]
Execution failed for task ':background_downloader:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':background_downloader:compileDebugKotlin'.
   > Could not resolve all files for configuration ':background_downloader:kotlinCompilerPluginClasspathDebug'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
        Searched in the following locations:

**Comment by 781flyingdutchman** [comment]
Hi, you need to upgrade to Kotlin 1.9.20 or higher, see the docs for how this is done in different situations
