### ISSUE TITLE
Nothing happens when clicking on a finished download

### ISSUE THREAD

**Issue by rekire** [781flyingdutchman/background_downloader#36]
I would like to have a callback when the user has clicked on a notification. So that the user can interact with the downloaded file like basically just opening it.

**Comment by 781flyingdutchman** [comment]
Added in version 5.6.0

Adds handler for when the user taps a notification, and an `openFile` method to open a file using the platform-specific convention.

To handle notification taps, register a callback that takes `Task` and `NotificationType` as parameters:

```
FileDownloader().registerCallbacks(
            taskNotificationTapCallback: myNotificationTapCallback);
            
void myNotificationTapCallback(Task task, NotificationType notificationType) {
    print('Tapped notification $notificationType for taskId ${task.taskId}');
  }
```

To open a file, call `FileDownloader().openFile` and supply either a `Task` or a full `filePath` (but not both) and optionally a `mimeType` to assist the Platform in choosing the right application to use to open the file.
The file opening behavior is platform dependent, and while you should check the return value of the call to `openFile`, error checking is not fully consistent.

Note that on Android, files stored in the `BaseDirectory.applicationDocuments` cannot be opened. You need to download to a different base directory (e.g. `.applicationSupport`) or move the file to shared storage before attempting to open it.

If all you want to do on notification tap is to open the file, you can simplify the process by 
adding `tapOpensFile: true` to your call to `configureNotifications`, and you don't need to 
register a `taskNotificationTapCallback`.
