### ISSUE TITLE
Binary upload header 'Content-Disposition' is not encoded properly

### ISSUE THREAD

**Issue by Ansis100** [781flyingdutchman/background_downloader#376]
The header parameter `filename` in `multipartUpload` is properly encoded:
https://github.com/781flyingdutchman/background_downloader/blob/0fd47563c0239c5dcf8e1e0d9cd425ff0433e9d8/lib/src/desktop/upload_isolate.dart#L134-L137

However, in `binaryUpload` it is not:
https://github.com/781flyingdutchman/background_downloader/blob/0fd47563c0239c5dcf8e1e0d9cd425ff0433e9d8/lib/src/desktop/upload_isolate.dart#L52-L53

Which leads to "Invalid HTTP header" errors when trying to upload files with non-latin characters.

**Comment by 781flyingdutchman** [comment]
Included in V8.5.6
