### ISSUE TITLE
taskNotificationTapCallback not called on group notification

### ISSUE THREAD

**Issue by mattia-venturini** [781flyingdutchman/background_downloader#378]
**Describe the bug**
When I set a taskNotificationTapCallback for a group that is not the defaultGroup, it's never called.
I'm on Android 14.

**To Reproduce**
1. Open the example app in the package
2. Inside the initState add the following method call to the FileDownloader instance
```
.registerCallbacks(
    group: 'bunch',
    taskNotificationTapCallback: myNotificationTapCallback)
```
3. Click on the button "Load a bunch"
4. Click on the notification that appears

**Expected behavior**
I should see in the logs that myNotificationTapCallback is called.

**Comment by 781flyingdutchman** [comment]
Notification tap detection for notification groups is currently not supported. Tapping such a notification will simply bring the app to the foreground
