### ISSUE TITLE
[iOS] Notifications permission is requested on enqueue even if I don't use notifications config

### ISSUE THREAD

**Issue by slaci** [781flyingdutchman/background_downloader#38]
On iOS when I call `enqueue` notification permission is requested regardless the config. The problem is in [Downloader.swift#94](https://github.com/781flyingdutchman/background_downloader/blob/V5.4.6/ios/Classes/Downloader.swift#L94) the `notificiationConfigJsonString` variable holds `"null"` for me, then it is checked againts `nil` after, so I get into the permission requesting if.

The origin of the problem is in [native_downloader.dart](https://github.com/781flyingdutchman/background_downloader/blob/V5.4.6/lib/src/native_downloader.dart#L71) because that arg is json encoded even if its null, so that's why the null is passed as string. Real dart null is converted to NsNull on Swift side correctly.

On android its not noticable because not much happens based on the config. Shouldn't permission be requested from Android 13 though? 🤔 

Created a PR for it.

**Comment by 781flyingdutchman** [comment]
Thanks much! Included in V5.5.0. And yes, for Android Tiramisu the plugin does ask for notification permissions (see line 956 in TaskWorker.kt).
