### ISSUE TITLE
Question - using background_downloader to offload in background basic HTTP tracking queries

### ISSUE THREAD

**Issue by evaisse** [781flyingdutchman/background_downloader#388]
Hello, 

We have some basic http GET call to track user navigation (when user navigate from screen to screen).
Do you think `background_downloader` is reliable enough to offload those calls which are currently handled by the main flutter process ?
Is that a possible use-case for `background_downloader` ? 

Thx,

**Comment by 781flyingdutchman** [comment]
Yes, you can use it for "set and forget" type GET requests, perhaps using a `DataTask` but you could also look into the `Dio` package that is often used for foreground GET requests.

**Comment by 781flyingdutchman** [comment]
You should of course also consider packages and services specific to this purpose, eg Firebase Analytics
