### ISSUE TITLE
Issue with Pausing Downloads on iOS Cancelling Instead of Pausing in background_downloader

### ISSUE THREAD

**Issue by KevinShingala** [781flyingdutchman/background_downloader#390]
I am encountering an issue with the background_downloader package when pausing a download on iOS. Instead of the download being paused, it gets cancelled. This behavior is only observed on iOS, and the download works as expected on Android.

Steps to Reproduce:

- Start a download using the background_downloader package on an iOS device.
- Try to pause the download using the provided pause() method.
- Observe that instead of pausing, the download gets cancelled.

Expected Behavior:
When the pause button is clicked, the download should pause and allow resuming later.

Actual Behavior:
When the pause button is clicked, the download is cancelled instead of being paused.

**Comment by 781flyingdutchman** [comment]
See #389

**Comment by KevinShingala** [comment]
So what you suggest
