### ISSUE TITLE
moveToSharedStorage not working in background mode on Android

### ISSUE THREAD

**Issue by NavidFarahmandian** [781flyingdutchman/background_downloader#394]
The moveToSharedStorage function fails when the app is running in the background on Android. It works correctly while the app is in the foreground but encounters issues during background execution, preventing files from being moved to shared storage (e.g., the 'Downloads' folder).

**Comment by 781flyingdutchman** [comment]
Can you elaborate on this? What happens, what did you expect to happen, which OS/platform, what version of the OS, what plugin, a repeatable code snippet and logs?

**Comment by tunggTO2xxx** [comment]
@781flyingdutchman I have a problem when save file path on Android. I don't know how to save file into external storage because I cannot set useExternalStorage = true. Can you help me resolve this problem?
