### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by PierreBresson** [781flyingdutchman/background_downloader#40]
Hi,

I'm using `await FileDownloader().downloadBatch(...)` and I couldn't find a way to disable notification (for a specific batch download or in general).
Is it possible? I'm on `background_downloader: ^5.4.5`

Thanks :)

**Comment by 781flyingdutchman** [comment]
Hi, thansk for reaching out. There was an issue #38 that triggered the permissions dialog on iOS even when no notifications were configured. Please upgrade to `^5.5.0` (or run `flutter pub upgrade`) to ensure you are on the latest version. Please let me know if that works so I can close the bug, or if you still have an issue then please provide more details:
* how did you configure the notification?
* how did you start the download?
* on what platform does this present an issue?
* what exactly happens, in sequence?
* Log messages if possible

Thanks!

**Comment by PierreBresson** [comment]
Hi,

Looks like 5.5.0 solved the problem.

Thanks for the nice library and quick answer :)
