### ISSUE TITLE
Cannot download file when http POST request using a Map

### ISSUE THREAD

**Issue by tunggTO2xxx** [781flyingdutchman/background_downloader#400]
**Describe the bug**
Hello I'm having a problem with downloader package. When I used DownloadTask with http POST request and set header in type 'application/x-www-form-urlencoded' and request body was a Map, the response for this download was always failed. The error that I received is 'Map<String, dynamic> is not subtype of String'. I understand this that I need to change my body request to String but when I do that it's still fail because the body request isn't matching with the header's type. Why I cannot use request body as a Map?

**Code**
```
final headers = {
      'content-type: 'application/x-www-form-urlencoded',
      'authorization: 'Bearer $accessToken'
};

final requestModel = {
         "data": fileMain?.toJson(),
};

await FileDownloader().download(
     DownloadTask(
            url: url,
            post: requestModel,
            headers: headers,
            filename: fileName,
            directory: destinationPath,
            baseDirectory: BaseDirectory.applicationDocuments,
            httpRequestMethod: 'POST',
            requiresWiFi: true,
            updates: Updates.statusAndProgress,
       ),
       onProgress: (progress) => print('Progress: ${progress * 100}%'),
       onStatus: (status) => print('Status: $status'),
 );
```
More information I'm using Flutter SDK 3.19.6, Dart SDK 3.3.4 and background_downloader 7.11.0
Any help or information on how to solve this issue will help.
Thank you.

**Comment by 781flyingdutchman** [comment]
Thanks for sharing this issue. Can you share the full log that includes the error and stack trace?

**Comment by tunggTO2xxx** [comment]
Thanks for your reply on my issue. This morning, I resolved my problem. In my opinion, you should have a request body example for each content type of header because when I read your comment in code and readme, I was really confused about POST request body that I should use.
