### ISSUE TITLE
[Question] about IOS NSURLSession.background limit

### ISSUE THREAD

**Issue by bladeofgod** [781flyingdutchman/background_downloader#401]
Hello,  i'm an android developer, and i recently read some article  about Ios's NSURLSession-limit, and found out in `URLSessionConfiguration.background` way the `httpMaximumConnectionsPerHost` will limited at 6. So, i go checked your code and found it's used same function. 
I'm confuse if  set `maxConcurrentByHost` or `maxConcurrent` on ios has will worked ? or , am I completely mistaken?

```
    static func createUrlSession() -> Void {
        if UrlSessionDelegate.urlSession != nil {
            return
        }
        let config = URLSessionConfiguration.background(withIdentifier: UrlSessionDelegate.sessionIdentifier)
        let defaults = UserDefaults.standard
        let storedTimeoutIntervalForResource = defaults.double(forKey: BDPlugin.keyConfigResourceTimeout) // seconds
        let timeOutIntervalForResource = storedTimeoutIntervalForResource > 0 ? storedTimeoutIntervalForResource : BDPlugin.defaultResourceTimeout
        os_log("timeoutIntervalForResource = %d seconds", log: log, type: .info, Int(timeOutIntervalForResource))
        config.timeoutIntervalForResource = timeOutIntervalForResource
        let storedTimeoutIntervalForRequest = defaults.double(forKey: BDPlugin.keyConfigRequestTimeout) // seconds
        let timeoutIntervalForRequest = storedTimeoutIntervalForRequest > 0 ? storedTimeoutIntervalForRequest : BDPlugin.defaultRequestTimeout
        os_log("timeoutIntervalForRequest = %d seconds", log: log, type: .info, Int(timeoutIntervalForRequest))
        config.timeoutIntervalForRequest = timeoutIntervalForRequest
        let proxyAddress = defaults.string(forKey: BDPlugin.keyConfigProxyAdress)
        let proxyPort = defaults.integer(forKey: BDPlugin.keyConfigProxyPort)
        if (proxyAddress != nil && proxyPort != 0) {
            config.connectionProxyDictionary = [
                kCFNetworkProxiesHTTPEnable: true,
                kCFNetworkProxiesHTTPProxy: proxyAddress!,
                kCFNetworkProxiesHTTPPort: proxyPort,
                "HTTPSEnable": true,
                "HTTPSProxy": proxyAddress!,
                "HTTPSPort": proxyPort
            ]
            os_log("Using proxy %@:%d for all tasks", log: log, type: .info, proxyAddress!, proxyPort)
        } else {
            os_log("Not using proxy for any task", log: log, type: .info)
        }
        UrlSessionDelegate.urlSession = URLSession(configuration: config, delegate: UrlSessionDelegate.instance, delegateQueue: nil)
    }
```

**Comment by 781flyingdutchman** [comment]
In my experience the `httpMaximumConnectionsPerHost ` property does not really work, as servers have different ways to implement this (and for example using HTTP2 this is bypassed altogether).  The way I have implemented this is therefore on the client side, by counting the number of tasks that are active with a given host, and not scheduling new tasks if that number equals the maximum set - so I am not using `httpMaximumConnectionsPerHost ` at all.

**Comment by bladeofgod** [comment]
> In my experience the `httpMaximumConnectionsPerHost ` property does not really work, as servers have different ways to implement this (and for example using HTTP/2 this is bypassed altogether, as multiple requests are carried over 1 connection). See for example this [thread](https://forums.developer.apple.com/forums/thread/73565). The way I have implemented this is therefore on the client side, by counting the number of tasks that are active with a given host, and not scheduling new tasks if that number equals the maximum set - so I am not using `httpMaximumConnectionsPerHost ` at all.

I see, thanks for your reply. :)
