### ISSUE TITLE
"TaskException: Could not enqueue task ParallelDownloadTask" on IOS

### ISSUE THREAD

**Issue by bladeofgod** [781flyingdutchman/background_downloader#405]
**Describe the bug**
Hi , I found some error log about download failed on iOS at v8.5.6。 
error msg is : "TaskException: Could not enqueue task ParallelDownloadTask". 

**To Reproduce**
actually I can't reproduce it .

**Expected behavior**
I wanna know witch situation will cause this exception ?

**Logs**
If possible, include logs that capture the issue:
```
logs
```
TaskException: Could not enqueue task ParallelDownloadTask

**Comment by 781flyingdutchman** [comment]
There is likely a more detailed log message in the iOS console. For example, a parallel downloadtask can fail to enqueue if the initial head request made when enqueing fails (for example, when there is no internet connection at the time of enqueue - this is different from a regular task).

**Comment by bladeofgod** [comment]
> There is likely a more detailed log message in the iOS console. For example, a parallel downloadtask can fail to enqueue if the initial head request made when enqueing fails (for example, when there is no internet connection at the time of enqueue - this is different from a regular task).

I see, thank you very match.
