### ISSUE TITLE
DataBase contains upload tasks in enqueued state although it was uploaded to server. 

### ISSUE THREAD

**Issue by hedi-ghodhbane** [781flyingdutchman/background_downloader#412]
**Describe the bug**
I'm using background_downloader to upload pictures to server. I need to handle the uploading when i enqueue while i'm offline, and once internet is back or when i close & reopen the app, i need to fetch enqueued tasks from db and show them in UI for the user to be aware of these tasks. 

However, sometimes db contains enqueued tasks that are actually uploaded and stays there forever. 

**To Reproduce**
1. Upload tasks while in offline mode
2. kill the app
3. Re open the app and get records from db

**Code**
If possible, paste in the code snippet where you interact with the package:
```
    uploader.fileDownloader.database.allRecords().then((tsk) async {
      for (var a in tsk) {
        final path = await a.task.filePath();
        if (a.status == TaskStatus.enqueued) {
          runningTasks.add(RunningUploadTask(
            id: a.taskId,
            path: path,
            progress: a.progress,
          ));
        }
      }
    });
```

**Comment by 781flyingdutchman** [comment]
Please carefully read the [docs](https://github.com/781flyingdutchman/background_downloader?tab=readme-ov-file#central-monitoring-and-tracking-in-a-persistent-database) on how to use the database. Because events happen in the background, you need to also use `resumeFromBackground` after registering your listeners at startup.

**Comment by 781flyingdutchman** [comment]
That is indeed surprising. Do you have any more info and logs about when that happens? Fore example, there should be an Android log when the plugin cannot post the update to the application, and therefore stores it locally 

Also, you could check out branch 'callbacks' where I introduce an option for a Dart function callback that should be called also when the app is suspended (work in progress).

**Comment by 781flyingdutchman** [comment]
If you are refusing the same taskId then yes, that's an issue. If you're not, then I don't think it should be but it is going to be confusing.  Are you using multiple uploads of portions/chunks of the same file? Can you try without doing multiple uploads for the same file?
