### ISSUE TITLE
Couldn't upload to s3 bucket using presigned url in chunks

### ISSUE THREAD

**Issue by ujas-m-simformsolutions** [781flyingdutchman/background_downloader#414]
**Describe the bug**
I'm trying to upload an image file to s3 bucket in chunks. First I tried with dio and it works fine but if I use background_downloader then aws throws this error.

**Expected behavior**
file in chunks should be uploaded without any error.

**Logs**
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<AWSAccessKeyId>IDsadadas</AWSAccessKeyId>
<StringToSign>PUT

image/png
1731328859
```

**Code**
This is how I create upload task,
```
for (final partFile in partFiles) {
      final url = res[partFile.index]['ETag'];

      final (baseDirectory, directory, filename) =
          await Task.split(filePath: file.path);

      final uploadTask = UploadTask(
        url: url,
        updates: Updates.statusAndProgress,
        httpRequestMethod: 'PUT',
        headers: {
          'Range':
              'bytes=${partFile.start}-${partFile.index == partFiles.length ? '' : partFile.end}',
        },
        post: 'binary',
        baseDirectory: baseDirectory,
        directory: directory,
        filename: filename,
      );
      tasks.add(uploadTask);
    }
```
Uploading,
```
fileDownloader.uploadBatch(
      tasks,
      batchProgressCallback: (succeeded, failed) {
        print('s -> $succeeded');
        print('f -> $failed');
      },
    );
```
Doing this always fails for me but if I use dio it works,
dio code,
```
Future<String> dioUpload(String url, dynamic data) async {
    try {
      final pdio = Dio()..interceptors.removeImplyContentTypeInterceptor();
      final res = await pdio.put(
        url,
        data: data,
        options: Options(
          requestEncoder: (request, options) {
            return data;
          },
        ),
        onSendProgress: (count, total) {
          print('count: $count');
          print('total: $total');
        },
      );
      return (res.headers.map['etag'] as List<String>).first;
    } on DioException catch (e) {
    }
  }
```
Addition context,
If I upload this directly without dividing it into chunks then it works fine as well.

Thank you in advance.

**Comment by 781flyingdutchman** [comment]
The logs suggest an issue with the signature on the URL.  I a not sure how you create that signature, but I would suggest looking into that and confirming that the url and headers you set on the `UploadTask` are exactly the same as those you set using `Dio`. 

It is also possible this is related to the `Range` header. I just introduced an option for partial uploads using that header, and it is stripped before connecting to the server. Did you add that to tell the downloader what range of you big file to upload, or is this part of the Amazon protocol?  Can you check if you force the version of background downloader to 8.5.6 in pubspec.yaml if that solves the problem?

**Comment by ujas-m-simformsolutions** [comment]
As you can see in shared for dio upload I don't need to add any header in the request as it is presinged url. And also if there is any else included in the header then it will fail. So background downloader doesn't include anything right?

Also, I currently using 8.7.0 version of the background downloader.

**Comment by 781flyingdutchman** [comment]
Can you try forcing version 8.5.6?

**Comment by ujas-m-simformsolutions** [comment]
@781flyingdutchman I'm getting same result with `8.5.6`

**Comment by 781flyingdutchman** [comment]
Got it, a few questions/comments. Let's assume the big file you want to upload is 1000MB and the chunk you are trying to upload with the task above is the portion from 100-200MB. In that case:
1. Is the file you reference in the task the big file, or only the chunk? (i.e. is the file of length 1000MB or 100MB?)
2. You add a Range header. Does that indicate the range of the part within the big file? So in this case, would the Range be 100-200MB?
3. Can you print the headers that are going to the server in the Dio example? You say there are none but you are explicitly removing a content-type header by adding `Dio()..interceptors.removeImplyContentTypeInterceptor()` which tells Dio not to include that header.  That doesn't mean it doesn't add other headers, so I would really like to see what headers are going to the server
4. Can you print and compare the url (which will have query parameters) between the Dio version and the downloader version? Make sure to replace the actual values with `<token>` or something, as you don't want to expose auth info here, but we need to see if the urls are truly the same format/structure

I suspect the issue is with the headers that the downloader adds (e.g. it will add a content-type header) but I am not sure that is the only thing that's causing this to not work.

**Comment by pn-smcom** [comment]
> **Describe the bug** I'm trying to upload an image file to s3 bucket in chunks. First I tried with dio and it works fine but if I use background_downloader then aws throws this error.
> 
> **Expected behavior** file in chunks should be uploaded without any error.
> 
> **Logs**
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>SignatureDoesNotMatch</Code>
> <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
> <AWSAccessKeyId>IDsadadas</AWSAccessKeyId>
> <StringToSign>PUT
> 
> image/png
> 1731328859
> ```
> 
> **Code** This is how I create upload task,
> 
> ```
> for (final partFile in partFiles) {
>       final url = res[partFile.index]['ETag'];
> 
>       final (baseDirectory, directory, filename) =
>           await Task.split(filePath: file.path);
> 
>       final uploadTask = UploadTask(
>         url: url,
>         updates: Updates.statusAndProgress,
>         httpRequestMethod: 'PUT',
>         headers: {
>           'Range':
>               'bytes=${partFile.start}-${partFile.index == partFiles.length ? '' : partFile.end}',
>         },
>         post: 'binary',
>         baseDirectory: baseDirectory,
>         directory: directory,
>         filename: filename,
>       );
>       tasks.add(uploadTask);
>     }
> ```
> 
> Uploading,
> 
> ```
> fileDownloader.uploadBatch(
>       tasks,
>       batchProgressCallback: (succeeded, failed) {
>         print('s -> $succeeded');
>         print('f -> $failed');
>       },
>     );
> ```
> 
> Doing this always fails for me but if I use dio it works, dio code,
> 
> ```
> Future<String> dioUpload(String url, dynamic data) async {
>     try {
>       final pdio = Dio()..interceptors.removeImplyContentTypeInterceptor();
>       final res = await pdio.put(
>         url,
>         data: data,
>         options: Options(
>           requestEncoder: (request, options) {
>             return data;
>           },
>         ),
>         onSendProgress: (count, total) {
>           print('count: $count');
>           print('total: $total');
>         },
>       );
>       return (res.headers.map['etag'] as List<String>).first;
>     } on DioException catch (e) {
>     }
>   }
> ```
> 
> Addition context, If I upload this directly without dividing it into chunks then it works fine as well.
> 
> Thank you in advance.

Set mimeType to empty string :) It helps because the library adds a Content-Type header, which does not allow AWS when uploading to a pre signed url.
