### ISSUE TITLE
Android: Unable to compile in a "simplest possible scenario" 

### ISSUE THREAD

**Issue by YesThatGy** [781flyingdutchman/background_downloader#417]
**Describe the bug**
When I try to use the example lib/* files in a freshly created project (flutter create...) the result will not compile to Android 

This started when I had trouble getting it to compile in any way in an existing project. To try to isolate the problem I tried integrating it into a brand new project and couldn't. 

**To Reproduce**
1. flutter doctor (confirm all is well) 
2. create a new project 
3.  flutter pub add background_downloader 
4. copy example files
5) resolve all other deps
6) attempt to run - see the errors 

**Expected behavior**
The example of background_downloader running on my Android device or virtual device

**Logs**
If possible, include logs that capture the issue:
```
See attached file "typescript" for what it looks like at bash CLI. I had similar errors trying to add background_downloader to an existing project. 
[typescript.txt](https://github.com/user-attachments/files/17778575/typescript.txt)

```

**Environment**

Redhat Fedora 40, Android Studio 2024.1.1, Java 17, all updates applied within last 30 days. 

**Code**
If possible, paste in the code snippet where you interact with the package:
```
Code
```

**Additional context**

**Comment by YesThatGy** [comment]
PS: I *can* run the example directly if I gh clone the project and open the .../example folder in Android Studio. 

I tried copying lib/*, assets/*, and pubspec.yaml to a new project and that didn't work either: same error.

**Comment by YesThatGy** [comment]
Using rsync, meld, and a bunch of restorations from backup, I found that if I made these changes to these files, I could get this to compile without any reported issues, see git.diff.txt. 

[git.diff.txt](https://github.com/user-attachments/files/17791581/git.diff.txt)

**Comment by 781flyingdutchman** [comment]
Not sure exactly what you're trying to do here, but please read the [Android setup instruction](https://pub.dev/packages/background_downloader#android) which tell you to make sure you use Kotlin 1.9 or better (which seems to be the issue you have run into).
