### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by hedi-ghodhbane** [781flyingdutchman/background_downloader#424]
**Describe the bug**
This bug is happening to some users ( Android for now ). We have a custom SSL certificate but this is very random and happening to around 1% of the users. 
The file is enqueued, then it's failed with this error.

**Comment by 781flyingdutchman** [comment]
I suspect it's related to [this](https://stackoverflow.com/a/78309587)

**Comment by K01010010** [comment]
I'm also have that issue, on android 9 (API 28). I'm setted certificate for dio, and for http overrider, and my certifcate working for simple api requests, but, I cannot set my certificate for android 9 for loading files with that package
