### ISSUE TITLE
Is there any way to force use pure dart on android platform?

### ISSUE THREAD

**Issue by bailyzheng** [781flyingdutchman/background_downloader#428]
Is there any way to force use pure dart on android platform or ios platform? 

So that this lib can be used on android below api 21. 

I think it should give a way not to use URLSessions  or DownloadWorker.

**Comment by 781flyingdutchman** [comment]
Android 21 was released more than 10 years ago. It is more likely the minSDK will go up in future releases.

**Comment by bailyzheng** [comment]
> Android 21 was released more than 10 years ago. It is more likely the minSDK will go up in future releases.

There are also a lot of TVs TV boxes or boards running lower Android version. 

Windows and Linux are using pure dart code. right?  I think it is easy to add this option.

This is a wonderful lib. If this option can be added, it is perfect.
