### ISSUE TITLE
M3u8 download as a single task?

### ISSUE THREAD

**Issue by Prince-of-death** [781flyingdutchman/background_downloader#429]
**Is your feature request related to a problem? Please describe.**
It seems almost impossible to download m3u8 file as mp4 from outside so i think it should be buildin

**Describe the solution you'd like**
Able to download m3u8 as mp4

**Additional context**
This i needed for a core part of my app I have been using this plugin for a long time and i like this work. You put out so much effort into it so i appriceate that. Plz implement this feature. [https://github.com/781flyingdutchman/background_downloader/issues/232

**Comment by 781flyingdutchman** [comment]
Thanks for raising this. I am not familiar with his format, but after a bit of Googling I understand it's essentially a playlist format. It should be easy to convert that playlist into individual download tasks (you can look at other dart packages that parse the m3u8 file, available on pub dev). The bigger issue is that you need ffmpeg to translate the downloaded TS files and merge them into a single MP4. I don't think that's available on mobile, but it's also really not the job of the downloader, so this is not a feature I will add. If you develop something that works with the downloader then please add a reference to it here, so others can benefit from it.
