### ISSUE TITLE
Allow uploads to specify HTTP method

### ISSUE THREAD

**Issue by lyio** [781flyingdutchman/background_downloader#43]
The plugin defaults to using a `POST`. My backend requires these uploads to be a `PUT`, though. 

So it would be nice to be able to switch these over. The `post` field on the `UploadTask` is used to differentiate between binary and multi-part uploads. On the `DownloadTask` the field is used to trigger a `POST` instead of a `GET` *and* contains the post body data.

Maybe this could be cleaned up a bit?

**Comment by 781flyingdutchman** [comment]
Good idea. While perhaps not ideal, I'd like to keep the `post` meaning and function as it is (in hindsight I should have called it `body`). What we could do is add a `method` or `httpMethod` field to the 'Request` class (which is a superclass for the Tasks) that, if provided, overrides the default method used (which is GET for Request and Download tasks, and POST for Upload tasks and Download tasks where `post` is set). That makes it fully backwards compatible (i.e. no major version change required) and does add the flexibility you need. You could override with any of the HTTP methods. Thoughts?

**Comment by lyio** [comment]
While confusing at first, I understand your thoughts with the `post` field. 

Adding a `method` parameter seems like the best way to deal with this.

**Comment by 781flyingdutchman** [comment]
Implemented in V6: you can specify `httpRequestMethod` on a `Request` or `Task` to override the default.
