### ISSUE TITLE
Redirects are not being followed but throw an error instead

### ISSUE THREAD

**Issue by jangxx** [781flyingdutchman/background_downloader#55]
According to the documentation, redirects should be followed by the downloader, but when I try to download a file from a URL which redirects to a S3 bucket address, I get the following exception:

```
I/TaskWorker( 8604): Response code 302 for download from  <url>
I/TaskWorker( 8604): Could not read response content from httpResponseCode 302: java.lang.NullPointerException: connection.errorStream must not be null
```

Using version 6.1.2 on Android with flutter 3.7.3 and Dart 2.

**Comment by 781flyingdutchman** [comment]
Can you confirm that the redirect works as intended on other platforms (e.g. iOS)?

**Comment by 781flyingdutchman** [comment]
[Here's](https://developer.android.com/reference/java/net/HttpURLConnection#response-handling) what the Android documentation says about following redirects. In  particular, redirects are limited to 5, and does not follow redirects from HTTP to HTTPS or vice versa. The latter in particular may be your issue- can you confirm?

**Comment by jangxx** [comment]
Ah okay, that's good to know, thanks. In my case I'm indeed redirecting from a development server running on my own PC using HTTP to an AWS URL which uses HTTPS. This should fix itself in the deployed version then however, since the deployed server uses HTTPS for obvious reasons.
