### ISSUE TITLE
Notification not showing in IOS

### ISSUE THREAD

**Issue by mdusaama0** [781flyingdutchman/background_downloader#58]
I'm using this package to download mp3 files. In iphone 12 (iOS version 16.5) everything is working perfect. But no notification is showing when I'm testing in iphone X (iOs version: 16.5) and iphone 7 (iOS version: 15.7). But task is downloading in directory. Foloowing is the code.

final task = bd.DownloadTask(
          url: url,
          filename: '$name.mp3',
        ); // define your task
        bd.FileDownloader().configureNotification(
          running: bd.TaskNotification('Downloading', 'file: "$name.mp3"'),
          progressBar: true,
          tapOpensFile: true,
          complete: bd.TaskNotification('Download Complete', 'file: $name.mp3'),
          error: bd.TaskNotification('Download Failed', 'file: $name.mp3'),
        );
        final result = await bd.FileDownloader()
            .download(task); 
        print(result.status);

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out. I'm not sure I have enough data to help: It *sounds* like an issue with the Notification settings on those phones (perhaps you have inadvertently disabled Notifications?). Also, on iOS when the app is in the foreground notifications only show in the Notification Center, and are not presented to the user as they are on Android.

Finally, this isn't an issue, but a suggestion: you can simplify the way you use notifications by doing the configuration once, at app startup, and use "file: {filename}" (with the braces, without the quotes) in your Task Notification definition. It will be replaced by the name of the task, and the idea is that you *don't* configure notifications for every task.

**Comment by mdusaama0** [comment]
> Hi, thanks for reaching out. I'm not sure I have enough data to help: It _sounds_ like an issue with the Notification settings on those phones (perhaps you have inadvertently disabled Notifications?). Also, on iOS when the app is in the foreground notifications only show in the Notification Center, and are not presented to the user as they are on Android.
> 
> Finally, this isn't an issue, but a suggestion: you can simplify the way you use notifications by doing the configuration once, at app startup, and use "file: {filename}" (with the braces, without the quotes) in your Task Notification definition. It will be replaced by the name of the task, and the idea is that you _don't_ configure notifications for every task.

Thanks for reply. But my notification configuration is perfectly fine on those mobiles too. Because I’m receiving firebase notifications already. 
I'm confused why same code is working fine in iPhone 12.

**Comment by 781flyingdutchman** [comment]
Hi, I don't understand that either but without further information it's hard for me to help you. Two things to try:
1. Can you run the example app (see the [GitHub repo](https://github.com/781flyingdutchman/background_downloader) and see if the notifications work there? 
2. Can you provide Log messages from the console?

**Comment by Shahmirzali-Huseynov** [comment]
@mdusaama0 notification arrived on your device?

**Comment by mdusaama0** [comment]
Well it was not working for me. Then I show custom local notification when
downloading starts and finished. And used package openfile method to open a
file on local notification tap.

**Comment by Shahmirzali-Huseynov** [comment]
@mdusaama0 Thanks for your reply. in my situation just completed notification arrived. I will test and inform in this issue #75

**Comment by mdusaama0** [comment]
Good luck!
