### ISSUE TITLE
 A version upgrade of the http package is required.

### ISSUE THREAD

**Issue by azeek** [781flyingdutchman/background_downloader#63]
The Http package is now updated to the 1.0.0 stable version.

```
Because background_downloader 7.1.0 depends on http ^0.13.0 and no versions of background_downloader match >7.1.0 <8.0.0, background_downloader ^7.1.0 requires http ^0.13.0.
So, because filecast_mobile_flutter depends on both http ^1.0.0 and background_downloader ^7.1.0, version solving failed.
```

**Comment by 781flyingdutchman** [comment]
Thanks for highlighting - a future version will set the http version to `http: '>=0.13.0 <2.0.0'`, allowing both older and newer versions (as there is no functional difference between the two, other than the dart3 requirement).

In general, when you come across a conflict like this you can add a dependency override to your app's pubspec file, as described [here](https://dart.dev/tools/pub/dependencies#dependency-overrides). This works fine if there is no functional difference between the conflicting package versions.
