### ISSUE TITLE
Have you tested on OPPO devices or similar?

### ISSUE THREAD

**Issue by IlyaMax** [781flyingdutchman/background_downloader#65]
My issue is rather just a question so I could know does it have any sense to migrate to your package from flutter_downloader which has some issue with that https://github.com/fluttercommunity/flutter_downloader/issues/488

**Comment by 781flyingdutchman** [comment]
Hi! I haven't tested on those but if you have access to one try running the example app in the repo, or run the integration tests in the example/integration_tests folder. If they run, you should be good

**Comment by IlyaMax** [comment]
@781flyingdutchman im in progress of searching such a phone so I could test on it. I will let you know
