### ISSUE TITLE
Hello, how do I get the file size

### ISSUE THREAD

**Issue by qflbai** [781flyingdutchman/background_downloader#66]

**Comment by 781flyingdutchman** [comment]
The file size is currently not available while downloading - only progress as a fraction of the total file size (if provided by the server). You'd have to wait until the download completes (and get the file size from disk), or do a HEAD server request prior to the download to get information about the file you're going to download.

May I ask why you want the file size while downloading?

**Comment by qflbai** [comment]
Thank you for your help。Designers require display of file size to have a better user experience

**Comment by 781flyingdutchman** [comment]
Implemented in V7.4.0

Added method `expectedFileSize()` to `DownloadTask`, and added field `expectedFileSize` to  
`TaskProgressUpdate` (provided to callbacks or listeners during download), and `TaskRecord` 
entries in the database. 
Note that this field is only valid when 0 < progress < 1. It is -1 if file size cannot be determined.
