### ISSUE TITLE
error in example main.dart 

### ISSUE THREAD

**Issue by ondanplatform** [781flyingdutchman/background_downloader#68]
![Screenshot 2023-06-14 at 18 16 00](https://github.com/781flyingdutchman/background_downloader/assets/106958390/3548fabe-5eb3-41cf-81c8-e1da8166b51a)
     
```
     flutter doctor -v 
     
    • Framework revision f92f44110e (13 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mirzali/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

```

packages versions 

```
background_downloader: ^7.4.0
  connectivity_plus: ^4.0.1
  logging: ^1.2.0
```

my pubspec.yaml environment:

```
environment:
  sdk: ">=2.19.6 <4.0.0"
```

**Comment by ondanplatform** [comment]
![Screenshot 2023-06-14 at 18 21 49](https://github.com/781flyingdutchman/background_downloader/assets/106958390/e9ecf0b5-f491-412b-9038-94b1ee4814eb)

 I think the case must be TaskUpdate isn't it ?

**Comment by 781flyingdutchman** [comment]
Hi, the version you are using requires Dart 3, and while your Flutter Doctor says you have that installed, your pubspec.yaml says you intend to run this with Dart >=2.19.6, and your IDE therefore highlights these statements as not being compatible with Dart 2.19.6. You need to change your pubspec.yaml back to
```
environment:
  sdk: ^3.0.0
```
as it is in the `example/pubspec.yaml`. If you must be compatible with Dart 2, use version `^6.0.0` of the downloader.

The code you reference uses the new [Patterns](https://dart.dev/language/patterns) functionality in Dart 3: `update` is of type `TaskUpdate` and the switch statement switches based on the subtype: if it's a `TaskStatusUpdate` then it executes that code block, and `update.status` is valid; if it's a `TaskProgressUpdate` then it executes the second code block and `update.progress` is valid.

Again, the reason you're seeing the error is that you are trying to be compatible with Dart 2, and this version of the package is not.
