### ISSUE TITLE
ios crash: userNotificationCenter

### ISSUE THREAD

**Issue by The-Redhat** [781flyingdutchman/background_downloader#72]
Hey we see quite some crashes in firebase crashlytics that are connected to the background downloader package. We don't use 
the notification functionallity.

`UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate` is added in `AppDelegate.swift`

```
Crashed: com.apple.root.user-initiated-qos.cooperative
0  BaseBoard                      0x1d64c -[_BSActionResponder action_sendResponse:] + 528
1  BaseBoard                      0x18490 -[BSAction sendResponse:] + 76
2  UIKitCore                      0xd5a258 __91-[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:]_block_invoke_12 + 80
3  background_downloader          0xb878 $s21background_downloader10DownloaderC22userNotificationCenter_11willPresentSo33UNNotificationPresentationOptionsVSo06UNUsereF0C_So0I0CtYaFyyYacfU_ToTQ0_ + 120
4  libswift_Concurrency.dylib     0x41948 swift::runJobInEstablishedExecutorContext(swift::Job*) + 416
5  libswift_Concurrency.dylib     0x42868 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
6  libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
7  libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
8  libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
9  libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

**Comment by 781flyingdutchman** [comment]
Thanks for sharing. I suspect this is a thread issue and I may have to add `@MainActor` to the method - let me look into that. That said, if you don't use notifications at all then I suggest not adding the `UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate is added in AppDelegate.swift` to your AppDelate.

**Comment by 781flyingdutchman** [comment]
Added @MainActor annotation to `    public func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification) async -> UNNotificationPresentationOptions` which I *believe* addresses this issue, though as I have not been able to replicate it I am not 100% sure. Please try upgrading to version 7.4.1 (or 6.2.1 if you're on Dart 2) and please let me know if you still see CrashLytics errors for that new version. Thanks!

**Comment by The-Redhat** [comment]
Hey @781flyingdutchman thanks a lot for the quick response, I updated the plugin version and we will release it tomorrow. I will update you.

**Comment by snipd-mikel** [comment]
I also experienced this issue with 7.4.0. I have already updated to 7.4.1, and are waiting for the app to be approved by apple. I'll let you know once I know more. Thanks for the fix!

**Comment by The-Redhat** [comment]
Hey @781flyingdutchman the app update is live since two days and I don't see the error anymore. Thanks for the fast fix
