### ISSUE TITLE
App not staying alive when downloading many smaller sized files

### ISSUE THREAD

**Issue by cal-g** [781flyingdutchman/background_downloader#76]
Hi @781flyingdutchman 
During my testing on iOS the app stays alive for around 30 seconds after being backgrounded. I used a Timer function that prints every second to detect this.

During this 30 seconds if I start a background download at the 20 second mark for a single large file ~500 MB, the app stays alive for slightly longer say ~40-45 seconds and if the usual download duration for that file is 50 seconds the Timer function will print 70 seconds that means the Flutter app was made alive because of the download completion. It works very well here.

However, if I try to download 1000 files of around 1 - 5 MB by sending 50 records to download to the FileDownloader (calling `enqueue` or `download`)  at a time and as soon as any task is completed I send the next task from the remaining 950 by calling `enqueue` or `download` the app does not stay alive as opposed to when downloading a larger file. This way I am not able to send all of the 1000 tasks to the FileDownloader. Also, I don't think sending all the 1000 tasks to the FileDownloader is very good because it can choke the server.

I see in one of your posts you mentioned in your app you do similar downloads of 1000 files and is working well. How do you achieve that ? In our app I am trying to start a download process and then move the app to the background.

**Comment by 781flyingdutchman** [comment]
Hi, thanks for checking this out. You actually should queue all files in one go, as iOS penalizes multiple start/stops of a background queue (which is what you're doing). Just enqueue them all, but yield a few ms after every few calls to enqueue to avoid blocking the UI thread. You can see how this is done in the downloadBatch method. 

Also, the app staying alive or not is not something a developer can control, so you have to write your code with the assumption it may get pushed to background. That means checking completed downloads upon app startup/resume.

**Comment by cal-g** [comment]
Thanks @781flyingdutchman, enqueuing them all with a slight delay did help a bit.

**Comment by 781flyingdutchman** [comment]
All your enqueued downloads should complete - but they may not all complete while your app is in the foreground, and that's working as intended. When your app resumes, you should start your updates listener and then call `resumeFromBackground`. Any task status updates that your app missed (because it was in the background) will then get sent to your listener, allowing you to account for those updates and act on them. I dont actually use that myself (because I simply check whether the files I scheduled now exist, and Mark those as completed). As you said, I am using this successfully for thousands of downloads, each about 2MB in size, and it works well for me, even when the app moves to the background. Let me know what your experience is!

**Comment by cal-g** [comment]
Did some more testing and the experience is a lot better when enqueuing them all. Almost all the tasks get sent to the OS and the downloading proceeds. Although, I do see slight janks even with me yielding 50 ms every few calls I will need to take a look at this more but I have an idea of sending these `enqueue` or `download` calls slowly while in foreground but enqueue them quickly when brought to background. Hopefully iOS does not penalize me for doing this.

I had the same idea of just checking if the file exists but was exploring how tracking centrally could help my case. I might end up just doing the same way you did.
Thanks again.

**Comment by 781flyingdutchman** [comment]
You can use the trackTasks method, which does the "file exists" checking
for you, if you want. For 1000s of files I would suggest using a different
database than the default one - you can supply your own database
implementation when you call FileDownloader for the first time - see the
docs.

**Comment by cal-g** [comment]
Hi @781flyingdutchman  I found this very old post https://developer.apple.com/forums/thread/14854 , is this the same when you said that iOS penalizes for multiple start/stops ?


> Hi, thanks for checking this out. You actually should queue all files in one go, as iOS penalizes multiple start/stops of a background queue (which is what you're doing). Just enqueue them all, but yield a few ms after every few calls to enqueue to avoid blocking the UI thread. You can see how this is done in the downloadBatch method.
> 
> Also, the app staying alive or not is not something a developer can control, so you have to write your code with the assumption it may get pushed to background. That means checking completed downloads upon app startup/resume.

**Comment by 781flyingdutchman** [comment]
I had not seen that specific thread but yes it talks to the same design as
I understand it, which penalizes multiple start/stops of a background
session. Exactly what defines a session is not entirely clear to me, but it
seems clear that scheduling all tasks at once is preferable over breaking
it down.
I'd add that for my app, the Android background downloads are much faster
than the iOS ones, which I imagine has to do with the resource allocation
to the background thread that is different between OSes

**Comment by cal-g** [comment]
I think you got the reference in the commit message incorrect. Commit https://github.com/781flyingdutchman/background_downloader/commit/ae382421f271cc00b078462af83bc796fb334f0d actually references https://github.com/781flyingdutchman/background_downloader/issues/78

**Comment by 781flyingdutchman** [comment]
Ah, my bad. Don't know how to change without messing up GitHub so it'll have to stay 😊
