### ISSUE TITLE
Check if file exists in shared storage

### ISSUE THREAD

**Issue by dwaiting** [781flyingdutchman/background_downloader#78]
Thanks for the great package!

Is there an easy to way to check if a filename exists in shared storage (e.g. the downloads folder) before downloading?

Currently I download the file and move it to the downloads folder and it creates a new copy if it already exists. I'd prefer to implement a behavior similar to the Chrome browser where I will prompt the user to open the existing file rather than re-downloading it every time.

I don't see anything in the documentation or examples to test if a file exists in shared storage or to get the path of shared storage so I can test myself.

**Comment by 781flyingdutchman** [comment]
Hi, thanks for checking it out. There isn't currently a way to do this, but it's an interesting idea so let me think about how I might add this.

**Comment by 781flyingdutchman** [comment]
Added in V7.5.0, though with some limitations on Android due to the behavior of the MediaStore - see documentation.

**Comment by manandharsudhir** [comment]
The name appends the number at the end of extension like if I have file.pdf downloaded and if i again download the same file.pdf then the package saves the file as file.pdf(1) is it possible if it would be file(1).pdf
