### ISSUE TITLE
Build failed with an exception when change minSdkVersion.

### ISSUE THREAD

**Issue by huynguyen96419** [781flyingdutchman/background_downloader#79]
Thanks for the great package!
The plugin require minSdkVersion 24, so i was changed it. After run, it show the error:
`What went wrong:
Execution failed for task ':app:processDevDebugResources'`
`> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     /Users/nexle/Project/chat-application-mobile/build/app/intermediates/packaged_manifests/devDebug/AndroidManifest.xml:88: error: resource xml/provider_paths (aka com.nexlesoft.corechat.dev:xml/provider_paths) not found.
     error: failed processing manifest.`

So how to fix this?

**Comment by 781flyingdutchman** [comment]
Hi, when you change minSdkVersion for your app, that may cause compatibility issues with your app or with other plugins you use. Based on the description you provide, I don't think this has anything to do with the background_downloader package, so I'm afraid I can't help you with this.
