### ISSUE TITLE
downloaded filename for Android issue

### ISSUE THREAD

**Issue by chrisvidal** [781flyingdutchman/background_downloader#8]
On Android, the filename is always the same `downloadfile` followed by its suffix.
As for iOS, the filename is correctly deducted from the \filestream sent from the server.

**Comment by 781flyingdutchman** [comment]
Hi @chrisvidal , I know you closed this issue but wanted to clarify: you have to set a filename in the `BackgroundDownloadTask` and that is the filename that will be used.  We don't derive the filename from the URL or the server - you have to provide it before the download starts.
