### ISSUE TITLE
Update notification after download retry

### ISSUE THREAD

**Issue by theakanfecode1** [781flyingdutchman/background_downloader#81]
When my network connection is lost, the downloading process halts. Once the network is restored, the download resumes; however, the Android notification indicates that the download has failed. Additionally, a new download is initiated, starts from the beginning again.

Expected behavior: When the network disconnects, the download should pause and automatically resume from where it left off once the network is reestablished. Moreover, the notification should accurately reflect the ongoing download progress of the same task without creating another download.

Thank you.

**Comment by 781flyingdutchman** [comment]
Hi, this sounds like issue #77 which should have been fixed with version 7.5.0, published yesterday. Can you confirm that you're on that latest version when you see this issue? If not, please upgrade and close this issue - thanks!

**Comment by 781flyingdutchman** [comment]
By the way, on Android the behavior is that when the connection is lost, the task restarts from the beginning when the connection is restored - it does not resume. Not ideal, but not something I can control, as the Android OS simply cancels the background task uncermoniously, leaving no time for things like storing resume data.

**Comment by theakanfecode1** [comment]
Thanks for the update. I'm currently on Dart 2, can you please update the code for Dart 2 as I am currently on 6.2.1 (The lastest version that supports Dart 2).



> Hi, this sounds like issue #77 which should have been fixed with version 7.5.0, published yesterday. Can you confirm that you're on that latest version when you see this issue? If not, please upgrade and close this issue - thanks!

**Comment by theakanfecode1** [comment]
> By the way, on Android the behavior is that when the connection is lost, the task restarts from the beginning when the connection is restored - it does not resume. Not ideal, but not something I can control, as the Android OS simply cancels the background task uncermoniously, leaving no time for things like storing resume data.

Oh I understand. 
Kindly update the Dart 2 plugin so it can contain the fix you made for issue #77

**Comment by 781flyingdutchman** [comment]
The fix is added to V6.3.0, so please update to that version. Note that the Dart 2 version (V6) won't be maintained much longer, so I would encourage you to switch over to Dart 3 and use V7.

**Comment by 781flyingdutchman** [comment]
In V7.9.1 failed download tasks can now be resumed (under certain conditions) even if the Task.allowPause field is false. Resuming a failed task will attempt to continue the download where the failure occurred. If retries are set to a value >0 then retries will also first attempt to resume, and only start from scratch if that fails.

Tasks can only resume if the ETag header provided by the server is strong, and equal to the ETag at the moment the download was paused/failed, or if it is not provided at all.
