### ISSUE TITLE
How to store the downloaded file in the Files app on Android?

### ISSUE THREAD

**Issue by chrisvidal** [781flyingdutchman/background_downloader#9]
`baseDirectory: BaseDirectory.applicationDocuments` is invisible to the user on Android unfortunately and we can't force an absolute directory in the arguments `directory`

**Comment by 781flyingdutchman** [comment]
Correct - you can move your file there upon completion of the download (eg
by listening to the updates stream).

**Comment by chrisvidal** [comment]
good point, silly me :)

**Comment by 781flyingdutchman** [comment]
No worries - I understand your comment, I'm just trying to keep the package really simple and basic, and Android Downloads is a somewhat unique thing for which there isn't an equivalent in iOS, and which may require complexity around the type of file (eg media, document, etc). I'd rather that the user of the package decides if/how to deal with that than trying to build something into the package that will satisfy some, but confuse others.

As suggested, you can download to the temp directory, and upon completion move the file to its final destination along with any necessary permissions, metadata annotations, etc.

**Comment by 781flyingdutchman** [comment]
You can now call `moveToSharedStorage` to move a downloaded file to Android directories like Downloads

**Comment by mdusaama0** [comment]
When we moveToSharedStorage then on tap notification music does not redirect to the file. @781flyingdutchman

**Comment by 781flyingdutchman** [comment]
That's correct 😁. It's meant to be a convenience function *after* you complete a download. The notification is for during the download. If you want to open a moved file, then don't set `tapOpensFile` and instead respond to the notification tap yourself in the app, then call `openFile` with the file path of the moved file.
