### ISSUE TITLE
Build Flutter Android APK Too Large

### ISSUE THREAD

**Issue by PhuongTranIUH** [781flyingdutchman/background_downloader#97]
**Describe the bug**
Build flutter android apk too large

**To Reproduce**
- Flutter version: 3.10.5
1. Create a new app flutter
2. Run the command: flutter build apk --release
3. Output: File apk (17.1Mb)
4. Install background_donwloader package
5. Run the command: flutter build apk --release
6. Output: File apk (38.3Mb)

**Comment by 781flyingdutchman** [comment]
A lot of factors go into that that I don't control. Not an area of focus, sorry.
