### ISSUE TITLE
iOS crash after received a push Notification

### ISSUE THREAD

**Issue by jamescardona11** [781flyingdutchman/background_downloader#98]
**Describe the bug**
I have an issue when receiving a notification iOS, and the user taps on it; it is causing a crash in the application. I will attach an image of the crash report shown in Xcode.

**To Reproduce**
1. Have notifications iOS implement
2. Receive a notification that open the app
3. After receiving that notification start a download
4. See the error

**Expected behavior**
Open the app without crash

![image](https://github.com/781flyingdutchman/background_downloader/assets/65878592/426fb698-3942-4cd6-b524-ec797eb89322)

**Code**
My configuration for iOS is:
```
extension AppDelegate: UNUserNotificationCenterDelegate, MessagingDelegate {
    private func configureNotifications(application: UIApplication) {
        UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
....

```

```
@override
  Future<String?> downloadAttachmentFromS3Mobile({
    required String filename,
    required String path,
    required String preSignedUrl,
    required String attachmentId,
  }) async {
    final task = DownloadTask(
      url: preSignedUrl,
      filename: filename,
      directory: kFilesFolder,
      updates: Updates.statusAndProgress,
      retries: 5,
      allowPause: true,
      metaData: json.encode({kAttachmentId: attachmentId, kTaskAttachmentType: kTaskAttachmentDownload}),
    );

    final enqueue = await FileDownloader().enqueue(task);

    return enqueue ? task.taskId : null;
  }
```

**Additional context**

**Comment by 781flyingdutchman** [comment]
Thanks - what exactly is the error you're getting? Can you share the text from the dialog box that pops up when iOS crashes, and also the console log around the moment of the crash? Thanks!

**Comment by jamescardona11** [comment]
Thanks for the reply; I don't have a lot of information, but I added this log and this Xcode report. 
I'm going to replicate it again and I'll delivery the text from the dialog box. I come back latter.

[log.txt](https://github.com/781flyingdutchman/background_downloader/files/12114946/log.txt)
![Screenshot 2023-07-20 at 7 27 32 PM](https://github.com/781flyingdutchman/background_downloader/assets/65878592/7202e8b8-4c6e-494c-8ca8-e3de333c3ba3)

**Comment by 781flyingdutchman** [comment]
HI - I can't replicate it but the error message gives me a hint, so I'll make a change in the next release that should hopefully fix your problem

**Comment by jamescardona11** [comment]
Thank you, btw I used push notifications, but I don't have any configuration the library notifications.

**Comment by 781flyingdutchman** [comment]
Sorry, I don't quite understand what you mean. Are you using push notifications from another library, in addition to the background_downloader notifications?

**Comment by jamescardona11** [comment]
I'm using firebase notification but I don't have the config for this: FileDownloader().configureNotification

**Comment by 781flyingdutchman** [comment]
Sorry, again just to be clear:
* You are using Firebase
* You have NOT configured background_downloader notifications in your app (i.e you do not have `FileDownloader().configureNotification` anywhere in your app)
* You receive a push notification via Firebase (not from background_downloader) which, when tapped, opens your app
* When you then start a download, you get the error above

Is that sequence of events and conditions correct? If not, please correct - otherwise I cannot understand what is happening

**Comment by jamescardona11** [comment]
Is correct.

**Comment by 781flyingdutchman** [comment]
Ok, sorry about that. I think I have fixed this. Can you use the `dev` branch of the repo and test? Change your pubspec.yaml to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: dev
```

**Comment by 781flyingdutchman** [comment]
These changes are now also included in V7.7.0.  Please let me know if you still see this bug - otherwise please close this issue. Thanks!

**Comment by jamescardona11** [comment]
I'll test tomorrow, and I'll let you know.

**Comment by jamescardona11** [comment]
Seems was fixed
Thanks.

How I can contribute to the library, do you a roadmap or idea for new functionalities?

**Comment by 781flyingdutchman** [comment]
Great!  and thanks for the offer. There's no roadmap - in fact I'd like to minimize new development/functionality but I do respond to suggestions. For example issue #100 is a good suggestion. If you want to work on that, that would be great, though I have to be honest that the code is quite complicated (and a feature like that one needs to be implemented in Kotlin, Swift and Dart) so that may not be an easy one to start with.

**Comment by 781flyingdutchman** [comment]
Closing this issue as the bug itself was fixed - happy to continue the conversation though
